### ISSUE TITLE
Do we want an array of fingerprint contributions on result?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#10]
Copied from https://github.com/sarif-standard/sarif-spec/issues/15, created by @lgolding:

Action: @michaelcfanning

**Comment by lgolding** [comment]
Comment from @lgolding:

The idea is: some tools generate multiple fingerprints, for example:
1. The contents of the file
2. The region around the issue
3. The name of the file

If we did this, we would add a `result.computedFingerprint[]` alongside `toolFingerprint` ?

Issue mgmt systems would not know the significance of the various computed fingerprints, and so could not use them for baselining. But a direct producer could store multiple fingerprint in a log, use that log as a baseline in a subsequent run, and interpret the fingerprints that it itself had created.

Instead of an array, it might be a dictionary, where each fingerprint has an identifier.

**Comment by michaelcfanning** [comment]
I like your proposed change. Consider adding guidance to the producer: 1) generate a meaningful description as a dictionary key, 2) produce a stable fingerprint per documented technique, 3) create a new entry for fundamentally different fingerprinting approaches, 4) add new fingerprints but be cautious about removing them

**Comment by lgolding** [comment]
@michaelcfanning I retitled this issue. It's about fingerprint _contributions_. For the issue that addresses fully computed fingerprints, see newly filed #126.
