### ISSUE TITLE
Missing "not" in Appendix E.

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#101]
Appendix E. currently starts with:

> The SARIF format allows rule metadata to be included in a SARIF log file (see §3.12.14 and §3.27). A SARIF log file does need to include any rule metadata. 

I presume the second sentence is intended to be:

> A SARIF log file does **not** need to include any rule metadata.

**Comment by lgolding** [comment]
@lukecartey @michaelcfanning  I fixed this directly in the provisional draft.
