### ISSUE TITLE
run.invocation should be an array of invocation objects

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#102]
many tools require the execution of multiple programs to operate the tool.  SARIF should be able to capture this data.  I propose that the invocation property of the Run Object should be an array instead of a singleton.

**Comment by michaelcfanning** [comment]
Project editor's discussion approved this work item. We need clarifying text in the spec to describe when this corner case makes sense (in cases where multiple tool invocations are required to drive some end-to-end results production). In the common case, a tool runs with a single invocation to produce a list of results.
