### ISSUE TITLE
Settle on a small set of hash functions

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#107]

**Comment by michaelcfanning** [comment]
I'm not sure why we need to reduce the # of hash function kinds that are available. I do think we should make a recommendation on an algorithm that SHOULD be provided (in addition to whatever additional ones a tool may choose). SHA256 is a good candidate.

**Comment by lgolding** [comment]
@michaelcfanning Here's what I propose. First, here are the inputs to my reasoning:

- I don't want SARIF to be in the business of specifying an exhaustive list of acceptable algorithms. That's not our expertise, and I don't want to have to rev SARIF every time a hot new algorithm comes along.
- I certainly don't want to include the laundry list of algorithms from a Wiki article. There's nothing authoritative about that list. It's just some Wiki author's idea of a good list.

So I propose that the spec say this:

- The `file.hashes` array **SHOULD** include `"sha-256"`.
- To offer a choice of algorithms that maximize interoperability, the `file.hashes` array **MAY** include any value from the IANA registry of [Hash Function Textual Names](https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml). A SARIF consumer **SHALL** be able to compute a `"sha-256"` hash, and **SHOULD** be able to compute any of the hashes in the IANA registry.
- The `file.hashes` array **MAY** contain any other hash algorithm name, but at the expense of interoperability. A SARIF consumer **MAY** implement any hash algorithm, but it does not have to implement anything that's not in the IANA registry.
- Hash algorithm names are case-insensitive.

If any of the algorithms in the IANA registry are broken, we might want the spec to say that producers "**SHOULD NOT**" use them.

**Comment by katrinaoneil** [comment]
Not sure if this is going to be of any help, but attached is a [paper](https://github.com/oasis-tcs/sarif-spec/files/1826680/CryptoManifesto2015.pdf) I wrote on various cryptographic primitives and their implementations after researching a number of standards. Among other things, the paper provides recommendations for which hash functions to use and which to avoid.

**Comment by kupsch** [comment]
All hash functions produce collisions, so "that occasionally produces hash collisions" should be changed to "that are have known weaknesses allowing adversaries to more easily generate collisions".

Should the description of the value say the property's value is a string and SHOULD be a hexadecimal representation of the numeric value of the hash digest, unless the value is not numeric?

**Comment by lgolding** [comment]
@kupsch: Thanks for the suggestion. I made the following editorial change directly in the provisional draft (the **bold** words are for visibility here; I didn't bold them in in the draft):

> In situations where compliance and security are not a concern, a system might prefer to use a fast hash algorithm (such as MD5 or SHA-1) **even though they have known weaknesses that allow adversaries to more easily generate that occasionally produces hash collisions.**

**Comment by lgolding** [comment]
@katrinaoneil Thanks for the paper. I looked at the table.

@michaelcfanning @kupsch In the course of incorporating Jim's editorial suggestion about hash collisions, I re-read that paragraph. Since we _already have_ text that advises about when and when not to use "weak" hash algorithms ("In situations where compliance and security are not a concern..."), I _withdraw_ the last sentence of my proposal above (the sentence about advising against the use of certain algorithms).

So with all that said, what do you all think of my proposal above?

**Comment by kupsch** [comment]
I think it would be fine to remove the sentence

**Comment by lgolding** [comment]
@michaelcfanning @kupsch @katrinaoneil Ping -- any feedback on my proposal?

**Comment by kupsch** [comment]
I think the sentence "A SARIF consumer MAY implement any hash algorithm, but it does not have to implement anything that's not in the IANA registry." is unnecessary and should be removed.  I also do not think there needs to be an commentary on 'If any of the algorithms in the IANA registry are broken, we might want the spec to say that producers "SHOULD NOT" use them.' as including sha-256 as one of the hashes as recommended makes this irrelevant. It is still useful to include 'sha-1' as long as systems such as git use it.

There should be language that if you are using one of the hashes listed in the IANA registry, then the name SHALL be the name specified in the registry, otherwise the producer SHALL chose a suitable name not found in the registry.

Also for the description of the value, it should include something like:  "The property's value is a string and SHALL be a hexadecimal representation of the numeric value of the hash digest for all hashes that produce a numeric value."

**Comment by lgolding** [comment]
@kupsch @michaelcfanning 

Jim, I agree with most of your feedback:
- I'll remove the part telling producers that they "SHOULD NOT" include broken hashes.
- I'll add the part about the spelling of IANA-registered hashes.
- I'll add the part about the format of the property value.

The only part I disagree with is removing the assurance that producers don't have to implement anything that's not in the IANA registry. We've told producers that (1) They SHALL implement `sha-256`, and (2) They SHOULD implement the IANA-registered hashes. So you're right: if we say nothing else, producers are entitled to assume that that's _all_ they have to do. I still want to retain the explicit statement that they really don't have to do anything else. (Since that statement does not impose any normative requirements, I consider it within my editorial discretion :-).)

The result is:

- The `file.hashes` array **SHOULD** include `"sha-256"`.
- To offer a choice of algorithms that maximize interoperability, the `file.hashes` array **MAY** include any value from the IANA registry of [Hash Function Textual Names](https://www.iana.org/assignments/hash-function-text-names/hash-function-text-names.xhtml). A SARIF consumer **SHALL** be able to compute a `"sha-256"` hash, and **SHOULD** be able to compute any of the hashes in the IANA registry.
- The `file.hashes` array **MAY** contain any other hash algorithm name, but at the expense of interoperability. A SARIF consumer **MAY** implement any hash algorithm, but it does not have to implement anything that's not in the IANA registry.
- Hash algorithm names are case-insensitive.
- If a SARIF producer uses one of the hash algorithms in the IANA registry, it SHALL use the algorithm name as specified in the registry. If a SARIF producer uses any other hash algorithm, it can use any suitable name, except that it SHALL NOT choose a name defined in the registry.
- The hash value SHALL be represented as a string. For hash algorithms that produce a numeric value, that string SHALL be a hexadecimal representation of the numeric value of the hash digest.
