### ISSUE TITLE
Represent VCS properties

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#108]
We need a way to say something like “This tool was run against commit `056eefc` of repo `https://github.com/example/repo_1`.” That would be fairly easy to add, but it might be tricky to express it in a way that is independent of the VCS (Git vs VSTS version control vs Subversion…).

**Comment by michaelcfanning** [comment]
My hat in the ring proposal, add a new run.versionControl property. 

 versionControl 
  - url
  - branch
  - revisionId

**Comment by lgolding** [comment]
@michaelcfanning This looks good to me.

I think we need to bring this into CSD.1, given your customer's needs.

**Comment by lgolding** [comment]
Closed by 4cca601.
