### ISSUE TITLE
Specify how to treat a file that contains interleaved stdout/stderr

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#110]
_This issue was approved for resolution in CSD.1 in the TC meeting of 2/28/2018._

In #92, we introduced properties on the `invocation` object to specify the locations of files containing the contents of the `stdin`, `stdout`, and `stderr` streams. But many engineering systems redirect both `stdout` and `stderr` to the same file. How should SARIF represent that.

**Comment by michaelcfanning** [comment]
Resolution here: stderr is present, the tool populates it. stderr may be empty in this case. if stderr is not present at all in the SARIF, it is an indicator that it is not separated as a stream and stderr contents may be interleaved with stdout (if present)

**Comment by michaelcfanning** [comment]
We propose "stdOutStdErr" as a new propery to cover interleaving case.
