### ISSUE TITLE
Add property invocation.exitCode

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#111]
_This issue was approved for resolution in CSD.1 in the TC meeting of 2/28/2018._

Add an integer-valued property `exitCode` to the `invocation` object, to capture the tool's exit code.

**Comment by kupsch** [comment]
#115 contains a more comprehensive proposal for this ticket. I did not see this ticket had been opened.  This ticket should be closed in favor of #115.

**Comment by lgolding** [comment]
@kupsch Wow! #115 is awesome. I will make a change draft for that and get it on the agenda for the next meeting. Thank you!!

@michaelcfanning FYI
