### ISSUE TITLE
Capture a deterministic URI prefix

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#112]
Sometimes (in particular when retrieving files from a version control system), the file URIs are lengthy, they all start with a common prefix (for example, a prefix that specifies the host name, project name, and commit id), and they end with what looks like a normal file path (for example, `src/Sarif/Errors.cs`). In that case, it would be nice to strip off the long prefix, store it once in the SARIF file, and specify the individual file URIs as relative URIs containing just the trailing path components. That would reduce file size and improve readability.

One possibility is to use the `originalUriBaseId` mechanism:
```
{
  "runs": [
    {
      "originalUriBaseIds": {
        "SRCROOT": "https://github.com/Microsoft/sarif-sdk/blob/master"
      },

      "results": [
        {
          "locations": [
            {
              "analysisTarget": {
                "fileLocation": {
                  "uri": "src\Sarif\Errors.cs",
                  "uriBaseId": "SRCROOT"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

The problem is that URI base ids are used to represent locations that might vary from machine to machine, and so are non-deterministic. For this reason, Appendix F states that a deterministic SARIF producer must not emit the `originalUriBaseIds` property. If we now also use this mechanism in situations where the URI base id _is_ in fact deterministic -- that is, if we use it to refer to a fixed, globally accessible location -- then we won't be able to tell deterministic SARIF producers whether or not to emit the `originalBaseIds` property.

It would be nice to have a mechanism for specifying the common prefix of a set of globally accessible URIs.

**Comment by lgolding** [comment]
One possibility is simply to allow deterministic producers to emit URI base ids only when they know them to be deterministic -- perhaps at command line option.

**Comment by michaelcfanning** [comment]
Editor's meeting disposition: won't fix.
