### ISSUE TITLE
invocation object should record process outcome

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#115]
The `invocation` object should record the outcome of starting a process. The outcome of starting a process can result in the operating system failing to create the process, or in the process starting and exiting.  When a process exits, it associates a small integer (0 generally indicating success), or a signal number if its exit was caused by a signal.  Exactly one of `exitCode`, `exitSignalNumber` or `processStartFailureMessage` **SHALL** exist as a property of the invocation object. These outcomes are represented by the following properties:

`exitCode` property

An `invocation` object **SHALL** contain a property named `exitCode` that is a small integer if the process started successfully and did not exit due to a signal.

`exitSignalName` property

An `invocation` object **SHOULD** contain a property named `exitSignalName` that is a string if the process started successfully, and exited due to a signal.  Signal names are of the form "SIG" followed by uppercase letters as defined by POSIX.

`exitSignalNumber` property

An `invocation` object **SHALL** contain a property named `exitSignalNumber` that is a small integer if the process started successfully, and exited due to a signal.  The value is the number of the signal that caused the process to exit.

`processStartFailureMessage` property

An `invocation` object **SHALL** contain a property named `processStartFailureMessage` that is a string if the process failed to start.  The value is the operating system's error message for the failure.

`processSuccess` property

An `invocation` object **SHOULD** contain a property named `exitSignalName` that is a boolean if the system that started the process knows that the process did not fail to function correctly, as some programs exit with a non-0 exit status to indicate different types of success.  If this property is absent, then a default value can be created that is true if the `exitCode` property is present and has the value 0, and false otherwise.  If true, viewer should indicate that process successfully completed, and if false, viewers should indicate a failure of operation.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning 

I don't think any of these properties should be required. After all, the whole `run.invocation` property is optional. I suggest we make all of these properties **SHOULD**s.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning 
In fact, at the moment every property of the `invocation` object is marked **MAY**.
