### ISSUE TITLE
SARIF file naming convention

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#118]
The spec does not propose a naming convention for SARIF files. Should we specify `.sarif`? _Do_ file format specs typically specify a filename extension?

If we specify `.sarif` for SARIF files, shouldn’t the resource filename extension also mention SARIF? Perhaps:

- `.resources.sarif`
- `.sarif.resources`
- `.sarif-resources`
- ...?

We need to decide:

1. Whether the spec should specify a naming convention, and
2. If so, what it should be (both for SARIF files and for SARIF resource files).

**Comment by michaelcfanning** [comment]
.sarif is preferred, 
.sarif.json may be used
we should define mime types for anything that's proposed

for resources variant, this leads us to this:
.resources.sarif
.resources.sarif.json

If we move on to defining SARIF as a conceptual standard, .sarif is reserved for the JSON implementation

**Comment by lgolding** [comment]
@michaelcfanning This is a good example of an `impact-documentation-only` issue that is _not_ "`editorial`" -- the TC would need to review it.

**Comment by michaelcfanning** [comment]
Right, but this is a settled issue. So let's get it onto the agenda. should we define a tc-ready or tc-agenda label?

**Comment by lgolding** [comment]
The labels I use for that are `change-draft-available` and `change-draft-superfluous`. I will write a change draft for this, label it `change-draft-available`, and put it on the agenda. Possibly this afternoon, possibly tomorrow.

**Comment by lgolding** [comment]
### Proposal
- Root files **SHOULD** be named `.sarif`; **MAY** be named `.sarif.json`.
- Language-specific resource files **SHOULD** be named `<lang>.sarif-resources` (for example, `en-US.sarif-resources`); **MAY** be named `.sarif-resources.json`.
- "Fragments" (external files) **SHOULD** be named `<root-file-name>.<property-name>.sarif-fragment` (for example, if the root file were named `scan-results.sarif`, then an externalized `run.files` would be stored in `scan-results.files.sarif-fragment); **MAY** be named `.sarif-fragment.json`.
- Rename the `externalFile` object to `sarifFragment`.
- Rename the `externalFiles` property of the `run` object to `fragments` (not `sarifFragments`; would be redundant).

@michaelcfanning This proposal is slightly more prescriptive than we discussed on Skype. I don't see a problem with saying that the fragment's filename **SHOULD** include the property name; **SHOULD** means "do it unless you have a good reason not to", and why shouldn't we promote that kind of uniformity in the SARIF ecosystem?

**Comment by michaelcfanning** [comment]
LGTM. We should update the MIME-TYPE tracking issue to ensure that we define relevant mime types for all the things.

**Comment by lgolding** [comment]
Done. I proposed `application/sarif-fragment+json`.

**Comment by lgolding** [comment]
Merged to provisional draft.

**Comment by lgolding** [comment]
We can discard some concepts that were floated in this discussion thread:

- There is no longer such a thing as a "SARIF fragment" mentioned in the related issue #182.

- There is no longer such a thing as the "language-specific resource file" mentioned in the [comment](https://github.com/oasis-tcs/sarif-spec/issues/118#issuecomment-431516493) above. Rather, there are `translation` objects, which can reside in `sarif-external-properties` files.

The only thing that survives is the SARIF external properties file, for which we will register the media type `application/sarif-external-properties+json`.

@michaelcfanning FYI
