### ISSUE TITLE
Provide for results management 'post-back' URL

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#121]
This idea was generated in context of testing the open source Microsoft SARIF viewer. In cases where some sort of modification to the SARIF occurs as a result of human review, it'd be helpful for the SARIF to contain a URL to write back the modified SARIF.

"resultsManagmentUrl" : "https://someresultsmgmturl.contoso.com/"

**Comment by lgolding** [comment]
@michaelcfanning Tell me more about this. To post content to a service (like GitHub), you need considerably more than the URL https://github.com; you need the shape of their Web API. How useful do you see this `resultsManagementUri` property being on its own?

**Comment by michaelcfanning** [comment]
Right, so that example isn't sufficiently well-developed. A SARIF consumer will consult a result management service to synthesize SARIF. The result management system may produce a specific URI for communicating any updates to this synthesized SARIF. The consumer needs to be cognizant of the web api for that communication back.

**Comment by michaelcfanning** [comment]
We probably can hold tight on this until someone produces a practical example. We have various result mgmt. systems in flight, I'm sure something will turn up soon.

**Comment by michaelcfanning** [comment]
We agree that the SASP initiative would be the proper avenue for providing this kind of mechanism.
