### ISSUE TITLE
Formulate design goals w.r.t. compactness and readability

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#13]
Copied from https://github.com/sarif-standard/sarif-spec/issues/126, created by @lgolding:

**Comment by michaelcfanning** [comment]
@lgolding propose to close this issue as completed, de facto. our design generally favors readability by focusing on an array of results as the essential data. these results can link to several other optional tables, files, logical locations, resources. add some supplemental content describing tools/invocations and that's the format. 

i am not sure what else this issue can drive as far as improving the spec or design, we need more specifics at this point.

**Comment by lgolding** [comment]
@michaelcfanning The spec does not state the design goals that have led to these design decisions. We would keep this open, not to drive improvement to the spec or design, but to add some words that say pretty much what you said in your previous comment. I _would_ like to add those words.
