### ISSUE TITLE
Do we need to persist directory information?

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#142]
If it is prohibitively expensive to document all files in a directory that are the target of a scan, a tool might prefer to record information on a containing directory (perhaps with a hash of all its contents or perhaps with a simple timestamp).

**Comment by michaelcfanning** [comment]
Discussion:
Add directory role.
Add optional wildcard property if an item is a directory

**Comment by michaelcfanning** [comment]
Closing this. #180 covers this topic to some degree.

**Comment by lgolding** [comment]
The newly filed #294, "Add run.scope", replaces this issue with a more general approach.
