### ISSUE TITLE
Add 'returnType', 'parameter' and 'variable' to logical location kind

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#143]
From internal MS testing of in-flight standard, some tools attempt to distinguish between casing/spelling issues, etc., for parameters vs. locals, etc. This logical distinction can be important when referencing these things in a side-car suppression mechanism. As a convenience, some tools allow applying in-source suppressions at the method/function level (which can themselves refer to individual parameters in the method declaration, or locals declared within its implementation).

**Comment by michaelcfanning** [comment]
From discussion, add these.
Relax spec location to note that following syntax is preferable but may not always be possible
It is ok to populate this enum with arbitrary string when tackling domains that aren't covered.

**Comment by michaelcfanning** [comment]
If we put the hood up here, we could also add 'directory' as a role and resolve #142 
@lgolding

**Comment by lgolding** [comment]
It isn't really putting the hood up; #142 and #143 can be addressed independently, and having done #143 doesn't make it any easier to address #142.

I'm certainly willing to _try_ to pull #142 into CSD.1 (although it's lower priority than everything currently designated CSD.1 (see the [TODO query](https://github.com/oasis-tcs/sarif-spec/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3ACSD.1+-label%3Apublication-cleanup++-label%3Achange-draft-available)).

**Comment by michaelcfanning** [comment]
Got it. Agree this is lowest priority.

**Comment by lgolding** [comment]
@michaelcfanning @jkupsch FYI:

Reopened: we propose to replace this:

- `"generatedFile"`: File was generated by the build.

... with this:

- `"uncontrolledFile"`: File is not under version control.

**Comment by lgolding** [comment]
I marked this `change-draft-available` based on the one-sentence proposal in my comment above. There's no actual change draft.

**Comment by lgolding** [comment]
And shoot, I should have made this change under the aegis of #160. No matter.
