### ISSUE TITLE
Consider removing result.relatedLocations

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#144]
result.relatedLocations are much less valuable now that message text can contain embedded links. 

do we still need them?

**Comment by lgolding** [comment]
@michaelcfanning The related locations provide the _target_ for those embedded links. Consider the message
```
"Tainted data entered the system [here](2)."
```
The link target `2` refers to a `physicalLocation` object whose `id` property is `2`. That `physicalLocation` object needs to live in a `location` object somewhere; `relatedLocations` is where we put them.

See the example in the spec in §3.9.5, "Messages with embedded links".

**Comment by michaelcfanning** [comment]
@lgolding of course. Thanks. 🙂
