### ISSUE TITLE
Document how converters should provide notifications

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#15]
Copied from https://github.com/sarif-standard/sarif-spec/issues/144, created by @michaelcfanning:

Should we provide a way for a converter to communicate that something strange happened during conversion? What about tools that process existing log files and add some notes/observations? Not a breaking change to extend the enum.

**Comment by lgolding** [comment]
Comment from @lgolding:

These belong in `toolNotifications`. Converters can specify a distinguished `notification.id`. It could even be something like `PREfastConverter.1`, `.2`, ...

The message should also make it clear who produced the notification.

**Comment by lgolding** [comment]
Comment from @lgolding:

@michaelcfanning Do you agree that these should be `toolNotifications` with a distinguished `id`, or do you have another suggestion?

**Comment by lgolding** [comment]
Notes from TC con call 2017/09/27:

- Need to mark a file as having been the result of a conversion.
- Need to distinguish notifications produced by the source tool from those produced by the converter.

JimKupsch suggests "provenance" -- which native tool output file was converted; which converter version was used.

**Comment by DerSaidin** [comment]
A tool could merge multiple input reports. A linear chain may be insufficient.

I feel this may be growing to be more complexity than necessary.

**Comment by michaelcfanning** [comment]
another possibility is adding converter specific notifications property

**Comment by lgolding** [comment]
@michaelcfanning I like the idea of a "converter specific notifications property". Now that we have a `conversion` object, that's the natural place for it `conversion.notifications`. I'll write the change draft that way.
