### ISSUE TITLE
DRY out definitions of property bags in the schema

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#151]
In the schema, define a `propertyBag` type and have each property-bag-valued property refer to it.

**Comment by lgolding** [comment]
@michaelcfanning I'm working on this now. I'll do it first in SARIF SDK, and if all the tests pass, I'll port the change to the OASIS copy of the schema.

**Comment by michaelcfanning** [comment]
@lgolding I resolved this on 11/1 as above. Closing this issue.
