### ISSUE TITLE
Clarify treatment of backslashes and square brackets with respect to embedded links

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#153]
Section 3.9.5, “Messages with embedded links”, describes a custom syntax for embedded links, and it says that square brackets that are not part of embedded links should be escaped. But it’s not clear whether a backslashed "]" should be considered part of the link text, interpreted as a literal "]".

This is not only insufficiently precise; it also doesn't match GitHub Flavored Markdown's treatment of brackets and backslashes in links. The behavior we want is for this input:

![sampleinput](https://user-images.githubusercontent.com/11762653/39265498-439a777e-487c-11e8-97e5-6ef0903a6275.png)

to produce this output:

![expectedoutput](https://user-images.githubusercontent.com/11762653/39265514-4ac1cda4-487c-11e8-9fdd-8e706c4add59.png)

Unfortunately the spec can't just say "Match GFM's behavior for hyperlinks" because GFM's link syntax includes features we don't want, like hover text. So I'll have to write words to explain exactly what we want.

**Comment by michaelcfanning** [comment]
Suggest document a regular expression that handles identifyinkg links. Chris M. is developing one.
