### ISSUE TITLE
Improve example of messages with placeholders and consider putting it in a more prominent location

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#156]
I see one example of a message with placeholders and it wasn't where I expected to find it (either in the description of message.arguments or in the section titled 'messages with placeholders'

Also the example that does exist should use apostrophes to help indicated the replacement value. Will help the example pop more. Also suggest using a variable name of greater length.

See example below for my suggested improvements, changed name of var 'n' to 'pBuffer' and added apostrophes in text and format string

  "results": [                                   # See §3.11.15.
    {                                            # A result object (§3.19).
      "ruleId": "CA2101",                        # See §3.19.4.
      "message": {                               # See §3.19.7.
        "text": "Variable 'pBuffer' is uninitialized.",  # See §3.9.7.
        "arguments": [ "pBuffer" ]                     # See §3.9.11.
      },
      "ruleMessageId": "default"                 # See §3.19.8.
    }
  ],

  "resources": {                                 # See §3.11.16.
    "rules": {                                   # See §3.35.3
      "CA2010": {                                # A rule object (§3.36).
        "messageStrings": {                      # See §3.30.7.
          "default": "Variable '{0}' is uninitialized."
        }
      }

**Comment by lgolding** [comment]
@michaelcfanning 
1. I left one copy of the example in place, in §3.19.2, "result object: Constraints", because it illustrates the constraint. But I made your suggested improvements.
2. I added a simplified version of the example to §3.9.4, "Messages with placeholders", again with your suggested improvements.

Change draft to follow shortly.

**Comment by lgolding** [comment]
@michaelcfanning I made the changes in the provisional draft. To see the change bars, see  [Documents/ChangeDrafts/Accepted/sarif-v2.0-editorial-156-improve-placeholder-example.docx](https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/ChangeDrafts/Accepted/sarif-v2.0-editorial-156-improve-placeholder-example.docx).
