### ISSUE TITLE
Should result have an exception property?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#16]
Copied from https://github.com/sarif-standard/sarif-spec/issues/171, created by @lgolding:

... to handle the case where a dynamic analysis tool encounters an exception in the case of executing the analysis targert.

@michaelcfanning FYI

**Comment by lgolding** [comment]
We don't know of a tool that would make use of this today.

**Comment by michaelcfanning** [comment]
Closing this issue as 'deferred'. We will reopen issues tagged 'future' later.
