### ISSUE TITLE
Expand code flows to represent dynamic execution events

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#161]
I had a lengthy talk with a dynamic analysis results producer yesterday who noted that SARIF is very thin as far as expressing stack-based information. He noted that his tool collects a series of execution events, each of which has an associated stack. This chain of events is what's examined to produce a scan result.

One of the events needs an identifier, some user-facing text, a stack and a bundle of state. Hm. Sounds a lot like a code flow, except that we have a stack (collected at runtime) rather than a speculative physical location provided by a static checker.

We have two directions we could go: 1) create dynamicEventFlows or some equivalent, modeled like code flows (they would be an array of arrays of dynamicEventFlows). Each dynamic event contains an identifier, message, stack, state and a thread id (or the thread id is associated with an array, 2) just add stacks and a 'kind' designator to code flows.

Note that doing either option will allow us to drop stacks from the result object. i.e., you could simply use code flows for this (and not populate any other information).

This suggestion also resolves a long-standing thought we've had around how to model exceptions. Now you populate code flow with a single item, add the exception stack, note the kind as 'unhandledException' and that's it.

**Comment by michaelcfanning** [comment]
@lgolding

**Comment by lgolding** [comment]
@michaelcfanning 

Proposal: Just add `codeFlowLocation.stack`. And yes, I suppose remove `result.stacks`.

Why do we need `codeFlow.kind` to say it's a "dynamic event flow"? The presence of `codeFlowLocation.stack` tells you what you need. Are youe concerned about having to paw through the whole `codeFlow` to decide whether there's any stack information?

Adding `codeFlow.kind = "unhandledException"` gets us back in the business we just got out of: assigning semantics (as opposed to display behavior) to code flows. It might be justified here. An alternative is to use a message, as we did when we got rid of `annotatedCodeLocation.kind`.

The whole thing might look like this:

```
{                                          # A run object.
  results: [
    {                                      # A result object.
      "codeFlows": [
        {                                  # A codeFlow object.
          "threadFlows": [
            {                              # A threadFlow object.
              "locations": [
                {                          # A codeFlowLocation object.
                  "location": {            # Existing: codeFlowLocation.location: a location object.
                     "physicalLocation": {
                       ...
                      },

                      "fullyQualifiedLogicalName": "A.B"

                      "message": {
                        "text": "Unhandled exception thrown: NullReferenceException."
                      }
                  },

                  "stack": {               # New: codeFlowLocation.stack: a stack object.
                  },

                  "state": {               # Existing: codeFlowLocation.state: a JSON object
                    ...                    # (string-to-string dictionary).
                  }
                }
              ],
            }
          ]
        }
      }
    }
  ]
}
```

**Comment by michaelcfanning** [comment]
adding 'kind' does not get us back into assigning any semantics with this suggestion. instead, 'kind' is an open-ended identifier. we would provide no enum values here, it's just a string. one possible use of a 'kind' would be to retrieve a specialized set of supporting properties from the properties bag. we need a property for this (instead of storing the 'kind' itself as a property) because, by design, there shouldn't be a deterministic association with a property key and the value that is retrieved by it. um, exception for using v1/ and v2/ prefixes. :)

another issue that came up is how to express parameterization that led to a result. for a web result, for example, you might want the request headers, because these impact the code that was generated. i think for this case, we'd recommend that producers use the 'state' object to hold this data. 

alternately, we could consult with the tools providers we are working with to propose a reasonable set of properties to capture this. I'll have more info on this soon, for now, let's assume 'state' can capture these things.

**Comment by lgolding** [comment]
@michaelcfanning I changed the issue title since we agreed that we would in fact expand code flows to represent this case.

Also note: I don't think the applicability is limited to dynamic execution. Even a static analysis tool that _simulates_ program execution will know the call stack at each code flow location it chooses to emit.

**Comment by lgolding** [comment]
@michaelcfanning Incidentally, I'm not entirely comfortable modeling exceptions as you suggest (a code flow with one location, which has a call stack, and `kind` is `"unhandledException"`). The problem is undefined semantics. A consumer isn't allowed to interpret the string `"unhandledException"` except with respect to a particular tool. If we standardize the meaning of  `"unhandledException"`, we're back in the semantics game.
