### ISSUE TITLE
Add result.workItemLocation

### ISSUE THREAD

**Issue by Evmaus-MS** [oasis-tcs/sarif-spec#163]
Many result management systems are likely to persist static analysis results in the form of work items for developers to triage/work on/etc.--these could be TFS work items, or Jira tickets, or GitHub issues, or etc.

It would be helpful if a results management system could persist the location that a particular result is tracked back to the SARIF file/SARIF result in some way--one observation we had is that almost all of those systems provide some way to link to a work item, so persisting it as a URI may make the most sense.

**Comment by lgolding** [comment]
@Evmaus-MS @michaelcfanning I'd like to name this `result.workItemLocation` (not ...Uri) for consistency with `help.location` and our use of "location" to describe resources specified by `fileLocation` objects.
