### ISSUE TITLE
Provide a URI that can be used to retrieve rule metadata

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#17]
Copied from https://github.com/sarif-standard/sarif-spec/issues/175, created by @michaelcfanning:

Remember @rtaket's fine suggestion around providing a URI member for rule metadata. In the event this item is populated, the uri represents an endpoint that can be used to retrieve the rule SARIF. Not a blocker for v1.

https://github.com/Microsoft/sarif-sdk/issues/124

**Comment by lgolding** [comment]
Comment from @michaelcfanning:

"It would be nice if ruleDescriptor had a URI property which specifies an endpoint where the rule definition can be retrieved from. 

In our meeting, we had a deeper conversation about how this property could be used. In general, we thought the URI (and it's contents) can be thought of as a contract for a rule. For example, if the URL was http://sarif.microsoft.com/codedefects/unusedusingstatements, this indicates that the rule professes to validate that there are no unused using statements. The URI describes the defect and the rule verifies the defect does not exist. The relationship between URI(defects)->rules is not 1-to-1. Many rules may profess to verify a defect. This also implies that many tools may profess to verify a defect. "

**Comment by michaelcfanning** [comment]
Note that we could also add a reserved 'uri' property to the 'rules' object that would allow retrieval of all rules metadata. Note that some rules metadata refers to enabled/disabled state (i.e., contains run-specific information, not strictly static rule metadata).

**Comment by lgolding** [comment]
This is covered by #84.
