### ISSUE TITLE
Inconsistent definition of `endColumn`.

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#171]
_3.22.7 endColumn property_ states:
> When a region object represents a text region, it MAY contain a property named endColumn, which SHALL have an integer value equal to the column number of the last character in the region.

This specifies that the `endColumn` is "inclusive". However, in _3.22.2 Text regions_, there are multiple references that suggest the `endColumn` should be "exclusive", i.e. it should point to the next column _after_ the region.

Two examples from 3.22.2:
> If endLine is the same as startLine and endColumn is the same as startColumn, the length of the region SHALL be taken to be 0.

This only makes sense if the `endColumn` is exclusive - if it's inclusive, you cannot represent regions of one character.

> EXAMPLE 1: Suppose a text file contains the following line, on line 5:
>
> abcde
>
> Then the region with startLine = 5, startColumn = 3, endLine = 5, and endColumn = 6 represent the three characters cde. This is the case whether or not the line ends with a newline sequence.

`endColumn` is clearly specified as the column _after_ the region here.

I am assuming that the definition in `endColumn` is wrong - it seems to be more consistent, and make more sense for it to be exclusive.

**Comment by michaelcfanning** [comment]
yes, endColumn should consistently be excluded. this will be addressed in #93

**Comment by lgolding** [comment]
This is covered by the change draft for #93.
