### ISSUE TITLE
Result mgmt. systems merge SARIF files. Can we provide a count of occurrences?

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#174]
When merging SARIF files back into a single SARIF file, the merge will potentially 'deduplicate' results. For merged logically unique results, can we provide a 'count of occurrences property'

**Comment by michaelcfanning** [comment]
@lgolding, need to raise priority on this. we have an early adopter internally that would like a first class SARIF property for this.

conceptually, we can think of this as a mechanism that simply counts occurrences for whatever location is provided. this would allow tools the provide simulated execution to provide a count of occurrences from that presumed execution. in another case, a tool that only provides a line location might be able to further qualify this information by noting that there are 'n' occurrences of the issue on the single line.

**Comment by lgolding** [comment]
@michaelcfanning Change draft available.

**Comment by michaelcfanning** [comment]
Looks good. is 'result.count' sufficient as opposed to 'result.occurrenceCount'?

**Comment by lgolding** [comment]
@michaelcfanning Reasonable people could disagree. In my experience whenever I see a name like "count" I immediately ask "Count of what?".
