### ISSUE TITLE
Spec unclear on whether non-embedded Markdown links are permitted

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#177]
The spec says:
> Square brackets (("[" and "]") in both plain text messages and rich text messages SHALL be escaped with a backslash ("\") to prevent them from being interpreted as embedded links.

If I read this sentence strictly, it seems to imply that any non-quoted `[` and `]` will be read as embedded links - i.e. regular Markdown links are not permitted. I assume that's not the intention, and that other forms of links (for example, to external resources) are permitted.

**Comment by lgolding** [comment]
@lukecartey The sentence you quote no longer appears in the provisional draft. It would indeed have led to the confusion you described. #153 took care of your concern.

§3.9.3.1 (message objects/Rich text messages/General) says:

> ... direct producers SHALL express rich text messages in GitHub-Flavored Markdown [GFM]. Since GFM is a superset of CommonMark [CMARK], **any CommonMark Markdown syntax is acceptable** [emphasis added].

This implies that normal links are acceptable.

Then in §3.9.5 (message objects/Messages with embedded links), we have:

> Within a rich text message (§3.9.3), an embedded link **SHALL** conform to the syntax of a GitHub Flavored Markdown link (see [GFM], §6.6, “Links”), with the restriction that the “link destination” **SHALL** be a non-negative integer (whose interpretation is defined below).

So it doesn't say "only embedded links are allowed." It says "you distinguish an embedded link from a regular link by looking at the link target."

There's also a note in §3.9.5 that says:

> NOTE: The GFM link syntax is very flexible. Since a SARIF viewer that renders rich text messages will presumably rely on a full-featured GFM processor, there is no need to restrict the embedded link syntax in SARIF rich text messages.

**Comment by lukecartey** [comment]
Great, thanks! This fixes my concern.

**Comment by lgolding** [comment]
@lukecartey @michaelcfanning Thanks Luke. Now, in email, Michael raised a distinct concern, about whether integer link destinations were a good idea after all -- at least in Markdown messages, although I argued that plain text messages are really no different in this regard -- but that discussion will become a different issue, if we decide to address it.
