### ISSUE TITLE
Support a character or column interpretation property

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#178]
In the latest regions change draft, the spec talks about `columnStart`, `columnEnd`, `charOffset` and `charLength` being determined based on the number of characters. In particular, the spec states:

> A text file’s character encoding determines the number of bytes that represent each character

For unicode based encodings, I'm taking this to mean that a character is equivalent to a unicode code point.

The problem is that this not the way many tools produce or interpret locations, and converting to/from different character interpretations can be expensive or difficult.

The problem is that many programming languages (Java, C#, JavaScript etc.) internally represent represent strings as UTF-16, and the "native" length and indexing operations work on UTF-16 _code units_, not unicode _code points_. In particular, when loading a file into a string in memory it will be converted to UTF-16, **regardless of the original encoding**. Then operations are performed based on the number of 16-bit elements in that string - surrogate pairs are treated as two columns in this mode.

Whilst these languages do also support working on code points, perceived performance penalties means that most tools built with these languages use the code unit approach to determine and interpret column locations.

Examples here include "producers" such as Roslyn, the Java (OpenJDK/Oracle) compiler and JavaScript tools such as jshint, and "consumers" such as editors like Eclipse, Visual Studio and Visual Studio Code.

My concern here is that by dictating that the locations use "characters" (e.g. unicode code points), we're creating significant work for _both_ producers and consumers. In particular, if you have a location in UTF-16 code units, then converting it to a location in unicode code points requires re-processing the whole file up to that point, and recalculating the offsets/lines/columns. In some conveter scenarios, the source code files may not be present.

I therefore propose we provide a character or column type property that, at a minimum, supports: UTF-16 code units and unicode code points. This way, if both the producer and consumer agree on the column type, no conversion work is required. If they disagree, then the consumer will need to convert or adapt the locations, but should have the source files on hand to do that.

**Comment by lukecartey** [comment]
I've uploaded a concrete example here:
[unicodetest.zip](https://github.com/oasis-tcs/sarif-spec/files/2035746/unicodetest.zip)
This contains a C# source code file with a unicode character from the supplementary plane (i.e. requires a surrogate pair to represent in UTF-16):
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UnicodeTest
{
    class Program
    {
        static void Main(string[] args)
        {
            /* 𐐷 */ int id = 0;
            /* a */ int id2 = 0;
        }
    }
}
```
And a SARIF file including locations reported by Roslyn:
```
{
  "$schema": "http://json.schemastore.org/sarif-1.0.0",
  "version": "1.0.0",
  "runs": [
    {
      "tool": {
        "name": "Semmle",
        "version": "1.16.0"
      },
      "results": [
        {
          "message": "Local variable",
          "locations": [
            {
              "resultFile": {
                "uri": "Program.cs",
                "uriBaseId": "%SRCROOT%",
                "region": {
                  "startLine": 13,
                  "startColumn": 22,
                  "endColumn": 32
                }
              }
            }
          ]
        },
        {
          "message": "Local variable",
          "locations": [
            {
              "resultFile": {
                "uri": "Program.cs",
                "uriBaseId": "%SRCROOT%",
                "region": {
                  "startLine": 14,
                  "startColumn": 21,
                  "endColumn": 32
                }
              }
            }
          ]
        }
      ],
      "rules": { }
    }
  ]
}
```
Note that the startColumn of the first result is 22, but the second column is 21. This is because Roslyn is treating 𐐷 as two columns (because it requires a surrogate pair to represent in UTF-16).

Also note that the `Program.cs` file is not UTF-16 encoded - it's actually UTF-8 encoded (with BOM). The locations Roslyn produced are based on the _internal_, in memory representation of the file, and are not in any way related to the encoding of the original file.

If you open the SARIF file up in the Visual Studio SARIF viewer, and map to the source file, the correct visual locations will be chosen for both results. This is because Visual Studio is loading the the UTF-8 encoded file, then representing it in memory as UTF-16, then interpreting the columns it is provided 

Concretely, the problem here is that if we enforce columns as unicode code points or characters, we would need to:

 (1) Change any producers using Roslyn column locations to produce code point relative locations, by reprocessing every file after Roslyn processes it.
 (2) Change the SARIF viewer to convert those code points _back_ into UTF-16 code units.

**Comment by lgolding** [comment]
@michaelcfanning @kupsch @lukecartey 

I think this is a reasonable concern. I know that when the three of us spoke, Michael's argument (which was essentially that if editors do that, then they're buggy) carried the day, but as a practical matter, I don't see how we can live with this (especially as Luke points out that producers like Roslyn make the same "mistake").

What do you think of Luke's proposal to introduce a property like `columnUnits` with values like `"unicodeCodePoints"` and `"unicodeCodeUnits"`. (Then we can argue over the default value 😉).

**Comment by michaelcfanning** [comment]
@lgolding read #93 carefully. Jim uses the term 'code points' in the beginning where he appears to have intended 'code units'. for example, he describes this thing as mirroring a character of the encoding (like a code unit). he notes they can be combined together to form glyphs (like code units).

**Comment by lgolding** [comment]
@michaelcfanning @lukecartey @kupsch

I don't think that's correct. Jim used the term "code point" as Unicode defines it, to mean an abstract character. Certain abstract characters (code points), like the "𐐷" in Luke's example, require more than one UTF-16 code unit to represent them, but Jim is arguing for treating every abstract character (code point) as one column.

The issue of combining characters is completely orthogonal. Unicode can represent certain _glyphs_ in more than one way as sequence of _abstract characters_ (code points). So for example, Unicode can represent the glyph "é" either as a single abstract character "Latin Small Letter E with acute" (U+00E9), or as a sequence of two abstract characters "Latin Small Letter E" (U+0065), "Combining Acute Accent" (E+0301). Jim proposes to treat the first of those as one column, and the second as two. That's why he writes:

> Note: due to combining characters and other formatting characters, the number of glyphs displayed may not match the number of character code points.

To reiterate: the issue of how many 16-bit "code units" represent a single abstract character (code point) is completely separate from the question of how many abstract characters (code points) represent a glyph. Jim proposed treating each abstract character (code point) as one column.

I'm not expressing an opinion on whether Jim's position (one column per code point) is better or worse than Michael's/Luke's position (one column per 16-bit code unit). But those _are_ the two positions in play, and the _are_ different.

**Comment by michaelcfanning** [comment]
I see. Please do something for me. Copy the commented code below into a C# file in VS. Position the cursor before each character within the comment and observe the status bar at the bottom right in VS that reports out on both current column and char index.

Note that both characters increment that char count by two. Luke's example only increments the column count by 1 on my machine, while the second character increments the column count by 2. Can we account for this behavior? Is it consistent with Luke's recommendation for SARIF?

/* 𐐷  𪘁 */

My observation seems inconsisten with Luke's observation on Roslyn:

"This is because Roslyn is treating 𐐷 as two columns (because it requires a surrogate pair to represent in UTF-16)."

Have I identified a discrepancy between the VS IDE and Roslyn behavior?

**Comment by lgolding** [comment]
I confirm your observation.

VS treats 𐐷 as two characters occupying one column (it increments Col by 1 and Ch by 2 when I step over it), but it treats  𪘁 as two characters occupying two columns (it increments Col by 2 and Ch by 2 when I step over it).

I suspect that VS displays the count of abstract characters in "Col" (consistent with Jim's proposal), and it displays the count of 16-bit code units in "Ch".

I suspect that the glyph 𐐷 is is a single abstract character (one column) represented by a surrogate pair (two characters), whereas the glyph 𪘁 is a combining sequence of two abstract characters (two columns), each of which resides in the Basic Multilingual Plane and hence consists of a single 16-bit code unit (two characters). This is like the case "Latin Small Letter E" (U+0065), "Combining Acute Accent" (E+0301)". This is exactly the situation Jim anticipates in his note that I quoted above.

You could confirm that speculation by writing a program and examining the sequence of 16-bit code units in the string "𐐷𪘁".

**Comment by lgolding** [comment]
So to answer your question, no, it's not a discrepancy. The "Ch" that VS reports matches Roslyn's 16-bit code unit-based counting.

**Comment by lgolding** [comment]
And to continue my stream of consciousness: The inconsistency is that Roslyn calls a "column" what VS calls a "Ch(aracter)", whereas the thing VS calls a "Col(umn)" does not match what Roslyn reports. The inconsistency is in the naming.

**Comment by michaelcfanning** [comment]
Ouch. So Roslyn's 'column' counting mechanism matches to VS 'CH' counting mechanism?

**Comment by lgolding** [comment]
Yes :smile:

**Comment by lgolding** [comment]
Unfortunately my speculation seems to be wrong:
```
using System;

namespace TestCharacterCounts
{
    class Program
    {
        static void Main(string[] args)
        {
            const string TestString = "𐐷𪘁";
            Console.WriteLine("Length: " + TestString.Length);
            for (int i = 0; i < TestString.Length; ++i)
            {
                Console.WriteLine("[{0}]: U+{1:X4}", i, (int)TestString[i]);
            }
        }
    }
}

// Output:
Length: 4
[0]: U+D801
[1]: U+DC37
[2]: U+D869
[3]: U+DE01
```
... which is two surrogate pairs, each consisting of a "high surrogate" from the range (U+D800 &ndash; U+DBFF) followed by a "low surrogate" from the range (U+DC00 &ndash; U+DFFF).

So I can't account for VS's behavior.

**Comment by lukecartey** [comment]
The Visual Studio "discrepancy" you are seeing is because the `Col` field in Visual Studio is not reporting Unicode code points - it's instead based on the Unicode "width" of each code point.

In particular, 𪘁 is handled differently because it is an East Asian character. East Asian text has a concept of "narrow" and "wide" characters. Typically, the narrow characters would take up half the width of the wide characters. In order to represent this, Unicode classifies code points according to width. 𪘁 is a "wide" character, which VS chooses to interpret as having two columns (vs. one column for narrow characters). 𐐷 is a "neutral" character (i.e. non east asian) according to Unicode, but that is typically treated as a narrow character.

More details here:
http://www.unicode.org/reports/tr11/
And a data table of widths is published here:
http://www.unicode.org/Public/9.0.0/ucd/EastAsianWidth.txt

Note: control characters can also have multiple columns per code point. An example here is the tab character - one Unicode code point, one UTF-16 code unit, but it will depend on editor configuration as to how many columns it represents.

Given all this, I don't think it would be useful for us to try and match the VS interpretation of "columns".

> The inconsistency is that Roslyn calls a "column" what VS calls a "Ch(aracter)", whereas the thing VS calls a "Col(umn)" does not match what Roslyn reports. The inconsistency is in the naming.

I believe Larry was correct with this statement.

**Comment by michaelcfanning** [comment]
I agree with this and that also raises the question of whether column is the appropriate term to use in the format. It is clear that the information that is persisted to SARIF should be data that isn't subject to, for example, the configuration of the editor (I'd forgotten about the tabs -> columns issue).

The most reliable mechanisms are either to specify Unicode code units or code points. I'd propose that code units are the default and that we provide a property that allows to make this explicitly code unit or code points. I'd also suggest that we consider renaming startColumn/endColumn (despite the pervasive use of these terms in existing tool log file output).

**Comment by lgolding** [comment]
I agree that “column” isn’t accurate. “character”  is also wrong, both because of surrogate pairs and because of Unicode normalization issues with accented characters.

There is no English word for the concept we want, which is “the unit in which a language or tool measures string lengths”. We could coin “stringLengthUnit” or “stringUnit” but I don’t think it’s necessary.

IMO, we should continue to use column. As Michael said, many tools use this term in their output, even though it’s not strictly correct.
