### ISSUE TITLE
Define tool component object to represent tool driver and its extensions/plugins

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#179]
In order to effectively compare two equivalent tool runs expressed as SARIF, it is useful to verify whether the log files were produced by tool configuration with equivalent functional behaviors. 

The tool version provides some help here. The tool invocation data also provides some assistance, in cases where things like the command-line arguments are exactly equivalent. 

Tools can be parameterized by things referred to on the command-line (such as scripts that drive analysis, or plug-ins that are delay-loaded). These things can be versioned out-of-sync with the tool. 

Additionally, some tools discover plug-ins at runtime, from well-known locations (that aren't explicit on a command-line).

It is difficult or impossible to specify SARIF that can accommodate the range of tool behaviors. But have we done enough on the problem of handling rule scripts/plug-ins versioning that is typical of tools such as Semmle? Fortify also has flexible rules customization/authoring. et al.

**Comment by lgolding** [comment]
@michaelcfanning:

Proposal (copied from #207):
Define a `plugIn` object with properties `fileLocation` (of type `fileLocation`) and `version` (of type `string`). Give `tool` a new property `plugIns` of type "array of `plugIn`".

Probably the `plugIn` object would have the same set of versioning properties that `tool` does: `version`, `semanticVersion`, and `fileVersion` (but not `sarifLoggerVersion`).

**Comment by michaelcfanning** [comment]
New proposal: provide a tool property that represents a set of file indices to plug-ins. Add a version property to the file object. Now, a tool can reference all its plug-ins. The file information can contain hash and version details to idenify it. Add an optional property to the rule metadata that refers to its container plug-in (by file index). Consider whether we require a new file 'role' to document this case.

**Comment by michaelcfanning** [comment]
Remove tool.sarifLoggerVersion
Tool 
  language
  driver
  extensions[]

latter two are now toolComponent objects

**Comment by michaelcfanning** [comment]
@lgolding, one thing to keep in mind here is that we've moved rules metadata to the tool object. if this data is now part of tool component, then a result ruleIndex needs to know what component it is associated with. this implies a toolComponentIndex on each result (that can't point away from the driver into some specific plug-in or component). The absence of this property would indicate that the driver component rulesMetadata s/be examined to retrieve rule data.

**Comment by lgolding** [comment]
@michaelcfanning I agree with your idea for `toolComponentIndex`.

**Comment by michaelcfanning** [comment]
Schema changes:

Tool.language retained.
Tool.sarifLoggerVersion deleted
Remainder of tool properties bundled into a toolComponent object.
toolComponent.fileIndex added to that type.
tool.driver is a toolComponent instance and is a required property
tool.extensions is an array of tool components that extend the default tool
result.extensionIndex can be used to associate a result with an extension
'toolComponent' added as a new file role

**Comment by michaelcfanning** [comment]
Checked into SARIF SDK schema.

**Comment by michaelcfanning** [comment]
Please note update to this issue, result.extensionIndex should be named result.ruleExtensionIndex (to provide parallelization with result.ruleIndex...)

**Comment by michaelcfanning** [comment]
**EBALLOT PROPOSAL**: define a mechanism to allow a tool to explicitly detail any plug-ins or extensions that were in play during the analysis run (and which potentially contribute to changes in analysis behavior).

**API IMPACT**
'tool.sarifLoggerVersion' property deleted (as not helpful to date)
New 'toolComponent' defined to represent a tool driver and its extensions.
'tool.driver' 'toolComponent' added to represent the driver and is required
'tool.extensions', an array of 'toolComponent' instances added to represent all extensions
'toolComponent.artifactIndex' added to that type to locate the component in the artifacts table
'result.rulePointer' can be used to associate a result with an extension (see #324 for more)
'toolComponent' added as a new file role
'conversion.tool' remains a 'tool' instance and therefore has driver + extensions tool components.

**Comment by lgolding** [comment]
#### E-BALLOT <span>#</span>2 PROPOSAL

We decompose a `tool` object into a number of `toolComponents`: a "driver" (the component that contains the tool's primary executable) and zero or more "extensions" (components that affect the tool's behavior, such as plugins and configuration files).

This ballot proposal incorporates the later changes introduced by #336 ("Changes to toolComponent properties").

#### SCHEMA CHANGES

- In the `tool` object
    - Remove the never-used `sarifLoggerVersion` property.
    - Add a property `driver` of type `toolComponent`, required.
    - Add a property `extensions` of type `toolComponent[]`, optional, minItems: 0, default: empty array

**Comment by lgolding** [comment]
Neglected to close this after e-ballot-2.
