### ISSUE TITLE
should we require 'id' on a 'rule' instance when the 'rules' key matches it?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#18]
Copied from https://github.com/sarif-standard/sarif-spec/issues/210, created by @michaelcfanning:

We don't require this recapitulated information for the 'uri' in a file object where the key matches...

**Comment by lgolding** [comment]
Comment from @lgolding:

@michaelcfanning  I think we discussed this and I advocated for keeping it for self-contained readability of the rule instance, and to simplify the job of SARIF processors. Did we close on this?

**Comment by lgolding** [comment]
Comment from @lgolding:

In any case I'll argue now that the v1.0.0 ship has sailed, but we can consider for Future.

**Comment by lgolding** [comment]
Comment from @michaelcfanning:

That's not a very persuasive argument, since removing the restriction to require "id" isn't a breaking change. Looking at the rule metadata, I don't think the 'required' value is correct. you and I had discussed reviewing the spec comprehensively for this. I'd prefer that we do that as a pass, this is likely to be more productive than examining whatever specific instances of this problem we have in the open issues list. I can appreciate here that you're simply trying to close items that need closing.

**Comment by lgolding** [comment]
Comment from @lgolding:

It is not a breaking change for producers (because rules with 'id' present continue to be valid), but it is breaking for consumers (who at present are entitled to assume that if the file validates, then rule.id is non-null).

**Comment by lgolding** [comment]
Comment from @michaelcfanning:

we only have supported producers. they are Roslyn and the C++ compiler. we do not have a shipped consumer.

**Comment by lgolding** [comment]
Comment from @lgolding:

That is likely true today. At some point we have to take "impact-breaks-consumers" seriously, though, because we ship an SDK, and at some point we have to assume that someone's using it to write a consumer.

**Comment by lgolding** [comment]
Comment from @lgolding:

(so we have to decide together, when is that point?)

**Comment by lgolding** [comment]
Comment from @lgolding:

Actually I'll go a little farther: The spec is public, so at some point we have to assume that others have written their own access code (maybe not a full-blown SDK) for other, non-.NET platforms, and they have to be entitled to rely on the published spec and schema. Maybe that day is not today.

**Comment by lgolding** [comment]
Comment from @lgolding:

In any case, even if the "breaking change" argument is not persuasive, the "self-contained readability" and "simplicity of consumption" arguments might be. I just don't feel a strong need to do this.

**Comment by michaelcfanning** [comment]
Closing per historical conversation. If anyone else reactivates or issue is raised independently, we will take another look.
