### ISSUE TITLE
Consider providing a mechanism to escape forward slashes in hierarchical strings

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#183]

**Comment by lgolding** [comment]
Copied from #264, which I've just closed with `resolved-duplicate`:

> Hierarchical strings consist of forward-slash-separated components, so a component can't contain a slash. There are two options:
> 
> 1. Explicitly prohibit slashes in components.
> 2. Define an escaping mechanism. For example, JSON Pointer (RFC 6901) is made of just such forward-slash-separated strings. It uses `~1` for literal slash, and (since `~` is now special) `~0` for a literal tilde.
>
> Which shall it be?

**Comment by lgolding** [comment]
Per TC <span>#</span>25, we will prohibit slashes in components, and we will make the change directly in the provisional draft.

**Comment by lgolding** [comment]
Fixed. The grammar already prohibited the slashes. I just added a note to call attention to that fact.
