### ISSUE TITLE
Specify a default value for columnKind

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#188]
Today, there is no default if it's not present.

**Comment by michaelcfanning** [comment]
The default value s/be unicodeCodePoints

**Comment by michaelcfanning** [comment]
@lgolding, neglected to mark this triage-approved. would be great to get a change draft out on this at your convenience

**Comment by lgolding** [comment]
I marked it `to-be-written` and I'll do it today.
