### ISSUE TITLE
Distinguish "tool-specific" from "generic" properties

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#190]
Some properties, like `result.ruleId`, can only be filled by the analysis tool (let's call them "tool-specific properties"). Others, like `run.baselineInstanceGuid` and `result.fingerprints`, can be filled by other components of the SARIF ecosystem, such as the result managements system (let's call them "generic properties").

Today, the spec says that the analysis tool "**SHOULD NOT**" fill `result.fingerprints`, which is too strong a statement. We need to explain the concept of tool-specific _vs._ generic properties, and _encourage_ tool vendors to fill only the tool-specific properties -- without making a normative statement. Perhaps we can explain this in a non-normative Appendix.

The whole idea is to make it as easy as possible for tools to emit valid SARIF, by minimizing the amount of work they _have_ to do.

**Comment by lgolding** [comment]
@michaelcfanning My care factor for this one has disappeared. Ok with you to close it?

**Comment by michaelcfanning** [comment]
Please do.

**Comment by michaelcfanning** [comment]
Please do.
