### ISSUE TITLE
run.columnKind is only for text-processing tools

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#191]
The TC approved #178, which defined the required property `run.columnKind` with values `"utf16CodeUnits"` and `"unicodeCodePoints"`. But neither of these values is sensible for a tool that does not process text files.

To fix this problem, we will make the property optional. This approach has the following features:

- Tools that emit `columnKind` are better off than they were before, because consumers now know how to interpret the tool’s column counts.
- Tools that do _not_ emit `columnKind` are no worse off than they were before. Consumers had to guess before, and they still have to guess.
- We do not specify a default (a very contentious issue which we can sidestep).
- We do not have to specify a `"none"` value for use by non-text-processing tools. Nowhere else in SARIF does an enumerated property have a `"none"` or `"unknown"` value.

**Comment by lgolding** [comment]
We can do better: make the property required for tools that process text files, and forbidden for tools that don't.

The property has to be optional in the schema, but the spec can say the right thing.

@michaelcfanning

**Comment by michaelcfanning** [comment]
Ah ha. Nice.

**Comment by lgolding** [comment]
Forgot to close this.
