### ISSUE TITLE
Did we break code flows in v2?

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#194]
We should be consulting with GrammaTech on this. We specifically removed a code flow 'kind' and a 'target' property. These two v1 values were useful to GrammaTech previously in order to provide icons and special highlighting/other viewer functionality.

We discussed this yet? The issue is that we have an open-ended 'Kind' string which is intended to be user-facing. Some 'kinds' may arguably be inferable today (such as a call being implied by a change in nesting level) but not necessarily.

I agree with this general concern. I didn't like the proliferation of code flow 'kinds' previously and all the semantics we had to document around matching pairs of them, specifying target contents. But I think it's reasonable to enable viewers to provide standard icons/rendering for certain standard things (like a branch).

**Comment by michaelcfanning** [comment]
@lgolding this issue is the most urgent in my mind for CSD2. code/thread flows is the most critical part of the format for sophisticated checkers. this scenario needs to be handled very well, otherwise, the analysis that's leading the industry will not derive value from the format.

**Comment by lgolding** [comment]
@michaelcfanning Is there anything left to do here? We have validated that we can display v2 codeFlows in the viewer, and AFAIK the only issue that's been raised is that we need to restore `threadFlowLocation.kind` (in some manner -- we're still discussing that). That is covered in #202, "Restore threadFlowLocation.kind".

Can we close this?

**Comment by michaelcfanning** [comment]
1) remove any requirement to match kind pairs
2) make kind an array of unique elements
3) add sanitizer, source and sink as kinds

make it explicit that nesting level is exclusively used for that concept and doesn't depend on any implied semantics of 'kind'.

**Comment by michaelcfanning** [comment]
@lgolding, we'll close this and #202 once you have a draft that covers all three points documented above
