### ISSUE TITLE
You should be able to omit fileLocation.uri if it matches the files dictionary property name

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#195]
@michaelcfanning FYI. I discovered this bug while looking at Julien Henry's proposed SARIF v2 output.

The spec today says that given this `file` object:
```
"files": {
  "http://www.example.com/a.zip": {
    "fileLocation": {
      "uri": "http://www.example.com/a.zip"
    },
    "mimeType": "application/zip"
  },
```
... you can omit the `fileLocation` property, because its `fileLocation.uri` matches the property name in the `files` object:
```
"files": {
  "http://www.example.com/a.zip": {
    "mimeType": "application/zip"
  },
```

But that doesn't properly take account of `uriBaseId`. Suppose you have a run like this:
```
{                     # A run object
  "originalUriBaseIds": {
    "SRCROOT": "file:///C:/my_project/src/",
    "BINROOT": "file:///C:/my_project/bin/"
  },

  "files": {
    "ui/window.c": {
      "fileLocation": {
        "uri": "ui/window.c",
        "uriBaseId": "SRCROOT"
      },
      "mimeType": "application/zip"
    },
```
and suppose you omit the entire fileLocation object:
```
{                     # A run object
  "originalUriBaseIds": {
    "SRCROOT": "file:///C:/my_project/src/",
    "BINROOT": "file:///C:/my_project/bin/"
  },

  "files": {
    "ui/window.c": {
      "mimeType": "application/zip"
    },
```
When the viewer remaps this relative URI to an absolute location, it will not know whether to assign that absolute location to `SRCROOT` or `BINROOT`. So you need to _keep_ the `fileLocation` object -- but you can omit its `uri` property:
```
{                     # A run object
  "originalUriBaseIds": {
    "SRCROOT": "file:///C:/my_project/src/",
    "BINROOT": "file:///C:/my_project/bin/"
  },

  "files": {
    "ui/window.c": {
      "fileLocation": {
        "uriBaseId": "SRCROOT"
      },
      "mimeType": "application/zip"
    },
```

Here's what the spec should say:

> If `fileLocation.uri` matches the property name in the `files` object, then:
> - If `fileLocation.uriBaseId` is absent, you can omit the entire `fileLocation` object.
> - If `fileLocation.uriBaseId` is present, you must keep the `fileLocation` object, but you can omit its `uri` property.

**Comment by michaelcfanning** [comment]
Yes. This is simply a bug in our content nice find. 

Do me a favor while we are here. We should prefer consistently adding trailing slashes to any URI or URI-like things in the spec/examples that represent directories. :)

**Comment by lgolding** [comment]
Fixed in the issue description above, and also in the email I just sent (you caught me just before I sent it! :-) )

**Comment by michaelcfanning** [comment]
:)

**Comment by lgolding** [comment]
Here's an alternative proposal:
> ### fileLocation property
> Depending on the circumstances, a file object either **SHALL**, **MAY**, or **SHALL NOT** contain a property named `fileLocation` whose value is a `fileLocation` object (§3.2).
>
> If the `file` object represents a top-level file, then `fileLocation` **MAY** be present.
>
> If `fileLocation` is present, then if the property name of the containing `file` object within `run.files` is of the form #_uriBaseId_#_relativeReference_, the `fileLocation` object’s `uriBaseId` property **SHALL** equal _uriBaseId_, and its `uri` property **SHALL** equal _relativeReference_; otherwise its `uriBaseId` property **SHALL** be null and its `uri` property **SHALL** equal the property name.
>
> If `fileLocation` is absent, then it **SHALL** default to the value specified in the previous paragraph. That is, if the property name of the containing `file` object within `run.files` is of the form #_uriBaseId_#_relativeReference_, the defaulted `fileLocation` object’s `uriBaseId` property **SHALL** equal _uriBaseId_, and its `uri` property **SHALL** equal _relativeReference_; otherwise its `uriBaseId` property **SHALL** be null and its `uri` property **SHALL** equal the property name.


```

**Comment by lgolding** [comment]
This is now moot. `run.files` is no longer a dictionary. @michaelcfanning FYI.
