### ISSUE TITLE
threadFlowLocation.step should be all or nothing

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#203]
`threadFlowLocation.step` is optional, but if any `threadFlowLocation` in a given `codeFlow` has it, then all the `threadFlowLocation`s in the `codeFlow` should have it. The whole point is to allow users to discuss the code flow by saying things like "Look what happens at Step 4!".

The spec doesn't point out this subtlety; it just says that the property is optional.

@michaelcfanning

**Comment by michaelcfanning** [comment]
Per TC#20, approved for CSD.2. Editorial clarification, no further discussion required.

**Comment by lgolding** [comment]
Since `threadFlowLocation.step` is gone (#219), this issue is moot.
