### ISSUE TITLE
Clearly separate start/end vs. charOffset/length region property domains

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#204]
In example 1:
The first character in each of those regions is the "g" on line 2.

No. It turns out by spec that these regions are an insertion point with no length. 

abcd\r\nefg\r\nhijk\r\nlmn

{ "charOffset": 8 }

charLength is not expressed, and therefore has its default value of 0. This is valid, we've got an insertion point right before the "g" character. Your EXAMPLE 2 regions are _not_ equivalent, they actually do represent the letter "g" because their length is implicitly the remainder of the expressed start line.

**Comment by michaelcfanning** [comment]
Tried to read the spec more carefully. I see this:

A text region SHALL specify both its start (the location of its first character) and its end (the location of its last character).

And yet, in your example, the region does not specify its end location. So, in this case, do we assume a length of zero? or do we assume that the same implied 'run to the end of the line' logic is in play, due to the fact that the end location hasn't been specified?

for now, I'm going to imlement this logic, as it makes your examples legal. This is a bit contrary to the SHALL statement above, so do think we need a response here.

NOTE: i am creating unit tests based on your spec, so am interested in tracking any updates you make carefully to keep things in sync.

**Comment by michaelcfanning** [comment]
Oh. I can't follow through on this. :) The reason is that I can't tell whether charLength was omitted or not. For now, I MUST assume that charLength of zero is accurate in a case where charOffset is non-zero and there's no other supporting information expressed in the start/end pairs. 

So, I am returning to my first statement, I'm treating the example cited there as an insertion point. Everything else follows the equivalence you specified.

**Comment by michaelcfanning** [comment]
new Region() { CharOffset = 8, StartColumn = 3 })

Here's another good example of unwanted complexity. By spec, this region is intended to say, use a starting location as specified by CharOffset. The start column of this offset should match column three of the implied start line. Because we have explicitly specified a non-zero start column, however, the implied charLength equals the remainder of the current line excluding new line characters.

Eep. We can design something simpler than this. :)

**Comment by michaelcfanning** [comment]
Implementing the spec as it stands today is an exercise in unnecessary complexity. We should instead not allow the charOffset/charLength domains to intermingle with the start/end property pairs.

in other words, you cannot mix and match the start location and end location. if you specify charOffset, then you must specify charLength. if you populate startLine, all remaining start/end properties that are required to specify the region must be present. if both property sets are populated, they must specify (on their own) the same region.

**Comment by michaelcfanning** [comment]
Per TC#20 today, this change is approved. It is a technical change with no further discussion required (i.e., ready to prepare spec text).

**Comment by michaelcfanning** [comment]
@lgolding this is an important change that would be useful to close on asap.

**Comment by lgolding** [comment]
@michaelcfanning Ok, I'll do the change draft for this one next.
