### ISSUE TITLE
Suggestion: expand text in 3.22.2 examples to describe complete text associated with regions

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#205]
Consider this statement for EXAMPLE 3 in this section:

The first character in each of those regions is the "e" at the start of line 2.

This is a true statement but it would also be helpful to understand that the entire text of the region is "efg".

**Comment by michaelcfanning** [comment]
Per TC#20 meeting, approved for CSD.2, editorial change only

**Comment by michaelcfanning** [comment]
Closing in preference of #201

**Comment by lgolding** [comment]
@michaelcfanning Your comment said you were closing this, but you didn't actually do it, so I'm doing it now and labeling it `resolved-wont-fix`.
