### ISSUE TITLE
Provide deeper guidance around canonicalization of hardlinks, etc.

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#212]
From public comment on CSD.1:

Section 3.3. I don’t see any discussion of canonicalization anywhere in this section. How are symlinks, hardlinks, ./, and ../ handled? (Hardlinks cannot be canonicalized). Perhaps the cited RFC addresses it, but I still think it would be worth calling the readers attention to the matter.

**Comment by michaelcfanning** [comment]
technical issue warranting further discussion

**Comment by michaelcfanning** [comment]
Note this example from an actual tool (FxCop). The path below contains a location within a source enlistment that itself is anchored by a root that isn't explicit. In other words, i.e.,

Allowing specification of parent directories is always a concern, as these paths can 'slip' out of a sandboxed location.

We are currently interpreting the URL below as consisting of a uriBaseId == $(ProjectDir) with the remainder of the path in the uri component of the FileLocation instance.

$(ProjectDir)/../../../../../bld/bin/AnyCPU_Debug/Sarif.Multitool/net461/Microsoft.Json.Pointer.dll

**Comment by michaelcfanning** [comment]
Relates to #209. In that issue, we place the burden for path normalization on the producer.

In addition, I think I'd suggest that we encourage producers (via SHOULD language) to resolve paths to some absolute/relative form that doesn't include use of ../.

I'm not sure what we need to provide in the area of hard links and sym links. The analysis URIs will refer to the names provided when listing a directory. We could provide a 'role' that identifies these constructs but we'd also presumably benefit from a pointer to the actual thing indirectly pointed to. I'm not clear on what analysis scenario would require this.

I think I'd suggest that we modify the spec to resolving file paths completely (e.g., by eliminating ..\) and then close this issue (unless/until a clear need around hard and syms links materializes). @lgolding , @fishoak, thoughts?

**Comment by lgolding** [comment]
Who submitted the public comment?

**Comment by katrinaoneil** [comment]
@lgolding, my former co-worker Jon Giffin

**Comment by michaelcfanning** [comment]
TC recommendation for direct producers: 
  for files, you SHALL normalize to the file system's absolute path then create URIs from this
    (for converters, we recommend creating a uriBaseId comprising everything to the left of the rightmost .. segment)
  for other uris, follow the normalization semantics defined by 3986 (transforms double slashes to one, slash dot becomes nothing, etc).

**Comment by michaelcfanning** [comment]
Closing this in preference of #315. We don't believe that recording the existence of junctions, hard links, etc. is required.
