### ISSUE TITLE
Avoid JSON terminology where possible

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#213]
Section 1.2. Property Bag. Avoid the implementation-speciﬁc “JSON” term in your deﬁnitions. Deﬁne this as “an unordered set of properties with arbitrary camelCase names

**Comment by michaelcfanning** [comment]
Feedback above provided as CSD.1 public comment. Approved, fix at editor's discretion, no technical change or further discussion required.

**Comment by michaelcfanning** [comment]
@lgolding, can you make a call on this? If you intend to make the change, leave it open. i believe we now think the JSON specificity is ok, based on prior TC discussion? if so, close this.

**Comment by lgolding** [comment]
I will make a pass and remove gratuitous JSON dependencies, but I won't spend much time (< 1 hr).

**Comment by lgolding** [comment]
@michaelcfanning  I've spent about 15 minutes on this and determined there are two types of work here:
1. Avoiding gratuitous use of terms like "JSON object" where it can easily be avoided.
2. More systematically disengaging the description of the object model from the description of its serialization.

I will only do the first of these for CSD.2.
