### ISSUE TITLE
Consider adding a discrete 'id' object

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#217]
We have lots of identifiers in the format. They are confusing to track and, I suspect, rendered inconsistently. In some cases, we see a need to note that an id is explicitly a guid. In other cases, a logical identifier is indicated. Sometimes, we provide a matching description (as a sibling property).

Does this become easier if we try to define/utilize a common identifier object? This is in the spirit of the same approach we made for message, finally understanding that we would benefit from some bundling here.

Potential members:

id {
   "guid" : …,
    "logicalName"
     "description"
}

**Comment by michaelcfanning** [comment]
@lgolding, I believe we closed on a proposal for this

automationId
{
description // a message object. didn't discuss but makes sense
instanceGuid // guid representation for a specific instance
instanceId // hierarchical identifier consisting of the correlation id + suffix that uniquely identifies it
correlationGuid // guid representation of the set of things of which this id is an instance
}

**Comment by lgolding** [comment]
Here's what the proposal looks like (including our decision that a run might belong to more than one aggregate):
```
{
  "version": "2.0.0",
  "runs": [
    {
      "id": {
        "instanceId": "Nightly Fxcop run for sarif-sdk/master/2018-10-05",
        "instanceGuid": "11111111-...",        # Stands for the _entire_ instanceId.
        "correlationGuid": "22222222-...."     # Stands for the leading components of instanceId.
      },
      "aggregationIds": [
        {
          "instanceId": "Nightly security tools run for sarif-sdk/master/2018-10-05"
          "instanceGuid": "33333333-...",      # Stands for the _entire_ instanceId.
          "correlationGuid": "44444444..."     # Stands for the leading components of instanceId
        }
      ],
      ...
    }
  ]
}
```

**Comment by lgolding** [comment]
It's important to understand that we've changed the semantics from the existing set of "loose" id properties. In particular, the old `logicald` corresponded to `correlationGuid`, not to `instanceGuid`; that is, it represented only the _leading components_ of our new `automationId.instanceId`. That old `logicalId` does not correspond directly to any property of our new `automationId` object. If `automationId` had a `correlationId` property (a readable version of `correlationGuid`), that's what the old `logicalId` was.

**Comment by lgolding** [comment]
@michaelcfanning What do you think of `engineeringSystemId` as opposed to `automationId` for the name of the new object? I found myself writing the sentence:

> An `automationId` object encapsulates various information about its containing object, specifying that’s object’s role within an engineering system.

... so the name `engineeringSystemId` seemed better. Of course that could be read as "the id of the engineering system". Thoughts?

**Comment by michaelcfanning** [comment]
the 'engineering system id' seems like the general name for the system. the automation id is intended to specify a specific process enabled by the engineering system. so the key term in your text is 'within' - we require this term to clearly specify something within the system and not the system itself.

'pipelineId' may work.

I wonder whether 'id' is even correct as a term, as this is now more a bundle of information rather than an explicit id. e.g., 'pipelineMetadata' or 'automationMetadata'.

**Comment by lgolding** [comment]
Good, we agree that "engineeringSystemId" identifies the wrong thing. And in a previous conversation, I think I persuaded you that "pipeline" wasn't a commonly used term for the thing this object describes. So we're back to "automation" and I'm ok with that.

As for "id" _vs._ "metadata": I think "id" is still ok; I think my text "information that specifies its containing object's identity and role within an engineering system" is accurate.

"Metadata" is one of those words, like "info" or "process" (used as a verb), that doesn't say anything, or rather, it doesn't say enough. What _kind_ of information does it contain? I think it's still fair to say it contains identifying information, so I'm back to being ok with "automationId".

**Comment by michaelcfanning** [comment]
My suggestion is to use 'automationDetails' as this is consistent with versionControlDetails, another bundle of identifiers and other useful data clustering around a topic.

**Comment by lgolding** [comment]
**Stream of consciousness:**

That's a definite candidate. My reservation is this: in the case of "version control details", it's absolutely clear  to me what kind of "details" there are -- if we'd called the object `versionControlMetadata`, I'd've been just as happy, because it overcomes my objection above; it tells me what _kind_ of metadata it contains. Whereas in the case of "automationDetails", it's less clear to me what kind of details we have; "automation" just doesn't call up a clear picture in my mind that way "version control" does; and so I want some more help from the second component of the name...

**Proposal:**

If we use "details", how about `engineeringSystemDetails`? If `versionControlDetails` is "a bundle of information clustered around an object's relation to the version control system", then `engineeringSystemDetails` is "a bundle of information clustered around an object's relation to the engineering system".

**Comment by lgolding** [comment]
Re: "metadata": I'm fine leaving "versionControl**Details**". I only mentioned it by way of saying that the word "metadata", which I usually find fuzzy, works fine for me as long as it's sufficiently qualified.

Re: "engineering system", the spec actually defines it:

> **engineering system**<br/>
> software development environment within which analysis tools execute
>
> NOTE: An engineering system might include a build system, a source control system, a result management system, a bug tracking system, a test execution system, and so on.

... and there's even a Conformance Clause for engineering systems.

Having said all of that: I think "scanAutomationDetails" is fine. Let's use that.

**Comment by michaelcfanning** [comment]
ship it.
