### ISSUE TITLE
Delete 'threadFlowLocation.step' property

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#219]
The threadFlowLocation 'step' property is purely a computed value, it is the index of the threadFlowLocations array index + 1. As such, we don't need a member for it. Instead, we can note that the step value can be inferred from the array index in cases where a viewer would like to provide it.

Before doing so, we need to be convinced that this property or something like it isn't useful for embedded links (i.e., providing a threadflowlocation message that has an embedded link pointing to another). This is a real scenario.

**Comment by lgolding** [comment]
@michaelcfanning As I commented in email, this works fine in a viewer (which can count up and display the index), but makes it more difficult for people who are looking directly at the log file.

Recall the scenario was one engineer saying to another "Look what happens in Step 6!". When I (I think it was me) offered that scenario in support of the `step` property, I had in mind people looking at the log file in (say) Notepad.

Did you always have the viewer scenario in mind? Is your position that the (rare?) case of two engineers poring over a text file is not worth the extra file size of adding this property, and the extra complexity of validating it?

**Comment by lgolding** [comment]
@michaelcfanning Ping on the question I raised in my previous comment. If you don't consider the scenario of two human beings collaborating over a raw log file significant, I'm happy to remove this property. It would certainly simplify the spec and obviate the need for validation rules around this property.

**Comment by lgolding** [comment]
@michaelcfanning re-ping. I suppose in the "collaborating over a raw file scenario", the engineer can say "look what happens on line 42", so perhaps that's not a good enough reason to keep the property.

**Comment by michaelcfanning** [comment]
Let's delete it. Note that every physical location (itself a member of threadflowlocation.location) has an 'id' that could be used to specify an id users can search on in the log file. Any literal 'step' value could be inferred from the array index. [note that my question above about whether the loss of step impacts embedded links is resolved by noting the existing of plc.id, these are the values referenced in a link.
