### ISSUE TITLE
should we provide 'suppressionJustification'?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#22]
Copied from https://github.com/sarif-standard/sarif-spec/issues/254, created by @michaelcfanning:

Many in-source suppression mechanisms provide a justification field. This information may be useful to persist to a log file, for auditing purposes.

if we provide a field, we need to be cognizant that a result can be suppressed in multiple locations, e.g., both in-source and as part of an external baseline. If we add something, is it a single member relevant to in-source suppressions only? Is there a member for each suppression state? Do we provide an array of justification strings, with no particular ordering or association?

Or take @rtaket's original suggestion: we should define a suppressions array on a result, each element of which might include information such as its justification and persistence location. We could add this data as an additional member (deprecating suppressionState).

**Comment by lgolding** [comment]
Comment from @lgolding:

We could have 

```
"results": [
  {
    "suppressions": [
      {
        "kind": "...",
        "justification": "..."
      }
    ]
  }
]
```

But we don't yet have a customer for this, so deferring.

**Comment by lgolding** [comment]
Comment from @lgolding:

Also, Roslyn uses the current `suppressionStates` mechanism, so it would be breaking for them.

**Comment by michaelcfanning** [comment]
Closing this item in favor of results mgmt. bucket item, #48
