### ISSUE TITLE
Add a correlationGuid property to run

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#220]
@michaelcfanning wrote in #196:

The property would be named 'correlationGuid'. it would serve the same function as 'logicalId' except that the semantics of populating the property are clear, it should be a GUID. generally, this slot might be an alternate to the logical id. the logical id is a more readable id that supports hierarchical data.

i thought we proposed this purely to allow for result management systems that consistently utilize guids for storing various things. the instanceGuid and baselineGuid argues, from a certain perspective, for a correlationGuid.

**Comment by lgolding** [comment]
@michaelcfanning I don't recall this proposal. The problem with having both `logicalId` and `correlationGuid`, where both are optional, is that... well... they are optional. A result management system that insists on labeling everything with a GUID will be unhappy if `run.correlationGuid` is missing, and you can't require all tools to populate it.

An engineering system could maintain a mapping from human-readable, hierarchical `logicalId`s to GUIDs, and post-processor could use the mappings to populate `run.correlationGuid`.

**Comment by michaelcfanning** [comment]
What's the issue? A pipeline processing tool will normalize log files, including adding the correlation guid if possible. This is the pattern in our own internal pipeline (where we do things like inject region snippets and remove non-deterministic information).

**Comment by lgolding** [comment]
@michaelcfanning Ok, then. I don't object to a property that allows an engineering system to stamp a run with a "logical Guid". I'll write this change draft tomorrow.

**Comment by lgolding** [comment]
@michaelcfanning As we discussed: the examplar for usage of this property is the VSTS build definition, which has a GUID. That GUID could serve as `run.correlationGuid`.
