### ISSUE TITLE
Make invocation.workingDirectory a fileLocation object

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#222]

**Comment by kupsch** [comment]
The working directory must be a local path, so it could be a URI-formatted string if it were required to be a file scheme URI. To go further, why not a file object so the directory can be made relative to a well known base location?

**Comment by lgolding** [comment]
@kupsch I do like that. A common scenario would be to run the tool from the root of the source tree:
```
{    # An invocation object
  "workingDirectory": {    # fileLocation object
    "uri": "."
    "uriBaseId": "SRCROOT"
  }
  ...
}
```

**Comment by michaelcfanning** [comment]
+1

**Comment by lgolding** [comment]
@michaelcfanning @kupsch 

With that agreement, I'll change the issue name to "Make invocation.workingDirectory a fileLocation object.'

@michaelcfanning I'll write this change draft now, consistent with our agreement to address breaking changes first.
