### ISSUE TITLE
CSD.1 spec incorrectly places result 'correlationGuid' property on the run object

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#228]
@lgolding 

since you are building out our errata for the draft. :)

**Comment by michaelcfanning** [comment]
Fix for this in flight.

**Comment by lgolding** [comment]
The schema and the spec now define `correlationGuid` on both `run` and `result`. `run.correlationGuid` can be used by engineering systems, for example to specify a "build definitions".
