### ISSUE TITLE
Does externalizable properties address performance goals sufficiently?

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#230]
In order to be useful in high-performance situations (which is the core scenario for externalizable properties), the externalizableFiles property should be the first property listed. It needs to be first in order to provide a reader a clue that that they can perform a high performance read (i.e., the point is not to have to parse the whole log file in order to get oriented).

Also, we should consider requiring producers to opt into the external files entirely (with the exceptions of results files) or not at all. i.e., no mix and matching.

Again, with the exception of the results table.

**Comment by lgolding** [comment]
The answer is yes!
