### ISSUE TITLE
objects without property bags

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#238]
The objects below do not have a properties property to act as a property bag.  It would be useful for the first set of objects.  It is not clear that it would be useful in the second set, but since it small, I think it should be added for completeness.  Also the schema repeats the definitions of the property bag instead of using $ref to a single definition. 

message
sarifLog
attachment
conversion
physicalLocation
region
rectangle
logicalLocation
resources
ruleConfiguration
replacement
exception

fileContent
fileLocation
fix
fileChange
replacement
hash

**Comment by michaelcfanning** [comment]
ok. agree. let's just permit it for everything. this should actually simplify the spec text. the only significant downside i see is that this property adds another item for every intellisense style dropdown.
