### ISSUE TITLE
Specify that nested paths shall be absolute

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#24]
Copied from https://github.com/sarif-standard/sarif-spec/issues/258, created by @lgolding:

In the section on [`run.files`](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#run-files), add the requirement that when a URI-valued property refers to a nested file whose location can be specified by a path relative to its parent (for example, a file within a compressed archive), the nested path should be specified as an absolute path (that is, it should begin with a slash).

Right:

```
"uri": "file:///C:/packages/foo.zip#/bar/baz/qux.cpp"
```

Wrong:

```
"uri": "file:///C:/packages/foo.zip#bar/baz/qux.cpp"
```

It doesn't actually matter, but  the idea is that this is a location starting from the "root" of the parent file.

**Comment by michaelcfanning** [comment]
@lgolding resolve before next TC?

**Comment by lgolding** [comment]
This is already done. Section 3.12.9, "files property", says:

> If the file is a nested file, then the property name **SHALL** be the URI of the outermost parent, together with a fragment that describes the nesting of the file within its parent or parents. The fragment shall be expressed as an absolute path; that is, it shall begin with a forward slash character (“/”).
