### ISSUE TITLE
Consider removing type inconsistency with message property in exception object

### ISSUE THREAD

**Issue by fishoak** [oasis-tcs/sarif-spec#240]
The message property in the exception object is of string type. In all other objects, properties whose name is "message" are expected to be message objects.

When I first saw this, I thought it was a bug, but I then read the text in the section describing that property and found that it was deliberately so. This is bad for two reasons:

1. It's confusing to human readers.
2. It's confusing to software readers too. I found that the Python schema tool I am using (python_jsonschema_objects) threw an error; it appears to expect that all properties with the same name have values with the same type (I'm inferring this from its behavior.)

There seem to be two solutions:
1. Change the name of the property, or
2. Change the type so that it is a message object

I prefer the second of these. We can always state that the message is unlikely to be anything except one that specifies plain text.

**Comment by lgolding** [comment]
@fishoak I don't object to this. I'll submit a draft for next time.
