### ISSUE TITLE
Rename startTime/endTime to startTimeUtc and endTimeUtc

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#242]
It needs to be more explicit in the format that these values s/be UTC. We had a usage report in which a producer was explicitly setting startTime (as non-UTC) while working with SDK helpers that automatically set endTime to a UTC value.

**Comment by lgolding** [comment]
@michaelcfanning We might also want to change the following property names:
- `threadFlowLocation.timestamp`
- `notification.time`
- `versionControlDetails.timestamp` (which might be problematic if the VCS doesn't provide the time in UTC)
- `file.lastModifiedTime` (problematic if the OS/file system doesn't provide the time in UTC)

**Comment by michaelcfanning** [comment]
It is possible to convert local time to UTC and back, what problem you see, can you clarify? 

A VCS typically sets time to local time when syncing files (TFS has settings to prefer the server time). the difference here can create problems no matter whether the date time is converted to UTC or not. We  introduced the timestamp setting here as a revision equivalent (i,e, 'sync my enlistment to yesterday at noon').

file.lastModifiedTime is interesting. if you moved your machine's time-zone, does it update file created and modified time? something we could test for, I'm sure.

in any case, since a producer can convert UTC to local, if necessary, is there a problem specifying UTC for everything? there's a nice clarity to both requiring this and making it explicit in names. this area is a common source of problems (time zone confusion, I mean). the only reason we should not do this is if we create an undue burden on producers/consumers.

**Comment by lgolding** [comment]
I was worried about a case where the producer wanted to populate `versionControlDetails.timestamp`, but the producer _didn't know_ what time zone the VCS was expressing its times in; or where the producer wanted to populate `file.lastModifiedTime`, but the producer _didn't know_ what time zone the OS was expressing its file times in.

Is this a plausible concern?

**Comment by michaelcfanning** [comment]
It's plausible but I'm not sure how likely there is to be a problem. file.lastModifiedTime seems likely to be retrieved in the same environment that's producing the SARIF.  For the scenario where a client has performed a sync using a timestamp, same point stands.

Note that if there's utter confusion about the locale/etc. of a time-stamp, it's going to have limited utility, yes? the timestamp in this case would be a bit of a curiosity (informational only) rather than something that could drive automation.

btw - why is it notification.time and not notification.timestamp?

**Comment by lgolding** [comment]
Ok.

I named it `time` because to my ear "notification time" read better in English than "notification timestamp". I'll go back and see if it makes more sense to make the opposite change: `timestamp` => `time` everywhere. I agree that consistency trumps my finely tuned ear.

**Comment by lgolding** [comment]
- `threadFlowLocation.executionTime`? (but might be mistaken for a duration)
- `versionControlDetails.commitTime` or `.revisionTime`?
