### ISSUE TITLE
Rename versionControlDetails.tag to revisionTag

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#249]
We have a specific meaning for 'tag' in context of SARIF and this recapitulation of the term is confusing.

**Comment by lgolding** [comment]
`syncLabel`? Ok.

**Comment by kupsch** [comment]
how about revisionTag (my preference) or revisionLabel to be consistent with revisionId?

**Comment by lgolding** [comment]
Much better! Thanks.

**Comment by michaelcfanning** [comment]
LGTM
