### ISSUE TITLE
One of result.{message,formattedRuleMessage} is required

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#25]
Copied from https://github.com/sarif-standard/sarif-spec/issues/259, created by @lgolding:

The section on [`result.formattedRuleMessage`](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#result-formattedrulemessage) correctly says:

> If the formattedRuleMessage property is present on a result, the message property (Sec. 5.14.5) shall be absent. If the message property is present on a result, the formattedRuleMessage property shall be absent.

But the section on [`result.message`](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#result-message) inconsistently says that `result.message` _shall_ be present.

**Comment by michaelcfanning** [comment]
@lgolding try to close by next TC meeting?
