### ISSUE TITLE
Consider result-level URI for alternate viewer

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#250]
Consider a team server that's producing results for a single tool. This server exports as SARIF and a pipeline aggregates its results with those of other tools. Now a bug filer comes along and auto-files several issues, among them several that were produced by this specific tool team server. The SARIF log file could useful contain a link to each result that takes the user to the dedicated team server to get more detailed information.

Something along the lines of result.hostedViewerUri or result.alternateViewerUri

**Comment by lgolding** [comment]
Proposal: Have an array of `hostedViewerUri`.No guidance on ordering.

**Comment by lgolding** [comment]
After discussion with @michaelcfanning: Only one is needed. This property is (at least primarily) for the benefit of the producing tool: "Here's my online viewing experience for this result."
