### ISSUE TITLE
Consider merging resources probing into general external files mechanism

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#252]

**Comment by lgolding** [comment]
These two mechanisms are orthogonal. "External files" is a performance optimization. It is logically equivalent to a `#include` -- it is a purely textual means of splitting a large file into smaller files, with no semantic significance. It takes precedence over any other "probing" mechanisms we might define.

The resource probing mechanism is a means of providing resources for different languages. If `resources` is externalized, it takes precedence over any resource file for `tool.language` that might be located by probing. (The spec does actually say this.)
