### ISSUE TITLE
Rename externalizedProperty.version to sarifVersion

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#254]
I propose to rename the property `externalizedProperty.version` to `sarifVersion`:
```
{                             # An externalizedProperty object
  "$schema":                  # See §4.2.2.
    "http:///json.schemastore.org/sarif-externalized-property-2.0.0",

   "sarifVersion": "2.0.0",   # See §4.2.3.

                              # See §4.2.4.
  "runInstanceGuid": "00001111-2222-3333-4444-555566667777",

  "files": {                  # See §4.2.5.
    "apple.png": {
      "mimeType": "image/png"
    },
    "banana.png": {
      "mimeType": "image/png"
    }
  }
}
```
That will make explicit the decision we reached at TC <span>#</span>24, where we decided that the version property referred to the SARIF version rather than to a separate external file format version.

**Comment by kupsch** [comment]
for consistency, should the sarifLog object's "version" property also be changed to "sarifVersion"?

**Comment by lgolding** [comment]
I'm trying to follow a (self-imposed) guideline: "give a name a prefix if and only if there's any doubt what it refers to." So in the externalized property schema, there was discussion about what the `version` property might refer to, so I propose to qualify it to `sarifVersion`. In the primary schema, there is no question what the `version` property refers to, so I prefer not to qualify it.

**Comment by lgolding** [comment]
Before we introduced the `externalFile` object (the object at the root of a SARIF external file), we had two properties named `version`. The spec says:

- `sarifLog.version`: "the version of the SARIF format to which this log file conforms."
- `tool.version`: "the tool version in whatever format the tool natively provides".

These two identically named properties meant different things, but no confusion resulted, because it was obvious that "version" in each case was scoped to and described the object that contained it.

At present the spec says:

- `externalizedProperty.version`: "the version of SARIF that defines the **external file format** to which this external file conforms."

My concern is that in the case of the `externalFile` object, there might for the first time be confusion about what a `version` property describes. I'm not willing to pay the "redundancy" price and rename `sarifLog.version` to `sarifLog.sarifVersion`, for the same reason I wouldn't rename `tool.version` to `tool.toolVersion` (and I didn't name `notification.timeUtc` as "`notification.notificationTimeUtc`").

However, if I rephrase the description of `sarifLog.version` to "the version of the SARIF **specification** to which this log file conforms", and I describe `externalFile.version` as "the version of the SARIF specification to which this external file conforms", then the properties are perfectly consistent and I don't think there's any confusion.

So how about I close this issue and just make that editorial change?

**Comment by kupsch** [comment]
That works for me.  I just wanted the names to be consistent.

**Comment by lgolding** [comment]
Opened editorial change #255, "State that sarifLog.version and externalizedProperty.version refer to the spec version" in place of this issue.
