### ISSUE TITLE
Editorial: Remove misleading uriBaseId examples

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#257]
I think there are examples that strip a common prefix from _deterministic_ URIs such as work item URIs, and puts them in `originalUriBaseIds`. This is bad because once a "determinizer" removes non-deterministic elements such as `originalUriBaseIds`, you've lost the ability to navigate to your work items.

Go through all examples of `uriBaseId` and `originalUriBaseIds` and remove any that demonstrate this anti-pattern.

@michaelcfanning FYI.

**Comment by lgolding** [comment]
@michaelcfanning When we discussed this issue once before, we considered adding a property `run.deterministicUriBaseIds` to cover just this case: you got the benefit of not having to repeat the lengthy URI prefix, without the worry that a determinizer would remove it.

Do you remember why we rejected that idea?

**Comment by michaelcfanning** [comment]
Yes. Nominal compactness of the JSON in this case isn't helpful, except arguably to increase load times in an editor. Actual compression libraries will do just fine with large #s of repeated/length strings. Chopping up an absolute URL compromises readability in that users have to go stitch together all components of the URL. Chopping up absolute URLs also compromises the click-through functionality provided by many code editors (i.e., in environments such as the VS IDE, you can click absolute URLs that you encounter in a JSON file. Finally, it isn't clear what the common root is in this case. In the version control case, it is the non-deterministic root. For URLs, it is an arbitrary common prefix that best supports the goal of compacting the file.

**Comment by lgolding** [comment]
@michaelcfanning If you don't consider brevity a good reason to use `uriBaseId`, then as part of this editorial change I will remove it from the list of justifications in §3.3.3, "uriBaseId property":
> NOTE: There are various reasons for providing the `uriBaseId` property:
> - Portability: A log file that contains relative references together with `uriBaseId` properties can be interpreted on a machine where the files are located at a different absolute location.
> - Determinism: A log file that uses `uriBaseId` properties has a better chance of being “deterministic”; that is, of being identical from run to run if none of its inputs have changed, even if those runs occur on machines where the files are located at different absolute locations. For more information on this point, see Appendix F, “Producing deterministic SARIF log files”.
> - Security: The use of `uriBaseId` properties avoids the persistence of absolute path names in the log file. Absolute path names can reveal information that might be sensitive.
> - Semantics: Assuming the reader of the log file (an end user or another tool) has the necessary context, they can understand the meaning of the location specified by the `uri` property, for example, “this is a source file”.
> - Brevity: The `uriBaseId` property might be shorter than the absolute path it represents.

**Comment by michaelcfanning** [comment]
Makes sense to do so.

**Comment by lgolding** [comment]
@michaelcfanning Done. There was only one such example in the spec. I made the change in the [provisional draft](https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/ProvisionalDrafts/sarif-v2.0-csd02-provisional.docx) but also provided a [change draft](https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/ChangeDrafts/Accepted/sarif-v2.0-issue-257-no-deterministic-uriBaseIds.docx) so you can see the change in isolation.
