### ISSUE TITLE
Create set of general icon types for review by TC

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#260]

**Comment by michaelcfanning** [comment]
This issue is closed in favor of the approach taken in #202. We will define a set of well known thread flow location kinds that viewers can use as hints to display relevant icons.

**Comment by michaelcfanning** [comment]
@lgolding should document this close

**Comment by lgolding** [comment]
@michaelcfanning I assume you mean I should mention it in the Editor[s Report. Ok.
