### ISSUE TITLE
Remove run.architecture

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#262]
Do we even require this? Should people encode architecture as part of run.instanceId (which contains a logical identifier). If architecture is _not_ encoded in the run.instanceId, then we must be comfortable with the architecture serving implicitly to determine the equivalence class of runs. i.e., the analysis results associated with the x64 build of a product are not the same as the analysis results of the x86 build.

We should probably zap this property. I note that we don't have other build qualifiers, such as debug vs. retail.

**Comment by lgolding** [comment]
Renamed the issue. We've decided that architecture _can_ be an element of the hierarchical instanceId, but it doesn't _have_ to be; it's not a first-class citizen. The spec already shows examples where it appears as a hierarchical component.

**Comment by lgolding** [comment]
Changes made directly in provisional draft.
