### ISSUE TITLE
Clarify presence or absence of instanceId components

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#263]
A runAutomationDetails.instanceId has a logical and instance component.
The instance component is the trailing content following the last forward slash or, in cases with no forward slash, the property value itself.
A missing instance component is indicated by a trailing slash with no following content.

logical (My Nightly Run/Debug/x64) and instance (2018-10-10)
My Nightly Run/Debug/x64/2018-10-10

logical only
My Nightly Run/Debug/x64/

instance component only 
2018-10-10

**Comment by lgolding** [comment]
Changes merged.
