### ISSUE TITLE
Define schema for localized resource files

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#265]
The schema should be:

- `version` -- `string`, required: the version of the SARIF specification to which this resource file conforms.
- `$schema` -- `string`, optional: an absolute URI from which this schema can be obtained.
- `tool` -- a `tool` object, required: the tool to which these resources belong. Its `language` property is required, and specifies the language of the resources in this file.
- `resources` -- a `resources` object, required: contains `messageStrings` and `rules` properties.

**Comment by michaelcfanning** [comment]
if we challenge the assumption that recapitulating the tool information is required, can we converge this format into the standard external files representation of a resources table? obviously, we need to retain language details

**Comment by lgolding** [comment]
@michaelcfanning and I agree that the spec needs improvement: it defines the format of a localized resource file to be confusingly almost-but-not-quite the same as that of a SARIF log file, and it takes pages to explain the difference.

Michael suggests above that we use the new external property file format to store localized resources.

It's true that the `externalProperties` object (the object at the root of an external property file) doesn't have a `language` property, but we could add one. It would even be ok to mention that property in an external property file that does _not_ contain a `resources` object; after all, the spec says that the `tool.language` property is "a string specifying the language of the messages produced by the tool," so it makes sense to specify it even if the external property file contains (for example) a `run.results` array.

Alternatively, we could address the lack-of-language problem by adding an optional `language` property to the `resources` object. In a SARIF log file, if `resources.language` was absent, it would default to `tool.language`, and if it was present, it would be required to equal `tool.language`. In an external property file that contains a `resources` object, `resources.language` would required. But you see how this approach (defining `resources.language`) again gets us into subtle differences between an object's usage in a SARIF log file and an external resource file.

The more serious problem with leveraging the external property file format is that _it is designed to hold properties that are associated with a specific run_, most notably `results`. `externalProperties.runInstanceGuid` points to that run, and we'd have to say that in an localized resource file, that property would have to be absent. Also, a localized resource file should have _only_ a `resources` object, while a normal external property file can contain multiple properties of any externalizable type. Once again, we're in "almost but not quite the same" territory.

So I still maintain that a bespoke localized resource file schema is the best option. I'm not wedded to the idea that it contain a `tool` object (as in my proposal above); we could consider just having a `language` property. But traceability to the tool (especially the tool's version) might be important.

**Comment by lgolding** [comment]
@michaelcfanning FYI

We are closing this issue because at TC <span>#</span>32 we agreed to drop localization support entirely from v2.0.

**Comment by michaelcfanning** [comment]
ack.
