### ISSUE TITLE
Schema needs to be carefully scrubbed for minItems and uniqueItems use for all arrays

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#270]
This was opened in the sarif-sdk repo: Microsoft/sarif-sdk#1115. I'm opening this issue in the spec repo since it really is a spec issue.

**Comment by lgolding** [comment]
After discussion among @lgolding, @michaelcfanning, and @kupsch, we settled on the following principles to guide our choices:

1. Producing highly optimized (_e.g._, most compact) SARIF is not a goal.
2. The SARIF design should not force producers into an optimal implementation (_i.e._, we loosen some restrictions to accommodate sub-optimal approaches to analysis, fix generation, _etc._).
3. SARIF producers are allowed to emit explicit but unnecessary/not useful data (such as an empty array `[]`) _except_ in cases where doing so creates an invalid object.
4. We will provide explicit default values in the schema, which can be used during serialization to make SARIF compact.
5. We use an `anyOf` array + null construct to differentiate cases where we need to understand whether a producer has the capability to emit a construct which may be empty
6. We have observed that the use of `fileLocation`s generally requires an array to be unique
7. We prefer to err on the side of allowing arrays to be non-unique, in order to prevent too draconian validations

**Comment by lgolding** [comment]
index | root object | property | anyOf+null | required | minItems | uniqueItems | default
-- | -- | -- | -- | -- | -- | -- | --
1 | sarifLog | runs | yes | TRUE | 0 | FALSE | none
2 | attachment | regions |   | FALSE | 0 | TRUE | []
3 | attachment | rectangles |   | FALSE | 0 | TRUE | []
4 | codeFlow | threadFlows |   | TRUE | 1 | FALSE | none
5 | conversion | analysisToolLogFiles |   | FALSE | 0 | TRUE | []
6 | exception | innerExceptions |   | FALSE | 0 | FALSE | []
7 | file | roles |   | FALSE | 0 | TRUE | []
8 | fileChange | replacements |   | TRUE | 1 | FALSE | none
9 | fix | fileChanges |   | TRUE | 1 | TRUE | none
10 | graph | nodes |   | FALSE | 0 | TRUE | []
11 | graph | edges |   | FALSE | 0 | TRUE | []
12 | graphTraversal | edgeTraversals |   | FALSE | 0 | FALSE | []
13 | invocation | arguments | yes | FALSE | 0 | FALSE | null
14 | invocation | responseFiles | yes | FALSE | 0 | TRUE | null
15 | invocation | attachments |   | FALSE | 0 | TRUE | []
16 | invocation | toolNotifications |   | FALSE | 0 | FALSE | []
17 | invocation | configurationNotifications |   | FALSE | 0 | FALSE | []
18 | location | annotations |   | FALSE | 0 | TRUE | []
19 | message | arguments |   | FALSE | 0 | FALSE | []
20 | node | children |   | FALSE | 0 | TRUE | []
21 | properties | tags |   | FALSE | 0 | TRUE | []
22 | result | locations |   | FALSE | 0 | FALSE | []
23 | result | stacks |   | FALSE | 0 | FALSE | []
24 | result | codeFlows |   | FALSE | 0 | FALSE | []
25 | result | relatedLocations |   | FALSE | 0 | FALSE | []
26 | result | suppressionStates | yes | FALSE | 0 | TRUE | null
27 | result | attachments |   | FALSE | 0 | FALSE | []
28 | result | workItemUris | yes | FALSE | 0 | TRUE | null
29 | result | conversionProvenance |   | FALSE | 0 | TRUE | []
30 | result | fixes |   | FALSE | 0 | TRUE | []
31 | run | invocations |   | FALSE | 0 | FALSE | []
32 | run | results | yes | TRUE | 0 | FALSE |  
33 | run | versionControlProvenance |   | FALSE | 0 | TRUE | []
34 | run | aggregateIds |   | FALSE | 0 | TRUE | []
35 | stack | frames |   | TRUE | 0 | FALSE |  
36 | stackFrame | parameters |   | FALSE | 0 | FALSE | []
37 | threadFlow | locations |   | TRUE | 1 | FALSE |  
38 | run | newlineSequences |   | FALSE | 1 | TRUE | ["\r\n", "\n"]
39 | run | files |   | FALSE | 0 | TRUE | []
40 | run | logical   locations |   | FALSE | 0 | FALSE | []  
41 | resources | rules |   | FALSE | 0 | TRUE | []

**Comment by michaelcfanning** [comment]
Whew. You know, we really should try to get one more array into the format so that we have 42.

**Comment by lgolding** [comment]
At this time, the code generator cannot handle `anyOf`. So we cannot yet make the schema changes for properties that are specified as "anyOf + null" in the table above. We can make the rest of the changes.

The affected properties are:
- `sarifLog.runs`
- `invocation.arguments`
- `invocation.responseFiles`
- `result.suppressionStates`
- `result.workItemUris`
- `run.results`

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
We don't necessarily need to allow limitations in the tool to drive the schema update. We could, for example, maintain an altered schema that drives the SDK code gen until that library is functional.

**Comment by lgolding** [comment]
Yes, we can do that. In that case, we would:
1. Validate the SDK's copy of the schema that does not include `anyOf`.
2. Update the spec's copy of the schema by adding the `anyOf`s.
3. Publish the spec's copy of the schema to schemastore.

**Comment by lgolding** [comment]
(Of course now we have to remember to make future updates by hand in both copies of the schema until the code gen can handle the "real" schema.)

**Comment by lgolding** [comment]
@michaelcfanning 

The `externalPropertyFiles` work introduces some array-valued properties that we missed in the table above. Here is the way the _schema_ stands today with respect to those properties. The _spec_ isn't clear enough on these properties. It says what should happen if these properties _are_ externalized (in which case, obviously, the array must have at least one element), but it doesn't say what should happen if they are _not_ externalized (should it be absent? can it be an empty array? is there a default?). The spec doesn't even explicitly say that the array elements have to be unique, although obviously they do.

index | root object | property | anyOf+null | required | minItems | uniqueItems | default
-- | -- | -- | -- | -- | -- | -- | --
1 | externalPropertyFiles | files | | FALSE | 1 | TRUE | 
2 | externalPropertyFiles | invocations | | FALSE | 1 | TRUE | 
3 | externalPropertyFiles | logicalLocations | | FALSE | 1 | TRUE | 
4 | externalPropertyFiles | results | | FALSE | 1 | TRUE |
