### ISSUE TITLE
Introduce resultProvenance object

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#272]
Users who preserve a SARIF file as a baseline would like to have a notion of 'first seen' timestamp associated with results. This would easily allow a baseline to show the oldest known issues in a run. 

Now, for a clean file, it might not be worth persisting a per-rule timestamp that records the actual time at which the result was generated (but perhaps this could be the case). More commonly, a time-stamp associated with the original log file might itself flow to all results that are 'matched' in a more current analysis run. When thinking this through, it may be important to hold in mind that we currently provide an array of invocations to be associated with a single run, but there's no association between a result and a specific invocation instance (which would hold a timestamp that could be used for a 'first seen' value.

Notification objects already contain a timeUtc property. The cleanest thing to do here might be to provide result.timeUtc as well. This property could be populated in various ways, as described above.

@lgolding FYI issue raised from baselining work in Microsoft internal SARIF tools execution pipeline

**Comment by lgolding** [comment]
I agree that `result.firstDetectionTimeUtc` (as I'd call it, with my usual verbose style) is useful. It's totally useful to be able to see at a glance "Oh good heavens, this bug has been around for a year".

Do we also want `result.firstDetectionRunInstanceGuid` to trace it back to the run?

**Comment by michaelcfanning** [comment]
Offline discussion: proceed with this proposal.

**Comment by michaelcfanning** [comment]
Consider adding provenance property or type resultProvenance, and seeding it with these values, firstDetectionTimeUtc and firstDetectionRunInstanceGuid.

**Comment by lgolding** [comment]
I'm going to close this issue as `resolved-fixed`, and capture the remaining question in #287, "Define default for resultProvenance.lastDetectionTimeUtc`.

**Comment by lgolding** [comment]
... and now I'm _really_ going to close it.
