### ISSUE TITLE
Can we get out of the business of describing resource probing behaviors?

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#276]

**Comment by lgolding** [comment]
Remember the scenario the current design supports:

- I consume SARIF log files _from a variety of tools_ containing message strings in `en-US`, using a generic SARIF viewer ("generic" meaning "not specially adapted for a particular analysis tool").
- On my machine, the UI resource language (in .NET, `CultureInfo.CurrentUICulture`) is set to `fr-FR`.
- I want to reliably locate the corresponding `fr-FR` message strings (if they exist), _regardless of the tool that produced the log file_.

**Comment by michaelcfanning** [comment]
Closing this issue. We discussed in an offline telecon and at this point, this scenario seems sufficiently distinct from externalized properties to retain. We have a tracking item to develop a working example of resources probing (#281). We should be open to revisiting this topic based on that work when it materializes.
