### ISSUE TITLE
Editorial issues from Jim Kupsch

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#277]
This issue addresses the first batch from a set of editorial changes proposed by Jim Kupsch (@kupsch).

For the editorial changes I accept, I will make them directly in the CSD.2 provisional draft. For visibility, I will also make them in a change draft Documents\ChangeDrafts\Accepted\sarif-v2.0-editorial-kupsch.docx. I will check off each item when it's done.

For the editorial changes I decide not to make, I will list them at the bottom of this issue.

### Changes I made

| Section | Change | Comment |
| --- | --- | --- |
| §1 | State that this document is defining SARIF, and what SARIF stands for, in the introduction. | |
| §1 | Specify how to pronounce SARIF in a comment or footnote (JSON document has it as a footnote). | It's "a" as in "cat", and "i" as in "if" |
| §1 | "logical construct" -> "logical location" to match wording elsewhere | You're right, that's the only place I used that noun phrase. I do refer to "programmatic constructs" and "syntactic constructs in many places, but this was the only place I used "logical construct". |
 | §1.2 | Definition of file: "sequence of bytes accessible via a URI" -> "sequence of bytes.  The location of the contents at the time of the assessment are specified by a  URI in SARIF" | Your suggested alternative still concedes that the file must be URI addressable. The constraint you propose is good, but IMO it belongs in the section describing the `fileLocation.uri` property, not in the definition. So I'll leave the definition the same (except I'll change "accessible" to "addressable"), and I'll add this sentence to `fileLocation.uri`: "The URI **SHALL** specify the location of the file contents at the time the analysis was performed." |
| §1.2 | Definition of logical name: "rightmost" -> "most specific (often rightmost) | |
| §1.2 | Definition of property bag: set of properties" -> "set of non-standardized properties" | |
| §1.2 | Definition of redaction-aware property: Change "redaction-aware property" -> "redactable property". The property is not aware. | This is my favorite of all your suggestions :smiley: Much better! |
| §1.2 | Definition of top-level file: Delete entire line below as it seems to have nothing to do with definition ("Example: Category (for example, "Style" or "Security"), documentation, URI") | That line obviously belonged to some other definition, and I failed to move it when I shuffled some text around -- but I can't find the definition it might have applied to, so I deleted it. |
| §1.4 | C++ standard: Update to latest standard C++17 [ISO/IEC 14882:2017] | |
| §3.3.2.2 | Change "A SARIF post-processor ..." to 'When producing a file URI with a hostname (authority), it SHOULD start with `"file:///"` as in Example 2.  See [RFC8089] for more information on this point. | It's "_without_ a hostname (authority) ", but yes, "**SHOULD** start with" is better. I didn't adopt your exact suggested phrasing -- I still want to explain why you might want to do this -- but now the advice isn't limited to post-processors. I wrote: "A SARIF producer **MAY** choose to omit the hostname (authority) from a file URI, for example, for security reasons. If it does so, then to maximize interoperability with previous version of the URI specification, the URI **SHOULD** start with `"file:///"`, as in EXAMPLE 2. See [RFC8089] for more information on this point." |
| §3.4.3 | Mention that these are also UUIDs.  RFC4122 calls them UUID first, GUID second. "form of a GUID [RFC4122]." -> "form of a GUID or UUID [RFC4122].  This document will use the term GUID.' | Thanks for not asking us to take the breaking change of using UUID throughout! |
| §3.9.5 | "the backslash SHALL be doubled." -> "the backslash is doubled by JSON encoding." | In the spirit of separating out the JSON-dependence (or at least, making it explicit), I removed the entire sentence and added a NOTE: "When a SARIF log file is serialized as JSON, JSON encoding doubles the backslash." | 
| §3.11.14 | In the example, add properly indent `"namespaceA::namespaceB"'` | |
| §3.11.12 | example: Error in example JSON "originalBaseIds" -> "originalUriBaseIds" | |
| §3.19.6 | I don't understand the reason for converter SHOULD NOT synthesize the ruleId.  They SHOULD NOT if they cannot do so in a consistent manner, but why not otherwise. | I added a NOTE to explain. Only a tool vendor can assign a rule id. If a converter author could do it, then two different converter authors might synthesize different rule ids, leading to loss of interoperability (for example, a consumer might wrongly conclude that two issues were logically distinct because they had different rule ids). |
| §3.19.13 | example 1: There is an extra space in the value of wordHash property (" 2c26...") | Not only that, but that example should actually have been "Example 3" (there are two previous examples in the same section), and the next one should have been "4" instead of "2" 😃 |
| §3.19.23 | There is a comma missing after '"endLine": 13' and an extra comma after '</problem>",' |
| §3.24.5 | Add that this is also called a mangled name as some users may be more familiar with terminology. | I added the sentence: "Some compilers refer to this representation as a “mangled name.”" |
| §3.26.4 | "the order that the tool visited them." to "the execution order that demonstrates the weakness."  The tools visitation order is not defined and is not important, the execution order is. | Good catch. I had assumed that the tool visits the locations in execution order, but who knows? It's one of those "as if" things. |
| §3.34.7 | "each of whose properties represents the value of an expression" is better worded as "where each property name and value pair represents an expression and it value respectively" | The existing text goes on to say "... the value of an expression _relevant to the location_...", which is hard to express in your formulation. I'm going with "in which each property name represents an expression relevant to the location in the context of the code flow, and the corresponding property value specifies the value of that expression." |
| §3.34.7 | The example 3 caption "In C++, a property value" would be clearer as "In C++, a JSON encoded property value" | Rather than changing the caption, I changed the parenthetical to this: "(the double quotes are escaped as the would be in a JSON serialization; other serializations might represent the double quotes differently)" |
| §3.36.8 | Aren't the richMessageStings keys contrained, so "set of properties with arbitrary names." could be "set of property names where the names are a subset of the messageString property names." | The spec already says that "SARIF consumers that cannot render rich text **SHALL** ignore the `richMessageStrings` property and use the `messageStrings` property instead. For this reason, every property name that appears in the `richMessageStrings` property **SHALL** also appear in the `messageStrings` property." But I like your idea of stating the restriction up front. |
| §3.37 | Why does this talk about future scans instead of the configuration during the run? | The text does not include the words “future scans”. I assume you are referring to this passage in the description of the runConfiguration.enabled property: "A `ruleConfiguration` object **MAY** contain a property named `enabled` whose value is a Boolean that specifies whether the rule _**will be**_ evaluated during the scan." You’re right. I changed it to “_**was**_ evaluated”, because yes, by the time you see the log file, it’s already happened. I made the mistake of using future tense here because I gave an example of how to specify this property on the command line – and at that point, the scan hasn’t happened yet. |
| §3.40.1 | After "start at byte 22", adding " of the file contents after applying the first file change." would make this clearer. | Nice clarification. |
| §3.40.4 | If the inserted data is text, it must be encoded in the file's encoding before insertion. | Good catch. I stated that, then added a NOTE saying that this implies that you can't safely apply a text fix unless you know the target file's encoding. |
| §3.41.2 | Need guidance on "do need to be either stable or opaque" (the word "do" could be removed).  when should it be stable, opaque, or both. | This was a typo. The spec should have said: "NOTE: In contrast to rule identifiers (see `rule.id`, §3.36.3), which must be stable and opaque, notification identifiers do _**not**_ need to be either stable or opaque, because the reasoning that leads to those requirements for rule ids does not apply to tool notifications.” (emphasis added here but not in the spec) |
| §4.1 | No definition for "SARIF log file" and all others listed have one | |

### Changes that had already been made

| Section | Change | Comment |
| --- | --- | --- |
| §2.3 | "consists of a set of properties" -> "is a set of name/value pairs. This calls a name/value pair a property "defined property name and property value? | The spec used to say "A JSON object consists of a set of properties..." which is indeed inconsistent with JSON terminology. But the spec now separates the notion of a SARIF object model from its serialization, so now it says "A SARIF object consists of a set of properties..." which is fine. |
| §3.22.2 | For the end of a text region make it SHALL include charLength if the start is only specified by charOffset. | This is moot because the line/column properties and the offset/length properties are now completely independent -- in the sense that (1) if _any_ line/column properties are present, they must completely specify the region on their own, (2) if _any_ offset/length properties are present, they must completely specify the region on their own, and (3) if _both_ line/column properties and offset/length properties are present, they must independently specify the same region. |
| §3.22.2 | I think that it would better if the end line/column were only computed as if charLength were not set, this should put no burden on producers other than to not be strange. | Yes, that's what the spec now says, now that the line/column and offset/length properties are independent and required to be consistent ("not strange", as you said). |
| §3.22.2 | example 4: the first line of example 4's caption is formatted as example body | Fixed when I rewrote the whole `region` section. |
| §3.22.2 | example 6: extra space before column in line 3 | The reworked example doesn't have that problem (but I did find and fix a missing comma in another example in this section). |
| §3.22.5 to §3.22.9 | Not referring to Section 3.22.2, but describing how to compute the value would be useful. | The rewritten `region` section doesn't have this problem; the defaults are simpler and are given inline in the section describing each property. |
| §3.22.11 | Is it the case that byteOffset MAY be present in text regions and must refer to the same bytes as described by the text region? | Yes. A single `region` object can contain properties that describe a text region, properties that define a binary region, or both, and if both are present, they must be consistent. |
| §3.35.2 | What is the reason for "SHALL NOT appear both as the value of a messageId property and the value of richMessageId ..." | When I wrote this, `rule.messageStrings` contained both plain text and rich text message strings. So you had to worry about the case where a `message` object might have its `messageId` and `richMessageId` properties both set to some value (say, `"default"`) – and the same entry in `rule.messageStrings` would be expected to be both a plain text string and a rich text string. In the current draft, the `rule` object has separate `messageStrings` and `richMessageStrings` properties, so this constraint is unnecessary and no longer appears in the spec. |

### Changes tracked in separate issues
| Section | Change | Issue | Comment |
| --- | --- | --- | --- |
| | There is no mechanism for tools to report computed values or properties of a program such as code metrics. | Existing issue #44, "Consider: adding support for metrics" | Non-editorial |
| | If a tool is invoked multiple times to analyze a package, this is logically one run, but there is not a mechanism to relate a result to an invocation. | New issue #285: Provide a mechanism to associate a result with an invocation | Non-editorial |
| §3.24.6 | Add "class" to handle C++'s "class".  Without it, "module" seems like the closest fit.  There is current work on a module system for C++, I do know any more. | New issue #279: "Add "class" to logicalLocation.kind" | Non-editorial |

### Changes I did not make

| Section | Change | Comment |
| --- | --- | --- |
|   | All examples should be numbered. | ISO says that if there's only one EXAMPLE or NOTE in any given numbered section, then you don't number them; if there's more than one, then you do. That's what I've done. Sometimes when I split or join sections, I might neglect to fix that up. Let me know if you see examples in the current draft. |
| §1.2 | Definition of log file: "log file" -> "result file" more specific | I don't see a need for this. Besides, a "log file" contains more than just results (files, resources, tool definition, invocation information, notifications, and so much more). |
| §1.2 | Definition of problem: "problem" -> "weakness" as it is a more common term in the security field | SARIF applies to much more than security. A failure to conform to a coding standard is a "problem" but in no way a "weakness". |
| §1.2 | Definition of property: Property is not defined in JSON spec [ECMA404]. It uses name/value. | Actually the spec didn't define "property" at all, so I defined it ("attribute of an object consisting of a name and a value associated with the name"). SARIF is not fundamentally tied to JSON (JSON is just one possible serialization), so I have no problem with the term "property." This is all much clearer in the current draft than it was in the CSD.1 draft you commented on; I've taken pains to separate the object model from the serialization, although the separation is still not perfect.  |
| §1.2 | Definition of (static analysis) tool: Why parentheses?  Define "static analysis tool" and "tool" | In ISO, the parentheses mean that you can refer to the term either with or without the parenthesized portion; that is, "static analysis tool" and "tool" are the same. There is no confusion with "conversion tool" because we never call it that; we always call it a "converter". |
| §3.3.1 | "can sometimes":  why sometimes?  Maybe state that the baseUriId can be used to further resolve the URI, and to an absolute URI if the baseUriId is defined to be an absolute URI. | "can sometimes" because you might not have _any_ information about the location that `uriBaseId` should resolve to. The description of the `uriBaseId` property explains how consumers can attempt to resolve `uriBaseId`, but they won't always succeed. |
| §3.13.4 | Need guidance on when to use responseFiles vs attachments, why not just use attachments as there is already a role property to distinguish? | I don't think additional guidance is needed. The spec defines "response file" as "file containing arguments for a tool, which are interpreted as if they had appeared directly on the command line". It has much more specific semantics than attachment. And there is a `roles` value for `responseFile` as well. |
| §3.36.6 | How is the first sentence defined?  Just require shortDescription | The first paragraph of the section explains how "sentences" are delimited: "A plain text message SHOULD be expressed as a single paragraph of plain text, consisting of one or more complete sentences, each ending with a period (or appropriate punctuation for the language in which the message is written)." |
| Appendix D | I don't understand why a converter should not try to synthesize values and how this adds complexity.  If it can do so consistently and reliably, this seems like a good thing.  Leaving it to the viewer means that every viewer needs to be able to do this. | The complexity comes because either (1) the converter might be versioned, changing its synthesis behavior from version to version, or (2) converters from different authors might synthesize differently. This means that a SARIF consumer must be sensitive not only to the version of the original analysis tool, but also to the version of the converter. The viewer does not need to do anything. If a property is missing, the viewer doesn't display it or draw any conclusions about it (except possibly to use its default value if the spec defines one). |

**Comment by michaelcfanning** [comment]
great feedback from the great state of wisconsin and a very detailed response to it.

my only comment is a nit around 1.1. I like the clarification of 'most specific' in preference of (and addition to rightmost. But isn't the design that this value is always and not mostly rightmost?

**Comment by lgolding** [comment]
Thanks Michael. As I mentioned in email yesterday, there are still a few dozen editorial changes that I haven't yet addressed. I don't know if I'll add them here, or open a separate issue so you can easily identify the next batch.

**Comment by lgolding** [comment]
@michaelcfanning @kupsch I will open a new issue for the next batch of Jim's editorial issues. That will make it easy for you to see the new changes, rather than having them mixed into the long table in this issue.
