### ISSUE TITLE
Represent exceptions in code flows

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#28]
Copied from https://github.com/sarif-standard/sarif-spec/issues/265, created by @lgolding:

Enable SARIF to represent exceptions in code flows, perhaps by introducing new values for `annotatedCodeLocation.kind`. Take into account at least the following issues:
- An exception may be thrown implicitly (for example, a `ThreadAbortException`), without a `throw` statement appearing in the source code.
- An exception may be thrown explicitly.
- An exception may be typed (_e.g._, `throw new Blah()`) and the thrown object may be parameterized (_e.g._ ,`throw new Blah(42)`).
- An exception may satisfy an exception filter.
- An exception may be caught by a `catch` clause.
- An exception may be rethrown (bare `throw` statement in a `catch` clause).
- An exception may cause program termination (for example, if thrown from a C++ destructor).
- A `finally` clause may execute as control leaves a function which did not catch an exception (or, for that matter, if the function _did_ catch the exception).

**Comment by michaelcfanning** [comment]
We've decided not to expand code flow kinds to account for new domains such as this, so closing this item.
