### ISSUE TITLE
result.message SHALL be present constraint should be added to schema

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#283]
Somehow we appear to have lost the schema constraint that result.message is required. The spec still makes this sensible condition clear.

**Comment by lgolding** [comment]
@michaelcfanning Both the spec and the schema are correct. The spec says that _either_ `message` must be present (if the log specifies its messages "inline"), _or_ `ruleMessageId` must be present (if the log just provides a resource identifier together that locates the message string), or both.

Now even if the log file specifies a message indirectly _via_ `ruleMessageId`, you still need `message` if the resource string has any replacement sequences `{n}` that need to be filled from `message.arguments`. But if the resource string has no replacement sequences, you don't need `message` at all.

So the schema can't require `message`.

**Comment by lgolding** [comment]
This is actually a bug that crept in when we _removed_ `result.ruleMessageId`. Before then, `result.message` could not be required, for the reason I stated above. But now, `message` is required because even a _rule's_ message id is now stored in `result.message.messageId`, not in a separate `result.ruleMessageId`.

(The point being, this schema constraint wasn't "dropped"; it was never there. But now it can and should be there.)

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Right. I your the reference entirely to a property that we removed. 

Great. I can't help but think that our ability to add 'message' as a required property in the schema reflects that the design has improved slightly.

**Comment by lgolding** [comment]
This is purely a schema change so no change draft is needed. I'll put it on the agenda to approve it.

**Comment by michaelcfanning** [comment]
The spec is correct and we should cover this explicitly in the editor's report. I don't see a need to require TC approval on this, however, we simply need to report out on the schema bug.

**Comment by michaelcfanning** [comment]
Updated the schema. Notification and result now both mark 'message' as a required property. @lgolding FYI

**Comment by lgolding** [comment]
The schema correctly says that `result.message` is required.
