### ISSUE TITLE
Provide a mechanism to associate a result with an invocation.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#285]
Suggested by @kupsch, who wrote:

> If a tool is invoked multiple times to analyze a package, this is logically one run, but there is not a mechanism to relate a result to an invocation.

**Comment by michaelcfanning** [comment]
Section 3.38.1. In general, there are four key players in the format, 1) a tool, 2) infrastructure that deploys/configures/executes and captures output of a tool, 3) users who are examining tool output, 4) infrastructure that manages run-over-run tool outputs and the end-to-end disposition of results.

associating a result with an invocation is useful to players 2, 3, and 4 above. a tool runner might want to understand the specific invocation of a tool that produced a specific result (for example, if the rule behind the result shouldn't have been configured to run at all. a dev lead reviewing results might want to know how long an issue has been lingering in code. a results mgmt. system will be responsible for producing/maintaining this value.

all of which is to say that the note in 3.38.1 is thin now that we're expanding the contents of the provenance object.

**Comment by michaelcfanning** [comment]
3.38.6

Consider this case: an invocations array exists, it is populated with a single invocation instance, no result is decorated with an invocationIndex. In this case, common sense tells us that the result is associated with the only existing invocation. But the format seems to explicitly forbid reaching this conclusion by specifying a default value for invocationIndex that is not a valid array index.

What are your thoughts on this?

**Comment by lgolding** [comment]
Thanks for the feedback.

**Issue 1**: I rewrote §3.38.1 to read:

> A `resultProvenance` object contains information about how and when its containing result was detected.
>
> NOTE: This information is useful to various human and automated participants in an engineering system. For example:
> - A build engineer might use the information to understand the specific tool invocation that produced the result, for example, if the violated rule should not have been configured to run at all.
> - A developer reviewing results might use the information to determine how long an issue has existed in the code.
> - A result management system might be responsible for associating logically identical results from one run to the next, making it possible for the developer to determine how long the result has existed.


**Issue 2**: I'll yield on this. In general, to reduce the burden on implementers, I have tried to avoid complex defaulting logic. It's the same reason I argued against a default for `resultProvenance.lastDetectionTimeUtc` in #287, and it's one of the reasons our `region` redesign was so good: it removed lots of complex defaulting logic.

But as I say, I'll yield this point. §3.38.6 now says:

> If `invocationIndex` is absent and `run.invocations` is present and contains a single element, it **SHALL** default to 0; otherwise it **SHALL** default to -1 (which is otherwise not a valid value for this property).
>
> NOTE: This provides a sensible default in the common case where there is only a single tool invocation in the run.


**Issue 3**: Good catch. Actually I had hung it off a `codeFlow` object. Now I provide a complete `resultProvenance` object (whose "`last`" properties match the corresponding properties of the current run), and correctly hang it off the `result` object:

```
  "resultProvenance": {
    "firstDetectionTimeUtc": "2016-07-15T14:20:42Z",
    "firstDetectionRunInstanceGuid": "8F62D8A0-C14F-4516-9959-1A663BA6FB99",
    "lastDetectionTimeUtc": "2016-07-16T14:20:42Z",
    "lastDetectionRunInstanceGuid": "BC650830-A9FE-44CB-8818-AD6C387279A0",
    "invocationIndex": 0
  }
```
