### ISSUE TITLE
Consider making log.version placement as first property a SHALL

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#289]
I understand that we generally do not want to enforce strict requirements without a good reason and not in cases where it puts unwanted limits on how SARIF is produced or consumed. 

The presence of log.version as the first property is very helpful for consumers as it prevents a complete additional parse of file contents in the case where a producers has placed the version at the end of the file.

Making the placement of version as first property a SHALL would be a helpful guarantee for consumers. I can't see where tightening this requirement would place a burden on producers. I can't think of a case where a producer would be writing contents and it is useful to delay writing the version.

**Comment by michaelcfanning** [comment]
@lgolding, this seems like another small one we could try to tackle before tomorrow's TC, contingent on your availability.

**Comment by lgolding** [comment]
I don't think we can make it **SHALL**. It requires the producer's JSON library to allow you to specify property order.

Newtonsoft.Json [can do it](https://www.newtonsoft.com/json/help/html/JsonPropertyOrder.htm):
```
    // appear first
    [JsonProperty(Order = -2)]
```

but others might not. **SHOULD** means "do it unless you have a good reason not to", and IMO "my JSON serializer can't do it" would be a good enough reason.

Thoughts?

**Comment by michaelcfanning** [comment]
Good point. I think you're absolutely right. This SHALL would clearly be a burden on producers if it required them to stop using a library that doesn't allow for deterministic serialization order. Please feel free to close this issue once you read this. :)
