### ISSUE TITLE
Introduce object-valued rule.configuration

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#29]
Copied from https://github.com/sarif-standard/sarif-spec/issues/266, created by @lgolding:

`"enabled"`, `"disabled"`, or `"unknown"`. Default: `"unknown"`.

If any rule has `"enabled"` or `"disabled"`, all rules must be mentioned, and all rules must be specified as either `"enabled"` or `"disabled"` (a smart validator can enforce the latter).

@michaelcfanning FYI

**Comment by lgolding** [comment]
Comment from @michaelcfanning:

This has been added to the SDK.

**Comment by michaelcfanning** [comment]
@lgolding this looks like something missing from the spec that should already have been added? I don't see it in the old spec. Looks like an oversight.

**Comment by michaelcfanning** [comment]
This item definitely exists in schema and SDK

    public enum RuleConfiguration
    {
        Unknown,
        Enabled,
        Disabled
    }

**Comment by michaelcfanning** [comment]
Create a configuration object. move defaultLevel into this configuration object. Create a Boolean 'enabled' to add to this object.
