### ISSUE TITLE
Update logical location kinds to accommodate XML and JSON paths

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#291]
'kind' for results grouping, XML and JSON domains, and can we find a magical general term that absorbs function/member

**Comment by michaelcfanning** [comment]
Received some feedback from a team implementing a JSON-driven analysis

* Some assistance with logical locations would be useful
* In this scenario, the leaf node is not super interesting, the parent objects are what's interesting. Our design currently requires that a logicalIndex point into the detail object. 
* The scan team has two paths, one is qualified by actual array indices, e.g., object[5].property. They have another, more 'stable' form where they elide the actual index, e.g., object[].property. This data removal is analogous to eliding line location details (where document churn might invalidate them).

**Comment by lgolding** [comment]
JSON: Object, Array, Property, Value,

XML: Element, Text, Attribute, Comment, Declaration, Dtd, ProcessingInstruction

**Comment by kupsch** [comment]
Have to state how to represent a dtd in the logical location as it appears that there is not an XPath representation for the DTD.  Perhaps /!DOCTYPE

**Comment by kupsch** [comment]
To make it clear, it should be noted that the line number are not part of the text. The line number could also be stylized differently such as color.

**Comment by kupsch** [comment]
In the JSON example there are a couple of errors in the SARIF data:

`results/0/locations/0/fullQualifiedLogicalName` should be **"/orders/0/productIds/1"**
`results/0/locations/0/logicalLocationIndex` should be **3**
`results/1/locations/0/logicalLocationIndex` should be **4**

**Comment by lgolding** [comment]
@kupsch Thanks Jim. I noted those changes in [this comment](https://github.com/oasis-tcs/sarif-spec/issues/342#issuecomment-474054209) in #342, and will fix it up after the ballot ends.

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
