### ISSUE TITLE
Specify a default for result.rank

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#292]
We can either specify a numeric default (0? 50? 100?) or not. If we don’t, then at the _format_ level, the _absence_ of the property signifies “unknown”. The _SDK_ can translate “absent” to “-1.0”.

Marked "bug" because it was a mistake for us not to consider whether a default was needed.

**Comment by michaelcfanning** [comment]
It is not reasonable to propose a default. The absence of the property should signify unknown. SDKs can translate this specification into a nullable type or use some sentinel value as you say that falls outside the valid range. This behavior doesn't need to be specified, of course, SDKs can handle this in many ways.

**Comment by michaelcfanning** [comment]
OK, let's think about this. First, I don't think it makes sense to propose a default other than 0.0. This is the 'safest' thing to do in the sense that we assume everything which is not annotated is fundamentally less interesting than any results which are annotated. A default within the range doesn't make sense, as this value is strictly owned by the tool (and we don't know what a value of 50.0 means). 0.0, on the other hand is very clearly defined: it is the least priority that can be assigned to a result.

As far as whether 'absent' is something that an SDK should broadcast, we have to go through our typical thinking exercise: if we take on the complexity of making this distinction, we should have a clear sense of the different action a consumer might take for an entirely unranked thing as opposed to something which is, say, ranked as 0.0.

I personally don't see a good distinction here, so my current opinion is that the default value s/be 0.0. 

If others argue for an explicit mechanism for specifying 'absent', we need to address the problem of whether it is legal to mix results with some explicitly specified ranks and failing to annotate others completely. With a default value of 0.0, this problem goes away.

**Comment by lgolding** [comment]
@michaelcfanning I don't think the spec should define any default value (and an SDK can translate a missing value to "-1.0", as we've done in the past).

Defining the default to be 0.0 means that the consumer can't tell the difference between "I've looked at this issue and it's utterly unimportant" and "I haven't looked at this issue."

**Comment by lgolding** [comment]
@michaelcfanning Well actually, there's nothing wrong with the _spec_ defining the default to be -1.0 -- _that's_ actually what we've done in the past.
