### ISSUE TITLE
Add run.scope

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#294]
For compliance purposes, it is often important to demonstrate that you have analyed every entity under some "scope". Here are three examples:

1. A tool analyzes the set of records returned from a specified database query. The query is the scope.
2. A tool analyzes the set of files that match a wildcard specification such as `"src\**\*.cs"` (the set of all C# files found recursively under the `src` directory). The wildcard is the scope.
3. A tool analyzes the set of HTML pages found by crawling a root URL such as `"https://www.example.com"`. The root URL is the scope.

In none of these cases is it possible (in general) to deduce the scope by examining the set of analysis targets mentioned in the log file. There needs to be a place in SARIF to state the scope explicitly.

The difficulty is in defining something that can capture the full generality of the types of scope you might encounter. The three examples above illustrate the difficulty. Even confining ourselves to <span>#</span>2 (a wildcard specification), we'd find ourselves in the business of specifying a wildcard syntax.

One possible way out is to focus on the _purpose_ of stating the scope: to claim compliance with some policy in a particular engineering system. From that point of view, a property `run.scope` of type `string[]` -- an array of arbitrary strings -- might suffice. The engineering system presumably knows what scopes it requires for compliance.

**Comment by lgolding** [comment]
@michaelcfanning mentions source code archives, UNC shares, tar/other archives, and NuGet packages as other possible examples of the "scope" concept.

**Comment by michaelcfanning** [comment]
TC recommends closing.
