### ISSUE TITLE
Move conversionProvenance under result.provenance

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#297]
- Rename `result.resultProvenance` to `result.provenance`.
- Move `result.conversionProvenance` (the array of `physicalLocation` that points to the source locations of the result in the native log files) into `result.provenance.conversionSources`.

@michaelcfanning FYI.

**Comment by michaelcfanning** [comment]
A gentle collapsing.

**Comment by lgolding** [comment]
Summary: Instead of
```
result
  resultProvenance:resultProvenance
  conversionProvenance:physicalLocation[]

resultProvenance
  detection time related properties
  invocationIndex:int
```
we have
```
result
  provenance:resultProvenance

resultProvenance
  detection time related properties
  invocationIndex:int
  conversionSources:physicalLocation[]
```

So all the "where did this come from" information is in one property.
