### ISSUE TITLE
Constraints on locations

### ISSUE THREAD

**Issue by AaronBallman** [oasis-tcs/sarif-spec#299]
The location object got a new set of constraints (3.23.2) in the 11-28 revision that say:

> At least one of the fullyQualifiedLogicalName property (§3.22.4) or
> the logicalLocationIndex property (§3.22.5) SHALL be present; they MAY
> both be present.

I read this as saying that a location object must have logical location information (because at least one SHALL be present), which I don't think is correct. I think the logical location information should remain optional, as not all analyzers have easy access to that information.

**Comment by lgolding** [comment]
@AaronBallman I fixed this by prefacing that sentence with:

> If a `location` object specifies logical location information, ...

**Comment by AaronBallman** [comment]
Perfect, thank you!
