### ISSUE TITLE
file.fileLocation.uriBaseId and file.parentIndex are mutually exclusive

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#305]
This would make a good validation rule.

Any file location that populates file.parentIndex is an item stored within a container. It is therefore not a candidate to utilize a uriBaseId (which is exclusively used to provide path information as part of a physical, not logical location).

So basically, file.parentIndex or file.fileLocation.uriBaseId may be present but not both. A uriBaseId does not make sense for referring to a location within, for example, a zip archive. There is no path non-determinism in that case.

**Comment by michaelcfanning** [comment]
@lgolding, validation suggestion for you

**Comment by lgolding** [comment]
I'll write a change draft for this. I consider it editorial, since one can (as you did) infer it from the existing text. This is just for the sake of explicitness.

**Comment by lgolding** [comment]
@michaelcfanning As I said in email, the sections on `file.parentIndex` and `fileLocation.uriBaseId` are already explicit:

- You can't use `parentIndex` on a top-level file.
- You can't use `uriBaseId` on a nested file.

I don't see a reason to add a sentence somewhere to that effect that "... so you can't use them together."
