### ISSUE TITLE
originalUriBaseId object's values are directory locations not file locations

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#306]
The values pointed to in a originalUriBaseId dictionary are exclusively directories. Elsewhere in the format, a file location exclusively points to a discrete file (sometimes embedded in another file, of course).

A uriBaseId by definition always points to a directory. What we should have done (in order to handle uriBaseId nesting to assist with things like git submodules) is define a directoryLocation type (which has the same members as fileLocation).

Please note the description of a file location from our schema. I noted this problem on attempting to update the C# SARIF SDK. Significant processing in the SDK is now broken when doing things like visiting all log file locations (because some, in fact, are directories).

We've discussed the possibility of the files table storing directories before (perhaps by adding a new directory 'role' to the file object. This would require making fileLocation very generic (with a path component and a uriBaseId), though. 

Unless/until we design something in a more comprehensive way, we should define a directoryLocation object and use this schema type for originalUriBaseIds.

@lgolding, easy change to develop for next TC discussion.

    "fileLocation": {
      "description": "Specifies the location of a file.",

**Comment by lgolding** [comment]
Let me take this one step at a time:

1. Yes, the `fileLocation` objects in `originalUriBaseId` are exclusively directories.

2. Yes, that conflicts with the schema's description of `fileLocation` ("Specifies the location of a file"). To be hypertechnical, the spec defines "file" as "sequence of bytes addressable _via_ by a URI," so you could take it to include directories. "Ah!", you say, "but you can't read the bytes from a directory." "Fine!," I reply, "so change the spec's definition to "resource addressable _via_ a URI." and all is well. "That's very clever," you say, "but a human being reading that schema definition will be confused." "Ok," I concede, "then change the spec definition as I suggested, and change the schema description of `fileLocation` to "Specifies the location of a URI-addressable resource."

2. Yes, for the most part, other `fileLocation` objects specify "files".

3. I do think it's possible for a `result.location` to specify a directory. For example, consider the rule "The `resources` directory must contain an `en-US` subdirectory" or "The `docs` directory must not be empty."

4. Even if every other `fileLocation` really is a file, I don't see why a new value `"directory"` for `file.roles` doesn't solve the problem. You wrote:

> This would require making `fileLocation` very generic (with a path component and a `uriBaseId`), though.

Could you clarify? Why would the existing `fileLocation` (consisting of a `uri` and a `uriBaseId`), when it occurs in a `file` object with the `"directory"` role, not meet your needs?

**Comment by lgolding** [comment]
While I'm at it, could you describe the scenario where something breaks in the SDK because you can't figure out that a `fileLocation` actually specifies a directory?

**Comment by michaelcfanning** [comment]
The scenario is a post-processing step that attempts to construct file data objects from references in the log file. Currently, we visit all file info objects and attempt to process these. Some processing requires loading the bytes. Other processing examines the reference only (to infer mime type).

All this code needs special-casing in order not to add erroneous entries for the original uri base id objects. Obviously, we can provide this special-casing.

Of course it's possible for a result.location to specify a directory. However, no tool in the SARIF eco-system does today, which is why we've never been prompted to settle the 'directories in files table'. I personally don't prioritize this speculative value highly unless/until someone points to a use case (at which point I will definitely be open to it). 

I'm not sure what attributes of a directory would warrant a static analysis result, though. Static analysis tools operate against code representations in the main. A directory is an artifact of a machine/other execution environment. I am not aware of any scanners that examine this data and inject problem reports into engineering workflow. 

This sort of analysis seems much more in line with operating system background scanners and other environment scanners (such as Qualys) that operate via agents on machines or which scan endpoints.

**Comment by lgolding** [comment]
Ok, I understand your scenario. And I agree that "analyzing directories" is not a high priority (but if we had a design that enabled it "for free", that would be a fine thing).

So that leaves my last question from the my [comment above](https://github.com/oasis-tcs/sarif-spec/issues/306#issuecomment-451769174):

> Even if every other `fileLocation` really is a file, I don't see why a new value `"directory"` for `file.roles` doesn't solve the problem. You wrote:

>> This would require making `fileLocation` very generic (with a path component and a `uriBaseId`), though.

> Could you clarify? Why would the existing `fileLocation` (consisting of a `uri` and a `uriBaseId`), when it occurs in a `file` object with the `"directory"` role, not meet your needs?

**Comment by michaelcfanning** [comment]
sorry it wasn't clear from my post, we can't use a files table 'directory' role to solve my scenario, because the scenario that uncovered this problem relates to processing log files that don't have a files table. i.e., the post-processing at hand is to populate this table. during that processing, we currently simply visit over every file location in the format. with the introduction of originalUriBaseIds, this is no longer possible, because we have introduced some file locations that point to directories. 

we don't embed file directories in the files table. neither do we compute their mime types. etc. 

the heuristics around determining whether a uri is a directory are only that, heuristics. they are probably fine to use, but it's too bad, because we know exactly where all the directories are today in the format: in the originalUriBaseIds object.

again, we can take an SDK change that simplifies things. we can maintain a stack of node kind, for example, so that when we visit a file location as part of examining a originalUriBaseIds object, we can know that (and not treat the file location as a file location).

**Comment by lgolding** [comment]
@michaelcfanning Per our long discussion yesterday: We will define a `directoryLocation` that contains `uri` and `uriBaseId`, just like `fileLocation`, but with no "index" property (because we don't have a `run.directories` array, at least not yet), and with the constraint that `uri` must specify a director, not a file.

**Comment by lgolding** [comment]
@michaelcfanning The change draft is ready. Per our design (introducing a `directoryLocation` object), this is a breaking change, not an editorial change, so I changed the issue labels.

**Comment by michaelcfanning** [comment]
Proposal was rejected by the TC

**Comment by lgolding** [comment]
One of the reasons was that two TC members (@lgolding, @kupsch) were reluctant to adopt a design that prevented a tool such as a web app scanner from specifying a directory as the result location (_e.g._, "Directory 'bin' is empty".
