### ISSUE TITLE
Rename run.files to run.artifacts, fileLocation to artifactLocation

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#309]
I am working with an internal team at MS that is utilizing SARIF for a set of services that provide scanning and scan results. This system operates exclusively against streams, there is nothing in the way of a file system that's involved.

SARIF is used as a kind of message envelope in this system: the team populates it with various SARIF values that the automation system knows about, such as correlation guids, instance ids, etc. The files table is used to specify scan stream targets. In some cases, these streams are downloaded. In other cases, the URIs are provided simply to use as identifiers in results (the request itself contains the scan streams to analyze).

Feedback from this team is that it is strange to constantly populate run.files and fileLocation instances for this scenario. Their suggestion was to make this more general, such as using 'artifact' as an alternate term.

I think we do aspire to have a format that works well in a services environment (this is a primary reason we chose JSON as a format). I'd be fine with this change.

@lgolding

**Comment by michaelcfanning** [comment]
TC approves the change.

**Comment by lgolding** [comment]
The full set of renames pursuant to this issue is:

- Rename the `file` object to `artifact`.

- In the renamed `artifact` object:

    - Rename the `fileLocation` property to `artifactLocation`.
    - Rename the following values for the `roles` property:
        - `unmodifiedFile` &rarr; `unmodified`.
        - `modifiedFile` &rarr; `modified`.
        - `addedFile` &rarr; `added`.
        - `deletedFile` &rarr; `deleted`.
        - `renamedFile` &rarr; `renamed`.
        - `uncontrolledFile` &rarr; `uncontrolled`.


- Rename the `fileLocation` object to `artifactLocation`.

- In the renamed `artifactLocation` object:

    - Rename the `fileIndex` property to `artifactIndex`.

- Rename the `fileContent` object to `artifactContent`.

- Rename the `fileChange` object to `artifactChange`.

- In the renamed `artifactChange` object:

    - Rename the `fileLocation` property to `artifactLocation`.

- In the `fix` object:

    - Rename the `fileChanges` property to `artifactChanges`.

- In the `physicalLocation` object:

    - Rename the `fileLocation` property to `artifactLocation`.

- In the `run` object:

    - Rename the `files` property to `artifacts`.
    - Rename the `defaultFileEncoding` property to `defaultEncoding`.

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
