### ISSUE TITLE
Register SARIF MIME type with IANA

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#31]
Copied from https://github.com/sarif-standard/sarif-spec/issues/268, created by @lgolding:

Possibly `application/sarif+json`.

@michaelcfanning FYI.

**Comment by lgolding** [comment]
Not actually a spec issue, will do later.

**Comment by robincover** [comment]
Larry, let's discuss offline your comment "Not actually a spec issue..." -r
