### ISSUE TITLE
Consider splitting resultlevel into result.level and result.kind

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#317]
Starting proposal:

resultKind -> open, review, not applicable, pass, fail

messageLevel -> note, warning, error

This allows us to converge notification and result levels so, hence, message level.

**Comment by michaelcfanning** [comment]
TC approves this change.

**Comment by michaelcfanning** [comment]
@lgolding, schema change is ready for this. is it ok to mark these as 'to-be;written'?

**Comment by lgolding** [comment]
@michaelcfanning Yes.

**Comment by michaelcfanning** [comment]
Update, we have added level.none and kind.debug.

**Comment by lgolding** [comment]
@michaelcfanning I emailed pushing back on `kind.debug`.

**Comment by lgolding** [comment]
Changes merged to provisional draft.
