### ISSUE TITLE
Converge all messages into a common format strings object

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#319]
rule.messages would be a dictionary from id to an object which contains various format strings, currently covering plaintext and markdown only (plaintext is required). In future, other formats could fill out this object.

**Comment by michaelcfanning** [comment]
'run.richTextMessageMimeType' renamed to 'run.markdownMessageMimeType'. 
'message.richText' renamed to 'message.markdown'. 
'message.richMessageId' deleted. 
Create 'multiformatMessageString' object, that holds plain text and markdown message format strings. 
'reportingDescriptor.messageStrings' is now a dictionary of these objects, keyed by message id. 
'reporting.Descriptor.richMessageStrings' dictionary is deleted.

**Comment by michaelcfanning** [comment]
This change has been accepted into the 01-24 schema + SDK

**Comment by lgolding** [comment]
#### E-BALLOT 3 PROPOSAL

- Define a `multiformatMessageString` object with the following properties:
    - `text` of type string, non-empty, required.
    - `markdown` of type string, non-empty, optional.
- In the `resource` object (it's still there because this is written before #325):
    - Change the type of the `messageStrings` property from `object` with `string`-valued properties to `object` with `multiformatMessageString`-valued properties.
- In the `rule` object (it's still there because this is written before #311):
    - Change the type of the `messageStrings` property from `object` with `string`-valued properties to `object` with `multiformatMessageString`-valued properties.
    - Change the type of the `help` property from `string` to `multiformatMessageString`.
    - Remove the `richMessageStrings` property.
    - Change the type of the `help` property from `message` to `multiformatMessageString`.
- In the `message` object:
    - Rename the `richText` property to `markdown`.
    - Remove the `richMessageId` property.
- In the `run` object:
    - Remove the `richMessageMimeType` property.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
