### ISSUE TITLE
"Properties" property missing from "run" object in schema

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#32]
Copied from https://github.com/sarif-standard/sarif-spec/issues/274, created by @mj1856:

Section [5.12.15](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20(SARIF).html#run-properties) describes a `Properties` property for the `run` object.  This doesn't exist in the JSON Schema.

However, the `run` object contains an `invocation` property, and there is a `Properties` property on *that* object that is described as `"Key/value pairs that provide additional information about the run."` in the schema description.  That one should probably say `"... about the invocation"`.

**Comment by lgolding** [comment]
Comment from @lgolding:

@michaelcfanning FYI

Hi @mj1856, I don't know how this slipped through the cracks. You are right on both counts. We will fix this. Thanks!

**Comment by michaelcfanning** [comment]
We should mark this issue as approved and have it signed off on by the TC this week.

**Comment by lgolding** [comment]
@michaelcfanning @mj1856

This is actually a bug in the schema, which is part of the sarif-sdk; the specification is correct. So I'm closing this bug and opening https://github.com/Microsoft/sarif-sdk/issues/631 to track this fix.
