### ISSUE TITLE
Provide a caching mechanism for duplicated code flow data

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#320]
**EBALLOT PROPOSAL**: provide a mechanism for caching thread flow location data, which is often copious and highly duplicative when producing complex code/dataflow static analysis results.

**API IMPACT**:
Add `run.threadFlowLocations`, an array of `threadFlowLocation` objects cached at the run level, analogous to `run.files` and `run.logicalLocation`.
Add `threadFlowLocation.index`, an index into `run.threadFlowLocations`.
Add `externalPropertyFiles.threadFlowLocations`, allowing cached data to be stored in a separate file.

**NOTES**:
A `result`-level `threadFlowLocation` object can specify properties of its own, and _also_ populate its `index` property. The behavior in this case is that the cached `threadFlowLocation` is used to initialize the local `threadFlowLocation`. Any local properties that diverge from the cached copy override the corresponding properties of the cached object. This allows producers to cache locations that share some common subset of properties while permitted the result-published locations to make minor updates to the cached version.

**Comment by michaelcfanning** [comment]
add run.threadFlowLocations
add threadFlowLocation.index property to index into for caching.
local threadFlowLocation will override cached values.
run.threadFlowLocations s/be externalizable

run.threadFlowLocations is a unique array with min of 0

**Comment by lgolding** [comment]
@michaelcfanning When you write "local threadFlowLocation will override cached values" do you mean that _individual properties_ on the local `threadFlowLocation` object would override corresponding properties on the cached object, but the cached object would continue to contribute all non-overridden properties. I think that's what we discussed, but I want it to be explicit for readers of the ballot.

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
