### ISSUE TITLE
Provide mechanism for inlining externalized properties data into the root log

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#321]
This required in order to accommodate sarifLog.taxonomies metadata, which will be a log level construct, as the data itself is entirely external to any tool execution (e.g., the CWE definitions).

The property names would be a JSON path to the construct which has been externalized.

@lgolding per discussion

**Comment by michaelcfanning** [comment]
Disposition: add a taxonomies property to the run object externalPropertyFiles object. Taxonomies is externalizable. Any externalized property reference can utilize the SARIF protocol to refer to data within the log file.

**Comment by kupsch** [comment]
Below is an example SARIF file, for my proposal to inline external data that can be shared between runs.  Add a new top level property whose value is an array of externalPropertyFile objects.  The sarif URI protocol is used to reference the location in the array.  Each run is unchanged except for the fileLocation of the external property, and the contents of the external file is unchanged.  There is no coupling of runs using this scheme, and file location in an external property file is always an externalPropertyFile object.

A further step would be to not require the externalPropertyFiles fileLocation in a run to change its fileLocation, but to inform consumers that if an inlineExternalFiles property exists with a matching instanceGuid then this is the externalPropertyFile object; this makes inline and externalizing simple.

```
{
  ...
  
  "inlineExternalFiles":  [
    {
      "$schema":
        "http:///json.schemastore.org/sarif-external-property-file-2.0.0",

      "version": "2.0.0",

      "instanceGuid": "22222222-2222-2222-2222-222222222222",

      "run.files": {
        "apple.png": {
          "mimeType": "image/png"
        },
        "banana.png": {
          "mimeType": "image/png"
        }
      }
    }
  ],

  "runs": [
    { 
      "originalUriBaseIds": {
        "INLINE": {
          "uri": "sarif:///inlineExternalPropertyFiles/"
        }
      },

      "externalPropertyFiles": {
        "files": [
          { 
            "fileLocation": {
              "baseUriId": "INLINE",
              "uri": "0",
              "fileIndex": 1
            },
            "instanceGuid": "22222222-2222-2222-2222-222222222222",
            "itemCount": 2
          }
      ]
    }
  ]
}

```

**Comment by lgolding** [comment]
Michael: did you capture any other changes than these?

 

Per discussion:

 

1.	Remove the “run.” prefix from the property names in an externalProperties object (section 4.3.6 of the spec).
2.	Use JPointer in the SARIF protocol (it’s designed to work with URIs).
3.	Accept Jim’s proposal with these renames:

 

{
  ...
  
  "inlineExternalProperties":  [
    {
      "$schema":
        "http:///json.schemastore.org/sarif-external-property-file-2.0.0 <http://json.schemastore.org/sarif-external-property-file-2.0.0> ",
 
      "version": "2.0.0",
 
      "instanceGuid": "22222222-2222-2222-2222-222222222222",
 
      "run.files": {
        "apple.png": {
          "mimeType": "image/png"
        },
        "banana.png": {
          "mimeType": "image/png"
        }
      }
    }
  ],
 
  "runs": [
    { 
      "originalUriBaseIds": {
        "INLINE": {
          "uri": "sarif:///inlineExternalProperties/"
        }
      },
 
      "externalPropertyLocators": {
        "files": [
          { 
            "fileLocation": {
              "baseUriId": "INLINE",
              "uri": "0",
              "fileIndex": 1
            },
            "instanceGuid": "22222222-2222-2222-2222-222222222222",
            "itemCount": 2
          }
      ]
    }
  ]
}

**Comment by michaelcfanning** [comment]
LGTM

**Comment by kupsch** [comment]
In 3.10.3, the sentence describing the sarif sheme ("Such a URI..."), would be more specific as:

> Such a URI uses the sarif scheme.  The sarif URI scheme consists of only a scheme (with the value sarif) and a path component.  The path component is interpreted as a JSON pointer [RFC6901] into the SARIF document containing the URI.  The authority, query and fragment URI components are forbidden.

**Comment by kupsch** [comment]
The sarif scheme should be registered with IANA.  If not on someone list of task already.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning 

Jim, I added your proposed text change to the punch list in #342. I opened #343, "Register the sarif scheme with IANA", labled `tracking-only` (although if we get it registered before we become a standard, I'll mention it in the spec).

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
