### ISSUE TITLE
Define a reportingDescriptorReference object

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#324]
**EBALLOT PROPOSAL**. Define a reporting descriptor reference object that allows notifications to point into reporting metadata that may be persisted to the driver or any of its extensions or to the new taxonomies metadata.

### API IMPACT
Schema only PR: https://github.com/Microsoft/sarif-sdk/pull/1316
- Create a `reportingDescriptorReference` type with these properties. 
    - `id` of type `string`: a notification identifier
    - `pointer` of type `string`: a JSON pointer that locates the descriptor for the notification with that identifier.
- In the `reportingConfigurationOverride` object:
    - Remove the `notificationIndex`, `ruleIndex`, and `extensionIndex` properties.
    - Replace them with a `reportingDescriptorReference` property of type `reportingDescriptorReference`, which specifies the `reportingDescriptor` whose configuration is being overridden.
- In the `notification` object:
    - Remove the `id` property.
    - Replace it with a `notificationDescriptorReference` property of type `reportingDescriptorReference`.
    - Remove the `ruleId` and `ruleIndex` properties.
    - Replace them with an `associatedRuleDescriptorReference` property of type `reportingDescriptorReference`, which locates the descriptor for the rule, if any, with which this notification is associated.
- In the `invocation` object:
    - Replace the property `reportingConfigurationOverrides` (which was defined to hold overrides for both rules and notifications) with separate properties `ruleConfigurationOverrides` and `notificationConfigurationOverrides`.
- In the `result` object
    - Remove the `ruleIndex` and `extensionIndex` properties.
    - Replace them with a `rulePointer` property of type `string`, containing a JSON pointer that locates the rule descriptor.

### EXAMPLE
```
{                            # A run object
  "tool": {
    "driver": {
      "name": "CodeScanner",
      "ruleDescriptors": [
        {                    # A reportingDescriptor object.
          "id": "CA2101",
          "name": "DoNotBeEvil",
          "shortDescription": {
            "text": "Do unto others as you would have them do unto you."
          },
          "messageStrings": {
            "default": {
              "text": "Evildoing was detected."
            }
          },
          "defaultConfiguration": {
            "level": "error"
          }
        }
      ],
      "notificationDescriptors": [
        {
          "id": "MSG0001",
          "name": "RuleDisabled",
          "shortDescription": {
            "text": "This notification occurs when a rule is disabled due to an exception."
          },
          "messageStrings": {
            "default": {
              "text": "Rule {0} has been disabled."
            }
          }
        }
      ]
    }
  },
  "results": [
    {                         # A result object.
      "id": "CA2101",
      "rulePointer":  "0"     # In this context, an abbreviation for "driver/ruleDescriptors/0"
      "message": {
        "messageId": "default"
      }
    }
  ],
  "invocations": [
    {
      "ruleConfigurationOverrides": [
        {
          "reportingDescriptorReference": {
            "id": "CA2101"
            "pointer": "0"     # In this context, ruleDescriptors are the default target
          },
          "configuration": {
            "level": "warning"
          }
        }
      ],
      "toolNotifications": [  # toolExecutionNotifications if #330 is approved
        {
          "notificationDescriptorReference": {
            "id": "MSG0001",
            "pointer": "0"    # In this context, an abbreviation for "driver/notificationDescriptors/0"
          },
          "associatedRuleDescriptorReference": {
            "id": "CA2101",
            "pointer": "0"    # In this context, an abbreviation for "driver/ruleDescriptors/0"
          }
          "message": {
            "messageId": "default",
            "arguments": [
              "CA2101"
            ]
          }
        }
      ]
    }
  ]
}
```
### NOTES
1. Certain JSON pointer-valued properties can be abbreviated, to optimize the most common cases:
- A JSON pointer that refers to a descriptor defined by the tool's driver can be abbreviated to a stringified integer value >=0 that will be treated as a relative reference into the driver's `ruleDescriptors` array or `notificationDescriptors` array, as appropriate. That is, if `notification.notificationDescriptorReference` is  `"driver/notificationDescriptors/42"`, it can be abbreviated to `"42"`, and if `notification.associatedRuleDescriptorReference` is `"driver/ruleDescriptors/54"`, it can be abbreviated to `"54"`.
 
2. We do _not_ replace `result.ruleId` and `result.rulePointer` with a `reportingDescriptorReference` in order to minimize churn in SARIF pre-release v2 producers.

3. `taxonomies` will also use this mechanism. That is covered in #314.

**Comment by michaelcfanning** [comment]
TC proposes to create a locator type with descriptor index and extension index only. id is excluded from the object for now.

**Comment by lgolding** [comment]
@michaelcfanning  I think id should be excluded because it's a "descriptor _identifier_" and so IMO should be decoupled from a "descriptor _locator_". I don't feel strongly about this, and my thinking wavers back and forth on it, but most of the time I come down on this side.

**Comment by michaelcfanning** [comment]
ruleIndex + extensionIndex pairs are replaced by a single property named rulePointer, which is a SARIF pointer with a special default relative value (that indexes into the driver toolComponent).
'''C#
reportingConfiguration.ruleIndex and reportingConfiguration.extensionIndex
result.ruleIndex and result.extensionIndex

**Comment by lgolding** [comment]
The proposal also includes some optimizations. For example, the `run.tool`-relative JSON pointer `"driver\ruleDescriptors\42"` could be abbreviated to just `"42"`, because most of the time, only a tool's driver will contribute metadata, and because rule metadata is so much more common than notification metadata.

@michaelcfanning In email, at your request, I proposed another few optimizations. Please add the ones you think appropriate to the e-ballot.

**Comment by michaelcfanning** [comment]
This issue also relates to #314, which proposes to define a reportingDescriptorReference object. This object will consist of an id and a pointer pair. It will be deployed everywhere in the format where an id + pointer pair occurs, except for the core "result" object, where we will retain the exiting property structure, in order to minimize late-breaking churn. @lgolding, fyi (and I will review your mail next)

**Comment by kupsch** [comment]
introducing a microlanguage where the value of the DescriptorReference determines what the relative URI is relative to unnecessarily complicates things.  Just use a prefix of ../.. to get to the tool object.

**Comment by kupsch** [comment]
I think eliminating the pointer all together, along with changing the descriptor arrays to an object with the keys being an the guid for the notification would be a better design.  Then you just lookup the id in the driver and extensions for a match.

**Comment by michaelcfanning** [comment]
Based on Jim's feedback, we propose to rework the reportingDescriptorReference as follows:

- `id` : the id of the descriptor
- `index`: the index into an array of descriptors
- `toolComponentGuid`: a guid that uniquely identifies the tool component associated with the descriptor
- `descriptorGuid`: a guid that uniquely identifies the descriptor.

Notes:
1. All these properties will be inlined into the `result` object, as with today's design, to minimize breaking changes.
2. index on its own references into tool.driver descriptors arrays. for extensions and other uncommon cases, the `toolComponentGuid` must be used to locate the relevant descriptors array (which is indexed into via the `index` property.
3. If the `descriptorGuid` is present, the consumer must potentially consult all descriptor data in the log file to locate it. The `index` and `toolComponentGuid` if present may be disregarded in this case.

**Comment by michaelcfanning** [comment]
Closing this issue. We will accept changes to this type in context of the open taxonomies proposal (where it is utilized). #314

**Comment by michaelcfanning** [comment]
Reopening, as other proposals don't clearly/comprehensively update the `reportingDescriptorReference' type.

**Comment by lgolding** [comment]
#### E-BALLOT <span>#</span>2 PROPOSAL -- INCOMPLETE (See @lgolding)

Define a `reportingDescriptorReference` object that allows results, notifications, and taxonomy references (#314) to point into reporting metadata that may reside in the driver or any of its extensions.

#### SCHEMA CHANGES

- Define a `toolComponentReference` object with the following properties:

    - `name` of type `string`, optional (matches the `name` property of the referenced `toolComponent`).
    - `index` of type `integer`, optional, default: -1, minValue: -1 (the index of the referenced `toolComponent` in `tool.extensions`, if that's where it lives).
    - `guid` of type `string`, optional (matches the `guid` property of the referenced `toolComponent` object).

- Define a `reportingDescriptorReference` object with the following properties:

    - `id` of type `string`, optional (matches the `id` property of the referenced `reportingDescriptor`).
    - `index` of type `integer`, optional, default: -1, minValue: -1 (the index of the referenced `reportingDescriptor` in `toolComponent.ruleDescriptors`, `toolComponent.notificationDescriptors`, or `toolComponent.taxonomyDescriptors` (#314), depending on context).
    - `guid` of type `string`, optional (matches the `guid` property of the referenced `reportingDescriptor`).

- In the `result` object:

    - Add a property `ruleDescriptorReference` of type `reportingDescriptorReference`, optional.
    - For backwards compatibility, _retain_ the `ruleId` and `ruleIndex` properties. That's why `ruleDescriptorReference` can be optional.

- In the `notification` object:

    - Add a property `notificationDescriptorReference` of type `reportingDescriptorReference`, required.
    - Add a property `associatedRuleDescriptorReference` of type `reportingDescriptorReference`, optional.
    - Remove the `id`, `ruleId`, and `ruleIndex` properties.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
