### ISSUE TITLE
Change run.graphs and result.graphs from objects to arrays

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#326]

**Comment by michaelcfanning** [comment]
Consult with Semmle to verify whether we can move this 'future' and remove from v2.

**Comment by michaelcfanning** [comment]
EBALLOT PROPOSAL: the proposed change is to remove all graph-related constructs from the format, to close this issue for v2, and mark it 'future'. In a future revision of the format, we would reconsider adding this functionality (with some updates to bring its design into conformance with other patterns).

API IMPACT:

remove 'edge'
remove 'edgeTraversal'
remove 'externalFileProperties.graphs'
remove 'graph'
remove 'graphTraversal'
remove 'node'
remove 'result.graphs'
remove 'result.graphTraversals'
remove 'run.graphs'

**Comment by lgolding** [comment]
#### EBALLOT <span>#</span>2 PROPOSAL

**Comment by kupsch** [comment]
The description in the OASIS SARIF  ballot for this issue (https://www.oasis-open.org/apps/org/workgroup/sarif/ballot.php?id=3352) says that the "... change is to remove all graph-related constructs from the format ...".  This is the text from #326 EBALLOT <span>#</span>1 PROPOSAL comment, but draft is for the #326 EBALLOT <span>#</span>2 PROPOSAL comment.  Just wanted to confirm that the ballot text is incorrect and that we are voting on EBALLOT <span>#</span>2 PROPOSAL comment.

**Comment by lgolding** [comment]
@kupsch Yes, the ballot text is incorrect and we are voting on the [*EBALLOT #2 PROPOSAL*](https://github.com/oasis-tcs/sarif-spec/issues/326#issuecomment-473594451). I will inform the TC.

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
