### ISSUE TITLE
Remove invocation.attachments

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#327]
The examples that the spec gives for `invocation.attachments` -- configuration files and plugins -- now have a better home in `toolComponent.extensions`. Is there any reason to keep `invocation.attachments`?

**Comment by michaelcfanning** [comment]
TC approves the change.

**Comment by lgolding** [comment]
TODO: Merge this change draft into the provisional draft.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
