### ISSUE TITLE
Consider renaming invocation.executableLocation to invocation.driverLocation

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#328]

**Comment by michaelcfanning** [comment]
Editorial change, update the spec text to be more clearly in line with the current name. Rename rejected.

**Comment by lgolding** [comment]
@michaelcfanning Yes, we decided to reject this because the "driver" component might consist of multiple files, and here we particularly want to specify the primary executable, that is, the file containing the entry point. So `executableLocation` is good.
