### ISSUE TITLE
Rename ‘invocation.toolNotifications’ and ‘invocation.configurationNotifications’ to ‘toolExecutionNotifications’ and ‘toolConfigurationNotifications’

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#330]
**EBALLOT PROPOSAL**: rename 'invocation.toolNotifications' and 'invocation.configurationNotifications' in order to make them more descriptive.

**API IMPACT**:
SDK PR: https://github.com/Microsoft/sarif-sdk/pull/1314
In the `invocation` object:
- Rename the `toolNotifications` property to `toolExecutionNotifications`.
- Rename the `configurationNotifications` property to `toolConfigurationNotifications`.

**NOTES**: these terms are intended to help communicate errors and other problems that are either raised by the tool during execution (requiring a tool developer to resolve ) or as a result of the way the tool has been configured (requiring a change to the results production automation). We also considered but rejected a rename of 'run.result' to 'run.analysisNotifications' or 'run.toolAnalysisNotifications' to completely unify this space. We rejected this possibility as simply being too intrusive at this late state.

**Comment by michaelcfanning** [comment]
Rename to toolExecutionNotifications and toolConfiguration notifications.
'result' remains as is, as too an intrusive a name to change this late in the game.

**Comment by lgolding** [comment]
(@michaelcfanning means that we will not rename the `result` object to `analysisNotification` or the like, even though in our current thinking a "result" is just another kind of notification, and a rename would make sense from the point of view of uniformity.)
