### ISSUE TITLE
Explain how a converter emits its own notifications (as opposed to transcribing the tool's)

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#331]
1. A converter might want to say something like "Conversion started" or "I couldn't convert issue <span>#</span>2". Where does it put these messages? It can't be in `run.invocations[i].tool{Configuration,Execution}Notifications`; those are for messages transcribed by the converter from the tool's native output.

2. Where do you put the converter's metadata, if any, for its own notifications?

**Comment by lgolding** [comment]
Answers:

1. `run.conversion.invocation.tool{Configuration,Execution}Notifications`.

2. `run.conversion.tool.driver.notifications` and/or `run.conversion.tool.extensions[i].notifications`.

So our design already covers this, so resolving "by design".
