### ISSUE TITLE
Can we replace rulePointer and similar with a guid?

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#333]

**Comment by lgolding** [comment]
Interesting point. Now that the localization design (if approved) required a rule GUID anyway.

The thing about the pointer, tho, is that you can navigate the OM to the rule, rather than having to search for it (of course a consumer could construct an in-memory dictionary from GUID to rule).

**Comment by lgolding** [comment]
Clarifying: You can't directly evaluate a JSON pointer in the OM, as you've pointed out, since the JSON is long gone by that time. But you can parse the pointer and use it as a guide to traversing the OM.

**Comment by michaelcfanning** [comment]
I believe we can close this issue. Dereferencing data by guid would require reverting to a dictionary (keyed by guid) or we have undesirable look-up semantics (O(n) traversal of the array looking for a matching guid.

This was a tracking item raised in discussion, there was never a concrete proposal. Please reactivate if you disagree. @lgolding
