### ISSUE TITLE
External property file related renames

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#335]
**EBALLOT PROPOSAL**: rename the external property files object 'properties' member so that it does not collide with the general SARIF design standard of populating all object types with a property bag of that name. This allows the external property file to both have its own property bag (named 'properties') while also allowing it to externalize a run-level properties object (which we will not call 'externalizedProperties')

**API IMPACT**
In the `externalPropertyFiles` object:
- Rename the `properties` property to `externalizedProperties`.
- Restore the `properties` property, which now refers to the object level property bag, not to externalized content.

In the `externalPropertyFiles` object:
- Rename the `instanceGuid` property to `guid`.
- Rename the `artifactLocation`property to `location`

**POST-BALLOT NOTE**
There is a typo in the ballot text. It should read "...which we will now call 'externalizedProperties'" instead of "... which we will not call 'externalizedProperties'".

**Comment by kupsch** [comment]
The object names in the "In the externalPropertyFiles object:" are incorrect: The first one should be "externalProperties" and the second one should be "externalPropertyFile".  It would be more appropriate if these names are swapped: the object in the external file should be the "externalPropertyFile" object and the object in theRun.externalPropertyFiles[<propName>] should be "externalProperty" or better yet something like "externalPropertyReference".

If the instanceGuid property name is going to change to "guid" it should change in both objects for consistency.

**Comment by lgolding** [comment]
1. I agree that if we are changing `externalPropertyFile.instanceGuid` (§3.14.3) to `guid`, then we should also change `externalProperties.instanceGuid` (§4.3.4) to `guid`. My [change draft](https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/ChangeDrafts/Active/sarif-v2.0-issue-335-externalPropertyFiles-property-changes.docx) -- which I pushed a couple of days ago, but did not yet announce to the TC because the ballot was still open -- actually **already has that change**.

2. I understand your argument regarding the names of the existing objects `externalPropertyFile` (§3.14) and `externalProperties` (§4.3):

    1. The rationale for the name `externalProperties` is that this object _contains external properties_: it is named for what it contains. I understand that you want to rename it to `externalPropertyFile` because it is in fact _the root element_ of an external property file: you would name it for where it resides. Both arguments have merit. In the interest of consistency -- at least from one point of view -- since basically every object in SARIF is named for what it contains, and also in the interest of minimizing churn, **I don't want to take this change**.

    2. The rationale for the name `externalPropertyFile` is that it _describes_ an external property file -- so from that point of view it conflicts with the principle of naming objects for what they contain. I like your suggestion of `externalPropertyFileReference`: it's consistent with `reportingDescriptorReference`. **I will make that change.**

3. With all that said: I now realize that the [eballot proposal comment](https://github.com/oasis-tcs/sarif-spec/issues/335#issue-414909200) is wrong in two ways, and one of those mistakes caused me to make a mistake in the change draft. Note that the proposal _twice_ says "In the `externalPropertyFiles` object". But there is no such thing as an `externalPropertyFiles` object.

    1. The first time it occurs, it should have said "In the `externalProperties` object". I need to fix that in the change draft.

          **OPEN ISSUE** Since we are renaming `externalProperties.properties` to `externalProperties.externalizedProperties` (to accommodate a property bag named `properties` in the `externalProperties` object) (and I'm not wild about the name `externalizedProperties`, but we can defer that), _should I make the same change_ in the property name of the object held by `run.externalPropertyFiles`? That is, should `run.externalPropertyFiles.properties` become `run.externalPropertyFiles.externalizedProperties` -- even though it's not strictly necessary because the object held by `run.externalPropertyFiles` has no property bag named "properties" -- in order to match the renamed `externalPropertyFiles.externalizedProperties`? **I think it should**.

    2. The second time it occurs, it should have said "In the `externalProperties` object:", but that doesn't seem to have caused any confusion.

**Comment by lgolding** [comment]
#### Feedback from MS (post-ballot):

- In the `externalProperties` object:
    - Rename the `instanceGuid` property to `guid`.
    - Rename the `properties` property to `externalizedProperties`.
    - Add a property named `properties` that is a property bag.
- In the `externalPropertyFile` object:
    - Rename the object to `externalPropertyFileReference`.
    - Rename the `instanceGuid` property to `guid`.
    - Rename the `artifactLocation` property property to `location`.
- With regard to the `run.externalPropertyFiles` property, and the object it contains:
    - Rename it to `run.externalPropertyFileReferences`.
    - Change the name of the contained object’s `properties` property to `externalizedProperties`.
    - Remove the `run.` prefix from the property names.

**Comment by lgolding** [comment]
Approved in e-ballot <span>#<span>2.
