### ISSUE TITLE
Changes to toolComponent properties

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#336]
**EBALLOT PROPOSAL**: add several descriptive strings to toolComponent that help describe it. This information may be displayed in context of a results management system (which, for example, might provide a brief description of a tool along with a current set of scan results).

**API IMPACT**:
In the `tool` object:
- Add a `organization` property of type `string`: the company or organization that produced the tool
- Add a `product` property of type `string`: a product suite to which the tool belongs, 
- Add a `shortDescription` property of type `multiformatMessageString`: a brief, multiformat description of the tool
- Add a `fullDescription` property of type `multiformatMessageString`: a comprehensive multiformat description of the tool
- Convert `artifactIndex` to an array of artifact locations named `artifactIndices`

**Comment by kupsch** [comment]
organization would be a better property name than company as it is more inclusive

**Comment by lgolding** [comment]
#### E-BALLOT <span>#</span>2 PROPOSAL

The change draft for the combined issues #179 and #336 defines a `toolComponent` object with the following properties, as well as related changes to the `tool` object.

#### SCHEMA CHANGES

- In the `tool` object:
    
    - Remove the never-used `sarifLoggerVersion` property.
    - Add a property `driver` of type `toolComponent`, required.
    - Add a property `extensions` of type `toolComponent[]`, optional, minItems: 0, default: empty array
    - Move all other properties to the `toolComponent` object (`name`, `fullName`, `version`, `semanticVersion`, `dottedQuadFileVersion`, and `downloadUri`) to the `toolComponent` object (defined next).

- Define a `toolComponent` object with the following properties:
    
    - All the properties moved from the `tool` object (`name`, `fullName`, `version`, `semanticVersion`, `dottedQuadFileVersion`, and `downloadUri`).
    - `releaseDateUtc` of type string in `date-time` format -- the component's release date.
    - `informationUri` of type `string` in `uri` format, optional.
    - `organization` of type `string`, optional -- the company or organization that produced the component, _e.g._, `"Example Corporation"`.
    - `product` of type `string`, optional -- the name of the product containing the component, _e.g._, `"Example Corp SecurityScanner"`.
    - `productSuite` of type `string`, optional -- the name of the suite of products containing the component, _e.g._, `"Example Corp Code Quality Tools"`.
    - `shortDescription` of type `multiformatMessageString`, optional -- a brief description of the component.
    - `fullDescription` of type `multiformatMessageString`, optional -- a comprehensive description of the component.
    - `artifactIndices` of type `integer[]`, optional, default: empty array -- references to the files which comprise the component.

**Comment by lgolding** [comment]
Neglected to close after e-ballot-2. Appeared again and approved in e-ballot-3.
