### ISSUE TITLE
Localization and policies

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#338]
#### EBALLOT PROPOSAL

Introduce a new localization mechanism that meets the following requirements:

1. Don't define a new file type to hold localizations. Instead, define new SARIF objects that can be persisted as external property files (and therefore also inlined in the `sarifLog.inlineExternalPropertyFiles` property, should #321 be approved).
2. It should be easy to switch from one language to another (which suggests that the design should permit -- but not require -- all the localized strings for one language to be stored together).
3. It should be possible for a log file to include a "partial" set of localized strings, containing just those strings that are referenced elsewhere in the log file.
4. It should also be possible to ship "comprehensive" sets of strings, that is, strings for all rules and notifications defined by a tool component. Since rule ids are not required to be unique, and since the order (index) in which rules appear in a translation object cannot be enforced, this implies that each rule needs a unique id.

#### API IMPACT

- In the `toolComponent` object:
    - Add a `guid` property of type `string` in GUID format.
- In the `reportingDescriptor` object:
    - Add a `guid` property of type `string` in GUID format.
- In the `run` object:
    - Add a `translations` property of type array of `translation` objects, which can be externalized.
- Define a `translation` object with the following properties:
    - `language` of type string in ISO 639 format, _e.g._, `"en-US"`.
    - `toolComponentTranslations` of type array of `toolComponentTranslation` objects.
- Define a `toolComponentTranslation` object with the following properties:
    - `toolComponentGuid` of type string in GUID format: matches `toolComponent.guid`.
    - `location` of type `artifactLocation`: where the translation can be obtained.
    - `semanticVersion` of type `string`: the semantic version of the tool component for which the translation was made.
    - `partialTranslation` of type `bool`: `true` if this object contains a subset of the strings defined by the tool component.
    - `globalMessageStrings` of type `object` with `multiformatMessageString`-valued properties: its property names are a subset of the names in `toolComponent.globalMessageStrings`.
    - `reportingDescriptors` of type array of `reportingDescriptorTranslation` objects.
    - `notificationDescriptors` of type array of `reportingDescriptorTranslation` objects.
- Define a `reportingDescriptorTranslation` object with the following properties:
    - `id` of type `string`: matches `reportingDescriptor.id`.
    - `guid` of type `string` in GUID format: matches `reportingDescriptor.guid`.
    - `shortDescription` of type `multiformatMessageString`.
    - `fullDescription` of type `multiformatMessageString`.
    - `messageStrings` of type object with `multiformatMessageString`-valued properties: its property names are a subset of the names in `reportingDescriptor.messageStrings`.

#### SAMPLE SARIF

```
{
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "CodeScanner",
          "guid": "<driverGuid>",
          "ruleDescriptors": [
            {
              "id": "CA2101",
              "guid": "<ruleGuid>",
              "defaultConfiguration": {
                "level": "error"
              },
              "messageStrings": {
                "default": {
                  "text": "This is bad: {0}.",
                  "markdown": "This is _bad_: {0}."
                }
              }

          ],
          "notificationDescriptors": [
          ]
        }
      },
      "results": [
        {
          "ruleId": "CA2101",
          "rulePointer": "drive/ruleDescriptors/0",
          "message": {
            "messageId": "default",
            "arguments": [ "42" ]
          }
        }
      ],
      "translations": [
        {
          "language": "en-US",
          "toolComponentTranslations": [
            {
              "toolComponentGuid": "<driverGuid>",
              "location": {
                "uri": "https://example.com/tools/CodeScanner/en-US/1.3.4/translation.sarif.external-property-file"
              },
              "semanticVersion": "1.3.4",
              "partialTranslation": true,
              "fullName": "The localized full name of my application",
              "shortDescription": {
                "text": "A tool for finding bad things."
              },
              "fullDescription": {
                "text": "The best tool for finding bad things. Get your copy today!"
              },
              "globalMessageStrings": {
                "call": {
                  "text": "Function {0} was called.",
                  "markdown": "Function `{0}` was called."
                }
              },
              "ruleDescriptors": [
                {
                  "id": "CA2101",
                  "guid": "<ruleGuid>",
                  "shortDescription": {
                    "text": "This is what happens when you do a bad thing.",
                    "markdown": "This is what happens when you do a _bad_ thing.."
                  },
                  "messageStrings": {
                    "default": {
                      "text": "This is bad: {0}.",
                      "markdown": "This is _bad_: {0}."
                    }
                  }
                }
              ],
              "notificationDescriptor": [
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by kupsch** [comment]
`semanticVersion` would be better as `localizationVersion`

Allow the following optional properties:

- `releaseDate` - date of the release
- `translatorUri` - URI for the translation (mirror tool property as they may no be the same)
- `translatorOrganization` - organization producing the translation
- `translationDownloadUri` - download location for the translation if different from the tool

**Comment by lgolding** [comment]
#### Feedback from MS 

- Typo: the array-valued `run.translation` property should have been named `translations`.

- Additional useful property: For consistency with `toolComponent.downloadUri`, should `toolComponentTranslation` should be have a string-valued `downloadUri` from which the translation can be obtained.

- Missing property: We really do need a `language` property, because it affects the message string lookup order.

    Suppose a tool declares its language as `en-US`. Then if a viewer wants `en-US` strings, it should first check to see if the string is inlined in (for example) the result message, and only if not should it look for `en-US` in `run.translations`. Whereas if the viewer wants `fr-FR` strings, it should not look for an inlined string; instead it should immediately look up `fr-FR` in `run.translations`.

    I also think `language` is more a property of `run` than of `tool`. It means “the language of the messages emitted into the log file during this run.”

**Comment by lgolding** [comment]
#### E-BALLOT <span>#</span>3 PROPOSAL


#### SCHEMA CHANGES

- In the `tool` obect:

    - Remove the `language` property (move to `run`).

- In the `run` object:

    - Add a property `language` of type `string`: the language of the localizable strings emitted in this run.

- In the `toolComponent` object:

    - Add a property `language` of type `string`: the language of the localizable strings defined in this translation.
    - Add a property `dataKinds` of type `string[]` with enumerated values `localizedData` and `nonLocalizedData`: the kinds of data contained in this object.
    - Add a property `isComprehensive` of type `boolean`: `true` is this object contains a complete definition of the localizable and or non-localizable data for this component.
- TO BE CONTINUED

**Comment by lgolding** [comment]
#### E-BALLOT <span>#3</span> PROPOSAL

We introduce a new localization mechanism that represents translations with `toolComponent` objects. Because `toolComponent` objects can now represent so many different things -- the driver, extensions such as plugin, taxonomies, and translations -- we rearrange the format to place these different types of components in their own properties, rather than placing them all in a single list `tool.extension`.

At the same time, we introduce a new mechanism to allow a post-processor to impose a set of rule severities that overrides the configuration that was in place during the run.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
