### ISSUE TITLE
Add suppression object to allow persisting location data for in-source suppressions

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#344]
#### E-BALLOT <span>#</span>3 PROPOSAL

Create a `suppression` object that contains three properties, `kind`, `location` and `properties`.

Scenario: Microsoft is building an internal SARIF tooling pipeline. Some tools flag results and emit -in-source suppression details to the log file. Some suppression decisions are audited/otherwise reviewed after the fact. The reviewers can currently identify the source code associated with a result and SARIF reports that the results are suppressed. The reviewers cannot jump to the suppression location, however, to read the justification information documented there (or to see what engineer checked in the suppression).

We do not propose to augment the suppression object further (to include justification, owner, timestamp, suppression reason, etc., all of which have been discussed at length in the TC) due to our desire to close the format and because these topics relate generally to the broader result management scenario (consciously omitted from SARIF v2). We do believe the suppression location is warranted in this context because: 1) this is data that is owned by the tool and reasonable or even required for the tool to emit, 2) the data is essential to close the loop on auditing the emitted result.

#### SCHEMA CHANGES

- Define a `suppression`object  with the following properties:
    - `kind` of type `string` with enumerated values `suppressedInSource` and `suppressedExternally`: required.
    - `location` of type `location`, optional: the location where the suppression is persisted.
   - `guid` of type `string` (expressing a GUID), optional: uniquely identifies the suppression

- In the `result` object:
    - Add property `suppressions` of type `suppression[]`, optional.
    - Remove property `suppressionStates`.

@lgolding

**Comment by lgolding** [comment]
Approved in e-ballot-3.
