### ISSUE TITLE
Add 'reportingDescriptor.deprecatedNames' and 'deprecatedGuids' to match 'deprecatedIds' property

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#346]
#### E-BALLOT <span>#</span>3 PROPOSAL

To track rules evolution, the property `reportingDescriptor.deprecatedIds` tracks updates to a check's stable and opaque `id` property. We should also track changes to its readable name and its GUID.

#### SCHEMA CHANGES

- In the `reportingDescriptor` property:

    - Add a property `deprecatedNames` of type `string[]`, optional: names by which this rule or notification was previously known.
    - Add a property `deprecatedGuids` of type `string[]`, optional: GUIDs by which this rule or notification was previously identified.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
