### ISSUE TITLE
Add 'referencedOnCommandLine' as a role

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#347]
Scenario: a tool accepts user inputs on the command-line. These inputs may do things like reconfigure the analysis and so this data may be valuable for compliance purposes. Log file producers can persist this user-provided configuration file in the artifacts table and mark it as 'referencedOnCommandLine'.

This suggestion will be included in the draft for #338 and its approval will be covered by the #338 ballot.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
