### ISSUE TITLE
SARIF needs a mechanism to denote an in-flight or completed suppressions review

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#348]
Before a result is conclusively suppressed externally, there is a conversation about it. A result viewer might want to connect to and update (or simply start) that conversation.

The simplest way to provide for this is to define an additional suppressState 'underReview'. When decorated in this way, a viewer would not literally indicate the result is suppressed.

We could also consider renaming this construct to 'reviewAnnotation' etc. I tend to think the 'underReview' state is the simplest option at this late stage.

Separately, what if a conversation occurs but the result was not deemed to be suppressible? What suppression state could indicate this? 'acquitted'? 'determinedToBeTruePositive'?

Once we think about this final 'not a false positive' annotation, another term does occur to me 'dispositions' or 'evaluations'.

result.dispositions is an array of external conversations related to 'disposing' or 'evaluating' a result. 'suppressedExternally' or 'suppressedInSource' is a completed evalution.

**Comment by lgolding** [comment]
#### E-BALLOT <span>#</span># PROPOSAL

Before a result is conclusively suppressed externally, there is a conversation about it. A result viewer might want to connect to and update (or simply start) that conversation.

The simplest way to provide for this is to define an additional `suppressionState` value, `underReview'. When decorated in this way, a viewer would not literally indicate the result is suppressed.

Then, what if a conversation occurs but the result was not deemed to be suppressible? We indicate that with the value `suppressionRejected`.

#### SCHEMA CHANGES

- In the `suppression` object:

    - In the `kind` property, add two new values `underReview` and `suppressionRejected`.

**Comment by lgolding** [comment]
Approved in e-ballot-3.
