### ISSUE TITLE
Consider: Adding CWE property to result object

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#35]
Copied from https://github.com/sarif-standard/sarif-spec/issues/278, created by @lgolding:

At least one static analysis tool (Semmle) emits a CWE ([Common Weakness Enumeration](https://cwe.mitre.org/)) value for the results it finds. Should we add a `cwe` property to the `result` object?

Possible counter-argument is that CWE is domain-specific (applies only to security), which SARIF is domain-neutral (applies to any static analysis result).

**Comment by michaelcfanning** [comment]
See discussion in #3

**Comment by lgolding** [comment]
This was implemented by #56.
