### ISSUE TITLE
Default toolComponent.associatedComponent to theTool.driver

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#357]
In the `sarif-v2.0-e-ballot-3.docx` document, section 3.18.4 "Policies" says:

> A policy SHALL specify the tool component to which it applies by way of its associatedComponent property (§3.18.31).

However, the following example of a policy does not contain an `associatedComponent` property.

**Comment by lgolding** [comment]
@lukecartey Good catch! I've just fixed this in the provisional draft.

I will also add text that if `associatedComponent` is missing, it refers to `tool.driver`, which is always a good default for the common case where the driver is the only component.
