### ISSUE TITLE
originalUriBaseIds and uri resolution

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#358]
The algorithm to merge base and relative URIs does not handle arbitrary URIs as in RFC 3986. The semantics of file paths is also different from the URI rules.  I propose that we treat file scheme URIs slightly different from RFC 3986 and otherwise align with RFC 3986.

The algorithm to create absolute URIs from relative URI and a base URI is almost the merge algorithm from RFC 3986.  The spec algorithm assumes all the originalBaseUriIds entry's path segments end in a trailing '/', are not empty, and do not have fragment or query components.   The RFC 3986 merge algorithm says to remove any query and fragment components of the baseUri first.  Then if the path is not empty remove the last segment but not the last '/' from the base and then concatenate or if the path is empty, concatenate baseUri, '/' and relUri.  The algorithm in spec does not work in this case as is just says concatenate so if there is not trailing '/' in the baseUri it produces an incorrect result.

There are two example in the document in the mappedTo section (probably came from an example I created) and in Appendix H that contain a baseUri without a trailing '/'.

This algorithm does not match how file paths are used or handled, and seems like an easy mistake for a producer to make if the developer is just thinking about file paths as the file path merge resolution algorithm is BASE + DIRSEP + RELPATH (where DIRSEP is '/' or '\') where that last last segment is not removed if there is not a trailing directory separator.

I propose that we align with the merge algorithm in RFC 3986 but to treat file scheme URIs specially:  do not remove the last segment of the path if not empty as it is the base directory and not a file in the base directory.

A safe and non-surprising option (at least for non-file scheme URIs) would be to specify that consumers shall append a '/' to all originalBaseUriIds URI path components before use if the path is empty or does not end in a '/' already.  This makes the algorithms work, and eliminates the possibility of this user error.  For the algorithm in the text any query or fragment components should also be removed from base uris before use.  The text should encourage producers to include a trailing '/' and to not include query and fragments in base URIs, but consumers should reasonably handle this case.

An alternative (that may be less surprising for non-file scheme URIs) would be to just special case URIs with a file scheme, but then the merge algorithm in the spec would need to be changed to recursively resolve the base URI and then just combine it with URI (resolve most-base to least instead of least to most) so you can determine if the base is a file scheme URI.

A lesser solution would be to include a warning that originalBaseUriIds URIs need to end a '/' (and not include a query or fragment) if there is a non-empty path and the validator should verify this condition.  Note that the algorithms in the spec still need to be changed to better match the merge algorithm in RFC 3986 (remove trailing component.

**Comment by lgolding** [comment]
We will address this by requiring that `uri` properties in `originalUriBaseIds` property values:
- **SHALL NOT** have a query or a fragment portion.
- **SHALL NOT** include `..` segments.
- **SHALL** end in a single `/`.

**Comment by lgolding** [comment]
Labeled as `bug` because without these restrictions (or similar measures proposed by @kupsch), the `uriBaseId` resolution algorithm described in the spec can fail.
