### ISSUE TITLE
Constraints in state objects

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#359]
@kupsch made this suggestion in a [comment](https://github.com/oasis-tcs/sarif-spec/issues/168#issuecomment-474065538) on #168:

For many of the tools that I have seen that include flows or traversals, when explaining a flow or graph traversal state, they specify the value of an expression as a literal value (expressible in this current design), or as a constraint on the value (currently not not expressible).  Such as

```
{
  "i":  "i < 5",
  "j":  "j >= 10 && j < 100",
  "p":  "p != NULL ",
  "r":  "r == NULL",
  "s":  "strlen(s) > 100",
  "t":  "buffer t is not NULL terminated"
}
```

This state constraint information that many tools report, could incorporate this without changing the schema by describing that a magic string value such as "{expr}" is used to represent a constraint expression. If "{expr}" exists in the value then it is a constraint (the value may substitute the actual expression for {expr}.  If "{expr}" does not exist in the value then this is an equality constraint equivalent to "{expr} == VALUE" where VALUE is the value of the JSON property.

The above constraints would then become a state object of

```
{
  "i":  "{expr} < 5",
  "j":  "{expr} >= 10 && {expr} < 100",
  "p":  "{expr} != NULL ",
  "r":  "NULL",
  "s":  "strlen({expr}) > 100",
  "t":  "buffer {expr} is not NULL terminated"
}
```

For viewer just displaying the values above would probably be deciphered with the correct meaning by most developers, and advanced viewers could do more to indicate a general constraint instead of just equality.

**Comment by lgolding** [comment]
This is a non-breaking change and I have time to take care of it, so I will.

**Comment by michaelcfanning** [comment]
@lgolding, shouldn't these all be string to multiformat string dictionaries? what happens when someone gets to the place where they want to render this content as markdown otherwise?

we should probably do a quick sanity check in the schema for this situation...

**Comment by lgolding** [comment]
I can certainly see wanting to bold part of an expression,  or to render "expr" in italics. I take it you're willing to accept the break. (Jim's proposal as written was non-breaking.)
