### ISSUE TITLE
3.14.2.2 : Note 2 should say run.conversion.tool property

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#360]
In the sarif-v2.0-e-ballot-3.docx document, in section "3.14.2.2 Property definition", NOTE 2 says:
> NOTE 2: Note that `run.conversion.tool.driver` and `run.conversion.tool.extensions` are not separately externalizable. Rather, the `run.conversion` property as a whole is externalizable.

I think the intention was to say:

> Rather, the `run.conversion.tool` property as a whole is externalizable.

**Comment by lgolding** [comment]
@lukecartey The spec is correct. It is `run.conversion` that is externalizable. See the table in 3.14.2.2, "externalPropertyFileReferences property", "Property definition".

**Comment by lukecartey** [comment]
Oh, you're right, sorry!
