### ISSUE TITLE
Allow the artifactIndex property to be absent when the artifactLocation is within an artifact

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#363]
Regarding the `artifactIndex` property of the `artifactLocation` object, the spec (section 3.4.5 on the  eballot 3 draft) currently says:

> If theRun.artifacts is absent or does not contain an element that describes the artifact specified by this artifactLocation object, then artifactIndex SHALL NOT be present.
> ...
> Otherwise, artifactIndex SHOULD be present.

However, the `artifactLocation` is also used in the `artifact` object itself, where it would seem we should be able to omit the `artifactIndex`, as it is not required for lookup. In fact, the example in the `artifactIndex` section omits the `artifactIndex` in this way.

We could prohibit the use of `artifactIndex` in `artifactLocation`s in `artifact` all together, but I think it might be useful to optionally allow it. This is because it would allow the use of the same _in memory_ object for `artifactLocation`s in both the `artifact` and places that reference the artifact.

**Comment by lgolding** [comment]
@lukecartey Good catch. I added this sentence:

> If `thisObject` occurs as the `artifactLocation` property (§3.23.2) of an `artifact` object in `theRun.artifacts`, then `artifactIndex` **MAY** be present. If present, it **SHALL** equal the array index within `theRun.artifacts` of the containing `artifact` object.

**Comment by lgolding** [comment]
@lukecartey Actually, in addition to adding that sentence, I reworked the presentation of the entire logic of this section. It is logically the same but, I hope, clearer.
