### ISSUE TITLE
ruleId hierarchical string is incompatible with Semmle rule ids

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#365]
The `ruleId` (3.25.5) property of `result` says:

> Depending on the circumstances, a result object either SHALL, MAY, or SHALL NOT contain a property named ruleId whose value is a hierarchical string (§3.5.5) whose first component is the stable, opaque identifier of the rule that was evaluated to produce the result.

The "first component" part is incompatible with Semmle ids, which are of the form e.g. `cpp/path-injection`. By treating the _first_ component as the identifier of the rule, we would consider the rule id to be "cpp", which is incorrect.

Perhaps we can change the description to specify that the `ruleId` should be a hierarchical prefix of the `id` of the associated reporting descriptor?

This also relates to #364.

Apologies, I tried to bring this up in the TC where we discussed this, but I don't think I was very clear on my concerns.

**Comment by lgolding** [comment]
Thanks, your explanation is clear. I fixed this simply by changing "... whose first component is the stable identifier..." to "whose leading components specify the stable identifier...". Surprisingly (to me), the rest of the text just works with that change.
