### ISSUE TITLE
Downgrade artifact.mimeType from SHOULD to MAY

### ISSUE THREAD

**Issue by lukecartey** [oasis-tcs/sarif-spec#367]
The spec currently says:

> An artifact object SHOULD contain a property named "mimeType" whose value is a string that specifies the artifact's MIME type [RFC2045].

However, the IANA list of registered MIME types (https://www.iana.org/assignments/media-types/media-types.xhtml) lacks any MIME types for representing source code files of different languages¹. Therefore, any artifacts that refer to source code will currently need to specify the `mimeType` as `text/plain`. Since the vast majority of entries in the artifact array will be source code files, it seems like this is pretty wasteful.

Two possibilities:

 1. Make the MIME type optional (convert the SHOULD to a MAY). In this case, consumers would use the MIME type to determine how to display the file only if it was present. Otherwise, they would use hints such as the file extension and any specified `sourceLanguage` to determine how to display a particular file. This approach makes sense because even if the MIME type is set to `text/plain`, the consumer will probably want to perform syntax highlighting, and so will have to use hints such as the file extension to determine how to do that.

 2. Make `text/plain` the assumed MIME type if the `artifact.mimeType` is missing.

¹ With two exceptions - javascript and ecmascript. However, the recommended MIME types for these are `application/javascript` and `application/ecmascript`. The `application` top level is supposed to be for _binary_ MIME types, and, in this sense, is used to indicate to a browser that the file is intended to be executed, rather than the viewed. There are some non-standard extension MIME types, for example for c there is `text/x-c`, but as these are not codified anywhere there's no guarantees that producers will all use the same MIME types for the same language files.

**Comment by michaelcfanning** [comment]
+1 on this.
I'd independently observed that the C# SARIF SDK emits a lot of unnecessary mime-type data since it's exclusively inferred from a file extension. There's really no reason to persist this in the SARIF, since it's just as easy to infer the mime-type at log file consumption time.

**Comment by lgolding** [comment]
+1

**Comment by lgolding** [comment]
Actually @lukecartey we could do both of your <span>#</span>1 and <span>#</span>2; they're not mutually exclusive. But since the `artifacts` array is a heady mix of text and binary files of all kinds, I don't think there's a reasonable default, so I'll only do <span>#</span>1.
