### ISSUE TITLE
Do we want to define a "conceptual standard"?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#37]
Copied from https://github.com/sarif-standard/sarif-spec/issues/280, created by @lgolding:

Do we want to _separately_ define

1. an "object model", and
2. a  definitive JSON serialization

... allowing other serializations such as XML, OR do we want to specify JSON as the only valid serialization?

**Comment by michaelcfanning** [comment]
Obviously a lot of work, we can revisit in the future.
