### ISSUE TITLE
Location relationships

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#375]
@kupsch wrote:

> A related location should say what is related to with a `relatedTo` property that is a URI (a `sarif` scheme URI relative to `theResult`). This is necessary as a tool may produce a `relatedLocation` that has its own related location, for instance, an error in `foo.h` may have a related location to say it was included from `bar.h` which was included in `baz.c`.  Also since there may also be multiple locations, they may each have unique related locations.

**Comment by michaelcfanning** [comment]
TC proposal:

Move `physicalLocation.id` to 'location.id'
Add 'location.relatedTo` an integer, >= 0 (the scope of which is constrained to a current result)
Add `location.relationshipKinds`, an array of string identifiers

**Comment by lgolding** [comment]
#### SARIF example (as presented at TC <span>#</span>35)

```
"results": [
  {
    "locations": [
      {
        "artifactLocation": {
          "uri": "foo.h"
        },
        "logicalLocation": "x::y",
        "id": 0
      }
    ],

    "relatedLocations": [
      {
        "physicalLocation": {
          "artifactLocation": {
            "uri": "bar.h"
          },
        },
        "id": 1,
        "relatedTo": 0,
        "relationshipKinds": [ "includes" ]
      }
      {
        "physicalLocation": {
          "artifactLocation": {
            "uri": "bar.c"
          },
        },
        "id": 2
        "relatedTo": 1,
        "relationshipKinds": [ "includes" ]
      }
    ]
  }
]
```

**Comment by lgolding** [comment]
**REVISED PROPOSAL** per Microsoft feedback.

This proposal is consistent with the original, but has the virtue of being consistent with the "reporting descriptor relationships" design.

- Define a `locationRelationship` object with the following properties:

    - `target`  of type `integer`, required, minValue: 0.
    - `kinds` of type `string[]`, optional, with well-known values `"includes"`, `"isIncludedBy"`, and `"relevant"`, default: `[ "relevant" ]`.

- In the `location` object:

    - Add a property `id` of type `integer`, optional, minValue: -1, default: -1 (moved from `physicalLocation`).
    - Add a property `relationships` of type `locationRelationship[]`, optional, unique, default: `[]`.

- In the `physicalLocation` object:

    - Remove the `id` property (moved to `location`).
