### ISSUE TITLE
Each redaction token in an originalUriBaseId represents a unique location.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#377]
From @kupsch, regarding p.29 3.4.5 (artifactLocation.)index property:

There should be a mechanism to redact multiple `uriBaseIds`, but still allow them to be different directories in the file system. If the `redactionToken` is used then there needs to be a note that if the `redactionToken` is present in segment, then each use within a `uri` should be considered a unique (undisclosed) location in the file system, just like a `uri` with `".."`.  If the `redactionToken` appears in a `uriBaseId`'s `uri`, then the `uriBaseId` should be treated as if it were a unique (undisclosed) directory location, but all uses of the that `uriBaseId` with the redacted segment should be considered to have the same unique (undisclosed) path prefix.  For instance if the `redactionToken` is `"[REDACTED]"`, and a `uriBaseId` named X has a `uri` of `"[REDACTED]"`, then `{ uriBaseId = "X", uri = "f.c"}` and `{ uriBaseId = "X", uri = "f.c"}` are the same path, whereas `{ uri = "[REDACTED]/f.c }` and `{ uri = "[REDACTED]/f.c }` should not be considered the same path.

**Comment by michaelcfanning** [comment]
TC approves this change:

Replace `run.redactionToken`, a string with `run.redactionTokens`, an array of strings.

**Comment by lgolding** [comment]
Closing because we have decided we cannot let URIs be redactable -- badly breaks the SDK.
