### ISSUE TITLE
Add properties to describe failed requests

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#378]
From @kupsch, regarding p.147, `response` object:

The `response` object should have a mechanism to indicate that no response was received from the server.  This could happen due to a DNS failure or a connectivity issue such as the server not running or the host or port being inaccessible.  Should add a `requestFailed` and `requestFailureReason` at a minimum.  This is similar to an `invocation` where process creation failed.

**Comment by michaelcfanning** [comment]
TC approves this change:

`request.noResponseReceived` : defaults to false
`request.failureReason` : of type string

**Comment by michaelcfanning** [comment]
@lgolding, on further review, I believe Jim had it right to begin with: noResponseReceived belongs on the response object. We should consider renaming 'reasonPhrase' to 'failureReason' to allow it to be used for this case. We should probably discuss in more detail soonest and loop in Jim.

**Comment by michaelcfanning** [comment]
@lgolding these changes need to go into the schema asap

**Comment by lgolding** [comment]
The current proposal is simply to add `webResponse.noResponseReceived`. We will overload `webResponse.reasonPhrase` to hold the error message in this case.
