### ISSUE TITLE
External property file guid  might refer to invariant contents

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#384]
The spec neglects to say that once you create an external property file, complete with guid, that you can never change its contents. You want new contents, you assign a new guid.

This maintains the integrity of the root log file. Conceptually you took a big log file and decomposed it into a set of parts; you can't change the parts after the fact.

**Comment by michaelcfanning** [comment]
The actual proposal for this problem has been updated, in order to allow both for the scenario described here as well as scenarios in which users explicitly form documents in a way that allows for dynamic updating of deconstructed elements.

**Comment by lgolding** [comment]
Final design: if the spec says it's invariant, remove that constraint; otherwise nothing to do.

**Comment by lgolding** [comment]
The spec does not say that the contents are invariant. It says that `externalPropertyFileReference.guid` is a "unique, stable, identifier" for the file, but it doesn't say the _contents_ can't change.
