### ISSUE TITLE
Improve Appendix on use of SARIF by log file viewers

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#394]
@michaelcfanning provided these suggestions:

> I think it might be useful to note that a primary concern of viewers is to retrieve and display the artifacts associated with a result. And to mention the range of things we provide for this, including embedding files in the artifacts table, constructing URIs so that it’s easier to remap local source enlistments, and/or providing URLs to actually hosted content that the viewer can retrieve.
>
> Having access to this data provides a fundamentally improved viewer experience.
>
> In the absence of this information, for whatever reason, code snippets (and those associated with a contextRegion in particular) are the fallback.
>
> Finally, in the absence of complete files or partial snippets, the user depends on properly constructed user-facing strings (which is why we spend so much time on documenting what should be in the result.message). Every tool’s goal s/be that this content is sufficient to guide a developer to locating and resolving the presumed quality defect.
> 
> It’d be nice to mention all these layers, building out from the core:
>
> 1. Well constructed result messages (and user-facing strings in general)
> 2. Code snippets
> 3. Access to complete files
>
> <span>#</span>1 cannot be dispensed with. The approach for <span>#</span>2 or <span>#</span>3 s/be carefully considered. We have found that in web/browser contexts where users perform a cursory triage (but don’t dive into a fix), code snippets are useful. For developers who need to get accurate root cause and make a fix, complete files are critical.
>
> Note that version control provenance is also highly relevant when oriented towards a fix.

**Comment by michaelcfanning** [comment]
Marking as `future` and closing for now.
