### ISSUE TITLE
Rework Appendix F: Determinism

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#395]
We need to rework Appendix F. As written, it doesn’t distinguish between two types of determinism:

•	Type 1: the ability to produce identical outputs from identical inputs.
•	Type 2:  the ability to produce identical outputs from any inputs that generate the same results.

And it has a single list of prohibited properties, but that is wrong because, for example, artifact.contents is allowed for Type 1 determinism but not for Type 2.

Type 2 determinism is useful in build systems that cache the results from each build step. It gives you the ability to (for example) skip a bug-filing step if the log file hasn't changed.

I (@lgolding) am not yet clear on the value of Type 1 determinism, but @michaelcfanning will provide more information.

**Comment by michaelcfanning** [comment]
My assumption is that we cannot update the appendices on the OASIS standard without opening a new effort to revise the standard. If so, we should label the two open appendix suggestions as 'future' and close. 

We can develop offline content to assist with this topic as part of the [SARIF tutorials](https://github.com/microsoft/sarif-tutorials) effort.

**Comment by dmk42** [comment]
Right.  Revising the appendices would be a SARIF 2.1.1 or later item.

**Comment by michaelcfanning** [comment]
Marking as `future` and closing for now.
