### ISSUE TITLE
CONSIDER: Adding a "project" property to the "file" object

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#40]
Copied from https://github.com/sarif-standard/sarif-spec/issues/283, created by @lgolding:

... to represent the project to which the file belongs.

**Comment by michaelcfanning** [comment]
Closing this item. This suggestion was provided by someone working in the Visual Studio IDE who wanted the VS 'project' column to be populated. This is done automatically by the IDE if a file that's referenced by an open project in the solution is opened.

To date, no one has cited a reason to directly relate a source file to a project file. TC participants have proposed to more strongly associate files with a source control server/project/repository/commit/version, and we will address those suggestions (in a separate work item).

@lgolding, if this makes sense, please close this issue.

**Comment by lgolding** [comment]
@michaelcfanning I agree. Closing.
