### ISSUE TITLE
Resolve spec vs. schema discrepancy re: "language" property

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#402]
The spec mandates RFC5646 to populate `run.language`. The schema specifies that this property is constrained to a proper subset of RFC5646, consisting of an ISO 639-1 country code and an optional ISO 3166 region code.

Larry and I can't locate any history that helps us figure out how this discrepancy materialized. The RFC5646 requirement is long-standing (in fact, dates back to SARIF v1). The most likely scenarios are that we either changed the requirement and failed to update the spec. Or that we updated the schema speculatively in the SDK and someone made a successful case against the change in TC discussion.

Does anyone recall the history on this? @kupsch?

**Comment by lgolding** [comment]
Per @kupsch: ISO 639-1/ISO 3166 suffices.
