### ISSUE TITLE
Remove per-property "inheritance" from cached objects

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#403]
Addresses and logical locations have a parenting mechanism to provide for caching. Adding a second caching mechanism for these creates unnecessary complexity for consumers that doesn't provide clear value. If producers provide an index, they can recapitulate duplicative properties for purposes of readability but they must remain in sync with the run level version. And so we should remove index.

Even after removing `logicalLocation.index` and `address.index`, the complexity we refer to still applies to the other cached objects `threadFlowLocation`, `webRequest`, and `webResponse`.

Part of the problem is that we have never clearly distinguished between two concepts; we have used the term "caching" to refer to both:

- **Reuse**: Multiple "local objects," for example multiple `threadFlowLocation` objects in  `result.codeFlows[0].threadFlows` can _reuse_ the same "cached object in `run.threadFlowLocations` by specifying their `threadFlowLocation.index` property.

- **Inheritance**: Those "local objects" can _inherit some properties from_ the "cached object", while at the same time specifying other properties locally.

It is the inheritance part that really complicates the SDK. Therefore, we propose to _remove the inheritance mechanism_. For the remaining cached objects `threadFlowLocation`, `webRequest`, and `webResponse`, we propose to require that _either_ the `index` property _or_ a set of local properties, but _not both_, be present.

**UPDATE** @lgolding 4/29/2019: We are restoring the `index` property on `address` and `logicalLocation`. So this is no longer a schema change (although it _is_ still breaking).

**Comment by lgolding** [comment]
Sorry, reopened the wrong issue. Should have been #401.
