### ISSUE TITLE
artifactLocation.rendered example shows a physicalLocation object instead

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#409]
See section 3.3.4. This example shows an example of `physicalLocation.region.snippet.rendered` rather than `artifactLocation.rendered`.

@lgolding

**Comment by lgolding** [comment]
The sample is correct. `rendered` is a property of the `artifactContent` object (see §3.3.4), not the `artifactLocation` object. And `region.snippet` _is_ an `artifactContent` object (see §3.30.13). So it is correct to show the `rendered` property under `physicalLocation.region.snippet`.

As @michaelcfanning pointed out, the example would have been clearer if I'd commented that `snippet` is an `artifactContent` object, so I did that.
