### ISSUE TITLE
TypeScript files with Sarif Object declarations

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#41]
Copied from https://github.com/sarif-standard/sarif-spec/issues/291, created by @joshbw:

It would be quite useful to have a couple TypeScript files with the Sarif objects declared.  That would make working with Sarif output super easy to script in Node.js, and selfishly, would save me some time adding Sarif output support in DevSkim

**Comment by lgolding** [comment]
Comment from @lgolding:

Thanks for the input, Josh! Tell me your thoughts on this. We have a SARIF SDK for .NET (https://github.com/Microsoft/sarif-sdk) with C# class declarations for the SARIF objects. So similarly, I suspect what we'd want here is a SARIF SDK for Node.js.

@michaelcfanning FYI for your thoughts as well.

**Comment by michaelcfanning** [comment]
This s/be a sarif-sdk issue, absolutely (and we should close this issue as not relevant to the literal spec).

**Comment by michaelcfanning** [comment]
https://github.com/Microsoft/sarif-sdk/issues/799
