### ISSUE TITLE
Improve efficiency of tool and toolComponent objects

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#424]
@kupsch commented on the second CSD.2 e-ballot:

> `tool.extensions[]` should be treated the same as `tool.driver` for the case of external property files. I am OK with not fixing this in version 2.1. In the next version of SARIF the `tool` property should be reworked to improve this and other inefficiencies with the `tool` object and `toolComponent` objects.

**Comment by michaelcfanning** [comment]
Closing due to marking as 'future'.
