### ISSUE TITLE
Add time-related properties to suppression object

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#428]
This was requested by a team internal to MS:

Add the following properties to the `suppression` object:
- `creationTimeUtc`: The time when the suppression was created.
- `reviewStartTimeUtc`: The time when the team started reviewing the suppression request.
- `reviewEndTimeUtc`: The time when the team finished reviewing the suppression request (and marked it either `"accepted"` or `"rejected"`).
- `expirationTimeUtc`: The time when the suppression will expire and the result will need to be reconsidered.

**Comment by michaelcfanning** [comment]
Closing due to marking as 'future'.
