### ISSUE TITLE
Add missing constraint: result.ruleId == result.rule.id

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#429]
The spec correctly says that if `result.ruleIndex` and `result.rule.index` are both present, they must be equal. But it does _not_ say that if `result.ruleId` and `result.rule.id` are both present, they must be equal. It _should_ say that.

**Comment by lgolding** [comment]
I neglected to close this when I marked it `resolved-fixed`.

**Comment by Hawkmike** [comment]
How are you doing click on the link below to update your contacts

**Comment by Rpsboogie** [comment]
Jzhhh
