### ISSUE TITLE
Consider per-sub-rule metadata

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#433]
Per §3.27.5, `result.ruleId` contains a rule's stable identifier, optionally followed by an additional hierarchical component. Since §3.49.3 says that `reportingDescriptor.id` is (_just_) the stable identifier, the spec does not support"per-sub-rule" metadata.

Should a future version of SARIF support per-sub-rule metadata? This would _not_ be a breaking change, because the spec says you have to look up rule metadata by `result.ruleIndex`, not by `result.ruleId`. So you could certainly have two result objects like this:
```
{
  "ruleId": "CA5350/sha-1",
  "ruleIndex": 1
},
{
  "ruleId": "CA5350/md5",
  "ruleIndex": 2
}
```

**Comment by michaelcfanning** [comment]
We should close all items labeled future. Then we can drop out active issue list to zero. Once the spec is accepted, we can go back and recover all 'future' items. Agree?

**Comment by lgolding** [comment]
Fine with me.

**Comment by michaelcfanning** [comment]
Closing due to marking as 'future'.
