### ISSUE TITLE
Add result.confidence

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#439]
We know of two tools that have the concept of the "confidence" of a result:

- Micro Focus Fortify
- Bandit (Python security analyzer)

**Comment by michaelcfanning** [comment]
This topic has been much discussed in previous related issues (see for example #28 and #58). There are many annotations tools provide tool results that describe criticality, confidence of a true positive, likelihood to occur, other data around engine precision (which may be the expression of confidence).

After much discussion around this topic, SARIF has landed in the following place:

1) Result failures are bucketed into levels that model compiler output (errors, warnings, and 'notes')
2) The 'rank' property is a general purpose property that a tool can use for its own specific understanding of ranking/prioritization.

By current design, the two tool examples provided would utilize 'rank' for their notion of confidence. 

I am closing this issue as expressing the problem in this way effectively resets the conversation back to our baseline. A moving forward request of this kind would really be an appeal for tool vendors to converge on a common set of terms for describing their analysis. This may not be practical, given the diverse nature of analysis techniques out there. 

Any reactivation of this problem should attempt to capture the SARIF v2 design decisions that we landed upon in this version and state the broad moving forward goal for the format in this area.
