### ISSUE TITLE
Editorial issue in invocation.startTimeUtc and invocation.endTimeUtc descriptions

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#445]
As below the descriptions for `invocation.startTimeUtc` and `invocation.endTimeUtc` should refer to the `invocation` and not the `run` instance. This correction was likely missed when we created the notion of multiple invocations to represent a single run (moving the relevant UTC properties to the invocation type).

`"description": "The Coordinated Universal Time (UTC) date and time at which the run started`

@lgolding, FYI

**Comment by michaelcfanning** [comment]
We may consider updating descriptions for the `invocation` `machine`, `processId` and `workingDirectory` descriptions as well.

**Comment by lgolding** [comment]
@michaelcfanning `executableLocation` also needed tweaking.
