### ISSUE TITLE
Invalid Hyperlinks Found

### ISSUE THREAD

**Issue by dmk42** [oasis-tcs/sarif-spec#446]
I'm forwarding this comment that Paul Knight made in a Jira issue while setting up our public comment period.

Paul Knight commented on TCADMIN-3638:
--------------------------------------

- checked links, etc.
-- noted that two text strings have been turned into "invalid" hyperlinked text (although not visible as blue text)
--- 3.11.6 - "C:\Users\Users\code\input.c(25"
--- 3.14.14 - "C:\Users\Mary\code"
--- It appears that someone changed these text strings to remove the blue (default) color in the document, but left the hyperlinks intact. These elements were in the initial material submitted by the TC for csprd01.
--- not a blocking issue, just possibly confusing to users

[https://issues.oasis-open.org/browse/TCADMIN-3638](https://issues.oasis-open.org/browse/TCADMIN-3638)

**Comment by dmk42** [comment]
@lgolding and @michaelcfanning - We should include this in our public comment processing as well.  I have also forwarded a copy to the sarif-comment list.

**Comment by lgolding** [comment]
@dmk42 @michaelcfanning I labeled this issue `2.1.0-candidate-standard-public-comment`.

**Comment by dmk42** [comment]
For OASIS bookkeeping, here is the link to the sarif-comment e-mail representing this comment:

https://lists.oasis-open.org/archives/sarif-comment/201912/msg00005.html
