### ISSUE TITLE
Suppression "status" property mis-spelled as "state" in the schema

### ISSUE THREAD

**Issue by lcartey** [oasis-tcs/sarif-spec#449]
In [Section "3.53.3 `status` property"](http://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html#_Toc27654054), the name of a `suppression` object's status property is called `status`. However, the schema:

https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json

has the field named as `state`. I suggest we take the spec name as canonical, and update the schema to match.

**Comment by brendongo** [comment]
Hi looks like this problem is back? https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json has `state` instead of `status`
