### ISSUE TITLE
Clarify restrictions on attempting to format plaintext messages.

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#451]
See 3.11.3 'Plain text messages'

This section clearly states that 'a plain text message SHALL NOT contain formatting information such as HTML tags'. This prohibition also includes more naive attempts to format messages such as using spaces, tabs, etc. to provide indentation or to suggest some structure to the message.

We should add a bit of language that makes it quite explicit: formating s/be restricted to embedded links and the introduction of line end sequences, if necessary, to break apart paragraphs (noting, as we already do, that viewers are free to transform, elide or encode these line end sequences).

Also, a minor point, the text refers to \r as a 'line break' when this character literally refers to a carriage return.

**Comment by lgolding** [comment]
Done, except I didn't change the "line break" language. Instead, I changed "line breaks (for example, `"\r"` or `"\n"`)" to "line breaks (for example, `"\r\n"` or `"\n"`)"

**Comment by michaelcfanning** [comment]
Yes, this seems simpler.
