### ISSUE TITLE
Some originalUriBaseIds uri properties in examples lack trailing slash

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#458]
- §3.14.14, EXAMPLE 1, `SRCROOT` (occurs twice in that example).
- §3.23.8, EXAMPLE, `HOME` and `PACKAGEROOT`.
- §3.25.2, EXAMPLE, `WEBHOST`.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
