### ISSUE TITLE
Define an "scannedFile" role

### ISSUE THREAD

**Issue by ghost** [oasis-tcs/sarif-spec#459]
`artifact.roles` has the value `"analysisTarget"` to describe an artifact that a tool was instructed to scan (for example, a C++ file `source.cpp`), and `"resultFile"` to describe an artifact in which a result was found as a result of scanning the target (for example, a C++ header file `header.h` that was `#include`d by `source.cpp`).

But there is no role to describe a file that was scanned as a result of scanning `source.cpp` but in which no result was found -- for example, a header file `header2.h` that was `#include`d by `source.cpp` but in which no result was found.

Consider adding a role named (for example) `"scannedFile"` for this situation.

@michaelcfanning FYI

* * * *
**FINAL PROPOSAL:**

### 3.24.6 roles property** (add after "resultFile" on L113)

- `"scannedFile"`: An "indirect" artifact (not directly requested for scanning, but scanned as a result of analyzing another "linked" artifact) in which no result was found.

    > NOTE 4: For example, a scanner might be configured to analyze a C source file and find no result in a header file that it includes. The header file may be marked with the `"scannedFile"` role. The C file should be marked with the `"analysisTarget"` role, however, as it was explicitly configured as a scan target.

**Comment by michaelcfanning** [comment]
TC approved during session 43.

**Comment by schlaman-ms** [comment]
Document location for issue:

lgolding:
> "Consider adding a role named (for example) "scannedFile" into roles property

§3.24 artifact object
§3.24.6 roles property

**Comment by sthagen** [comment]
Updated proposal (starting from Stacy's text and merging the feedback from Kalle):

```
Start of pseudo-snippet >>>
```

## 3.24 artifact object

### 3.24.6 roles property** (add after "resultFile" on L113)

- `"scannedFile"`: An "indirect" artifact (not directly requested for scanning, but scanned as a result of scanning another "linked" artifact) in the case no result was found in this indirectly scanned artifact.

    NOTE 4: For example, a scanner might be configured to analyze a C source file and find no result in a header file that it includes. The header file may be marked with the `"scannedFile"` role. The C file should be marked with the `"analysisTarget"` role, however, as it was explicitly configured as a scan target.

```
<<< End of pseudo-snippet
```

@stacywray There should be easier ways to characterize the set of scannedFile values ​​in English. If you know one, I would be happy if you either edit this suggestion right here or create a new suggestion “below”. Of course totally your choice. Thanks.

**Comment by stacywray** [comment]
@sthagen I updated the suggestion above for simplicity. Feel free to revert if needed.
