### ISSUE TITLE
Explain why ".." path segments can't be normalized out

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#460]
§3.10.2 says:

> SARIF consumers **SHALL NOT** normalize ".." segments out of a path. A consumer **SHALL** treat distinct portions of paths up to and including the rightmost ".." segment as unique directories on the file system, even if [RFC3986] normalization would produce identical paths.
>
> EXAMPLE 3: Consider the following three URIs:
> - `file:///d1/../f1`
> - `file:///d1/../f2`
> - `file:///d1/d2/../../f3`
>
> A consumer would treat `f1` and `f2` as residing in the same directory. So, for example, if a viewer prompted the user to supply the directory where `f1` resides, it could search for `f2 `in the same directory, without prompting again. On the other hand, even though `f3` appears to reside in the same directory as `f1` and `f2`, the viewer would not assume that, and would prompt the user to supply the directory where `f3` resides.

It's not obvious to the reader why `f3` might not be in the same directory as `f1` and `f2`. Add a NOTE to explain that it's because `d2` might be a reparse point.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
