### ISSUE TITLE
Discourage ".." in file scheme URIs

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#461]
In §3.10.2, "Normalizing file scheme URIs", add (something like) the following:

> SARIF producers **SHOULD NOT** emit file-scheme URIs that contain ".." path segments, and SARIF consumers **SHOULD** reject them.
> 
> NOTE: ".." segments are dangerous because the semantics of the file system on which the SARIF log file was produced might not match the semantics of the file system on which it is consumed. For example, the presence of a symbolic link in the path might redirect the consumer to an unpredictable location.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
