### ISSUE TITLE
Clarify that a region requires a "start" property.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#462]
The spec says:
- Every region is one (or more) of a text region with line/column properties, a text region with character offset/length properties, or a binary region (see §3.30.1).
- A text region specified by line/column properties requires a `startLine` property (§3.30.5).
- A text region specified by character offset/length properties requires a `charOffset` property (§3.30.9).
- A binary region requires a `byteOffset` property (§3.30.11).

From all this we can conclude that at least one of `startLine`, `charOffset`, or `byteOffset` is required. But the spec doesn't come right out and say that, and the schema doesn't require it.

Clarify this point in the spec text, and add the constraint to the schema's definition of the `region` object:
```
"region": {
  ...
  "anyOf": [
    { "required": [ "startLine" ] },
    { "required": [ "charOffset" ] },
    { "required": [ "byteOffset" ] }
  ]
```

@michaelcfanning and @harleenkohli FYI (Harleen and I ran into this point today).

**Comment by sthagen** [comment]
Propose to close as already resolved with the errata01 of the OS standard.
@dmk42 Do I got that right?

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
