### ISSUE TITLE
Clarify meaning of 'resultFile' artifact role.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#464]
The spec says (§3.24.6):

> `"resultFile"`: A result was detected in this artifact.

Clarify that this is intended for artifacts that the tool was not directly instructed to scan. The classic example is when a tool scans a C source file and finds a result in an included header file.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
