### ISSUE TITLE
Recommend the path-noscheme form for relative URIs.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#468]
The reason for specifying a URI as a relative reference is to make it easy to "rebase" URIs when you move a SARIF file from one machine to another where the repo root isn't in the same place. You can't do that if the relative references start at the root of the drive, for example `/a/b/c.txt`.

Consider adding either a non-normative note or a **SHOULD**-level requirement for relative references to use the `path-noscheme` form ([RFC 3986](https://tools.ietf.org/html/rfc3986) §4.2), which is roughly `a/b/c.txt` (no leading slash).

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
