### ISSUE TITLE
Spec doesn't say that region.startColumn can't point past the end of the line

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#475]
It should say that.

Strictly speaking this is a breaking change: pathological files that used to be valid according to spec are no longer valid.

When fixing this, consider whether `startColumn` should be allowed to point past the last visible column in the line and point to the line end sequence.

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
The TC rejected this suggestion. A `region.startColumn` value that doesn't exist is a bug in the producer. In general, we can't bullet-proof our specification by envisioning every possible producer bug and explicitly noting that this negative condition is invalid SARIF.
