### ISSUE TITLE
Comprehensive SARIF file example is not a valid JSON.

### ISSUE THREAD

**Issue by dector** [oasis-tcs/sarif-spec#476]
[Example provided in K.4 section](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541390) is not a valid JSON file (numerous error are found). Also there are some fields that are not defined in schema (e.g. `runs.automationId`).

Thus, according to [SARIF Validator](https://sarifweb.azurewebsites.net/Validation) this example is not a valid SARIF file.

**Comment by lgolding** [comment]
Thanks @dector for finding the errors.

**Comment by michaelcfanning** [comment]
Fixing this was approved during TC session 42.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
