### ISSUE TITLE
Add appendices for media type and URI scheme registrations.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#477]
Add appendices for the IANA registrations of
- Media type `application/sarif+json`
- Media type `application/sarif-external-properties+json` (not yet registered at the time of this writing)
- URI scheme `sarif` (not yet registered at the time of this writing)

Per Chet Ensign of OASIS:

> Generally, the way TCs do this is to include the registration as part of the specification, usually in an appendix.

Unfortunately we didn't complete the registrations before publishing the first version of the spec. So if there's ever another version, we should do this.

@michaelcfanning FYI

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
