### ISSUE TITLE
End-to-end results management concepts

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#48]
The TC has determined that for the immediate future, we will focus strictly on SARIF as a format for expressing immediate tool results. We will track a set of additional concepts, however, that relate to managing results end-to-end (from production, through baselining, triage, scheduling, resolution, etc.). If we have sufficient time/inclination in the TC, we may address these concepts or propose a new plan to address. We will maintain a list of concepts to address in the root message of this thread. Current concepts include:

* Triage state. 'Not reviewed', 'Won't fix', 'Fix', etc.
* Validation state 'Not validated', 'False positive', 'True positive.' 
* Suppression justification (string that describes why an item is baselined/suppressed)
* Priority, Certainty, Severity, Rank, etc.

**Comment by michaelcfanning** [comment]
Item #48 produced idea to persist suppression justification

**Comment by michaelcfanning** [comment]
#58

**Comment by lgolding** [comment]
This is a catch-all, not an independent issue. I'm closing this. I'll mark the related issues with the `result-management` label.
