### ISSUE TITLE
Don't allow leading / in relative artifact location URIs.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#480]
The rationale for requiring `artifactLocation.uri` to be a relative reference when `uriBaseId` is present is that we should be able to _combine_ `uri` with any `file`-based URI to form an absolute path. `/dir/file.c` is technically a relative URI reference, but it is an absolute _file path_.  That means you _cannot_ combine it with a base value such as `file:///C:/dev/myProject`.

The spec should prohibit leading `/`s on `artifactLocation.uri`. It doesn't even matter whether or not `artifactLocation.uriBaseId` is present: if `artifactLocation.uri` is _not absolute_, it can't start with a `/`.

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Approved TC session 43.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
