### ISSUE TITLE
Schema doesn't allow sarifLog.runs to be null.

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#481]
The text of the spec allows `sarifLog.runs` to be `null`, but the schema doesn't allow it. The text of the spec is right.

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Fixing this problem was approved by the TC during session 42.

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
