### ISSUE TITLE
Enums in the JSON Schema should include a type.

### ISSUE THREAD

**Issue by marcogario** [oasis-tcs/sarif-spec#487]
In JSON Schema, the keyword `enum` defines a constraint on possible values of the field, but does not enforce a type. Using an explicit type makes it possible to generate better code from the JSON Schema.

For example, changing the definition of Level https://github.com/oasis-tcs/sarif-spec/blob/master/Schemata/sarif-schema-2.1.0.json#L2054-L2058 from:

```json
"level": {
          "description": "A value specifying the severity level of the result.",
          "default": "warning",
          "enum": [ "none", "note", "warning", "error" ]
        },
```

to

```
"level": {
          "description": "A value specifying the severity level of the result.",
          "default": "warning",
          "enum": [ "none", "note", "warning", "error" ],
          "type": "string"
        },
```

makes it possible to generate code that assumes that `level` is a string, rather than an arbitrary object.

I checked a few other `enum` instances and it seems that none defines a type, so I assume this was an oversight, but let me know if this was intentional. 
Happy to prepare a PR to change this, if you can confirm against which version of the schema this should be done.

**Comment by michaelcfanning** [comment]
So, we missed this basically due to our focus on the converted OM generated from the schema. All SARIF enums consist of string values only. We will update the schema in the errata release to fix this. Thanks for the report!

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
