### ISSUE TITLE
The schema of the `run.language`  and `toolComponent.language` properties is incorrect.

### ISSUE THREAD

**Issue by aetos382** [oasis-tcs/sarif-spec#488]
The pattern of the schema for the `runs.tools.driver.language` property is `^[a-zA-Z]{2}|^[a-zA-Z]{2}-[a-zA-Z]{2}]?$`, but this will not entirely match language tags such as `en-US`.

https://github.com/oasis-tcs/sarif-spec/blob/a22c0397efc2dba5c74eededefe6b0307e329e4c/Schemata/sarif-schema-2.1.0.json#L2357

**Comment by michaelcfanning** [comment]
Approved during TC session 42.

**Comment by michaelcfanning** [comment]
Schema pattern updated to:

```
^(?i)[a-zA]{2}(-[a-z]{2})?$
```

**Comment by dmk42** [comment]
Now that the Errata document has been published, this has been fixed in the official version of the standard.
