### ISSUE TITLE
Suggestion: Add a `relatedLocations` property to `notification` objects

### ISSUE THREAD

**Issue by henrymercer** [oasis-tcs/sarif-spec#491]
This would allow notifications to distinguish between the following types of location:

1. Locations to which the condition described by the notification apply.
2. Other locations to which the condition described by the notification doesn't apply, but that are relevant to understanding the result.

Currently the definition of what should be in the `locations` property states that locations are present in the `location` property if "the condition described by the notification object is relevant to" them.  It's uncertain to me whether this implies just (1), or both (1) and (2).

It might be useful to redefine the `locations` property of `notification` objects to contain (1), i.e. locations to which the condition described by the notification applies, and add a `relatedLocations` property to contain (2), i.e. locations which are relevant to understanding the result. This would also improve consistency between `result` and `notification` objects.

As an example, suppose we have a notification for files that were not successfully analyzed by an analysis tool. The results for this notification each specify some location A which could not analyzed. Each result also contains a message with an inline link to a location B (maybe a build definition file) that prompted the analysis tool to attempt to analyze file A. The condition described by the notification object applies to A, but not B, since we did in fact successfully analyze B. So location A falls into the category (1), and location B falls into category (2).
* * * *
**FINAL PROPOSAL:**

The proposal is two-fold with a minor change to **§3.58.4 `locations property`**:

If the condition described by the `notification` object is relevant to one or more locations, the `notification` object **MAY** contain a property named `locations` whose value is an array of zero or more unique ([sec](#array-properties-with-unique-values)) `location` objects ([sec](#location-object)) that identify those locations to which the condition described by the notification applies.

---

And an addition of **§3.58.10 relatedLocations property (proposed)**:

### relatedLocations property{#notification-object--relatedLocations-property}

A `notification` object **SHOULD** contain a property named `relatedLocations` whose value is an array of zero or more unique ([sec](#array-properties-with-unique-values)) `location` objects ([sec](#location-object)) that identify those locations to which the condition described by the notification applies.

The `relatedLocations` property **SHOULD** allow `notification` objects to distinguish between the following types of locations:

- Locations to which the condition described by the `notification` object **SHALL** apply.
- Other locations to which the condition described by the `notification` object **SHALL NOT** apply but are relevant to understanding the result.

**Comment by michaelcfanning** [comment]
Thanks for the excellent suggestion. We will be discussing this change at today's committee meeting.

**Comment by schlaman-ms** [comment]
### Document location for issue:
Possible new subsection under §3.58 notification object
§3.58.10 relatedLocations property

**Comment by stacywray** [comment]
The proposal is two-fold with a minor change to **§3.58.4 `locations property`**:

If the condition described by the `notification` object is relevant to one or more locations, the `notification` object **MAY** contain a property named `locations` whose value is an array of zero or more unique ([sec](#array-properties-with-unique-values)) `location` objects ([sec](#location-object)) that identify those locations to which the condition described by the notification applies.

---

And an addition of **§3.58.10 relatedLocations property (proposed)**:

### relatedLocations property{#notification-object--relatedLocations-property}

A `notification` object **SHOULD** contain a property named `relatedLocations` whose value is an array of zero or more unique ([sec](#array-properties-with-unique-values)) `location` objects ([sec](#location-object)) that identify those locations to which the condition described by the notification applies.

The `relatedLocations` property **SHOULD** allow `notification` objects to distinguish between the following types of locations:

- Locations to which the condition described by the `notification` object **SHALL** apply.
- Other locations to which the condition described by the `notification` object **SHALL NOT** apply but are relevant to understanding the result.
