### ISSUE TITLE
Suggestion: add an `expiryDateUtc` property to `suppression` instances

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#492]
## 3.35.7 expiryDateUtc property  

A `suppression` object **MAY** contain a property named `expiryDateUtc` whose value is a string in the format specified in [§3.9](#3.9), specifying the UTC date (and optionally, the time) through which the suppression is valid.

A SARIF producer **SHOULD** omit the time component of the UTC unless the suppression requires a more granular validity precision.

~~~
        "expiryDateUtc": {
          "description": "The Coordinated Universal Time (UTC) date and time at which TODO (author this)",
          "type": "string",
          "format": "date-time"
        },
~~~

TODO: Extend 3.9 to show expanded UTC dates of supported formats.

* * * *

**FINAL PROPOSAL:**

## 3.9 Date/time properties

Certain properties in this document specify a date and time. The value of every such property, if present, **SHALL** be a string in the following format, which is compatible with the ISO standard for date and time formats [cite](#ISO8601;2004):

    date time = date, [ "T", time, "Z" ] (* UTC time *);

    date = year, "-", month, "-", day;

    year = 4 * decimal digit;

    month = 2 * decimal digit (* from 01 to 12 *);

    day = 2 * decimal digit (* from 01 to 31 *);

    time = hour, ":", minute, [ ":", second, [ ".", fraction ] ];

    hour = 2 * decimal digit (* from 00 to 24, to represent midnight at the
                                end of a calendar day *);

    minute = 2 * decimal digit (* from 00 to 59 *);

    second = 2 * decimal digit (* from 00 to 60, to accommodate leap second *);

    fraction = decimal digit, { decimal digit };

&emsp;&emsp;EXAMPLES:

&emsp;&emsp;`2016-02-08`

&emsp;&emsp;`2016-02-08T16:08Z`

&emsp;&emsp;`2016-02-08T16:08:25Z`

&emsp;&emsp;`2016-02-08T16:08:25.943Z`

&emsp;&emsp;`2016-02-08T00:00:00Z`

&emsp;&emsp;`2016-02-08T16:08:00Z`

&emsp;&emsp;`2016-02-08T16:08:25Z`

&emsp;&emsp;`2016-02-08T16:08:25.943Z`

The time component of every date/time-valued property **SHALL** be expressed in Coordinated Universal Time (UTC).

> NOTE 1: The name of every date/time-valued property ends in "Utc" to emphasize that requirement.

The time components of date/time-valued properties in property bags ([sec](#property-bags)) **SHOULD** also be expressed in UTC.

> NOTE 2: This might not always be possible if the property comes from a source that does not provide time zone information.

A SARIF producer **SHOULD NOT** provide more digits in `fraction` than warranted by the precision of the clock on the computer on which it runs.

A SARIF producer **SHOULD** express date/time properties, except for those that express product release dates, to a precision of at least whole seconds.

**Comment by michaelcfanning** [comment]
Approved during TC session #42.

**Comment by eddynaka** [comment]
@michaelcfanning , we could change to `expiryDateUtc` or `expiryTimeUtc`.
This would follow `releaseDateUtc`: https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317548
This would follow `startTimeUtc`: https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317574

**Comment by Motional-Charles-Wilson** [comment]
it would be nice to add a note with an example (`2023-07-14` presumes expansion to `2023-07-14T00:00Z`)

**Comment by schlaman-ms** [comment]
### Document location for issue:
Possible new subsection under §3.35 suppression object
§3.35.7 expiryDateUtc

**Comment by stacywray** [comment]
@michaelcfanning Regarding this issue, @sthagen mentioned that proposed changes for this issue were approved in 2021, but since then there have been new comments this year that need to be addressed, specifically a comment from July 13, 2023:

> it would be nice to add a note with an example (2023-07-14 presumes expansion to 2023-07-14T00:00Z)

**Comment by davidmalcolm** [comment]
> it would be nice to add a note with an example (`2023-07-14` presumes expansion to `2023-07-14T00:00Z`)

In particular, the wording "X through which the suppression is valid..." suggests that the suppression is valid at the instant of X, i.e. valid if current time <= X, when presumably it's valid if current time < X.

Perhaps "the date/time at which the suppression ceases to be valid" would be a less ambiguous wording?

**Comment by sthagen** [comment]
Per the TC meeting on 2023-12-07: 

> DECISION to approve the issue [Suggestion: add an expiryDateUtc property to suppression instances #492](https://github.com/oasis-tcs/sarif-spec/issues/492) as discussed implementing the comment of David Malcolm and the implicit expansion of midnight commented by Charles

**Comment by stacywray** [comment]
Incorporating @davidmalcolm's less ambiguous wording:

## 3.35.7 expiryDateUtc property  

A `suppression` object **MAY** contain a property named `expiryDateUtc` whose value is a string in the format specified in [§3.9](#3.9), specifying the UTC date (and optionally, the time) at which the suppression ceases to be valid.

A SARIF producer **SHOULD** omit the time component of the UTC unless the suppression requires a more granular validity precision.

~~~
        "expiryDateUtc": {
          "description": "The Coordinated Universal Time (UTC) date (and optionally, the time) at which the suppression ceases to be valid. ",
          "type": "string",
          "format": "date-time"
        },
~~~

TODO: Extend 3.9 to show expanded UTC dates of supported formats.

**Comment by stacywray** [comment]
## 3.9 Date/time properties

Certain properties in this document specify a date and time. The value of every such property, if present, **SHALL** be a string in the following format, which is compatible with the ISO standard for date and time formats [cite](#ISO8601;2004):

    date time = date, [ "T", time, "Z" ] (* UTC time *);

    date = year, "-", month, "-", day;

    year = 4 * decimal digit;

    month = 2 * decimal digit (* from 01 to 12 *);

    day = 2 * decimal digit (* from 01 to 31 *);

    time = hour, ":", minute, [ ":", second, [ ".", fraction ] ];

    hour = 2 * decimal digit (* from 00 to 24, to represent midnight at the
                                end of a calendar day *);

    minute = 2 * decimal digit (* from 00 to 59 *);

    second = 2 * decimal digit (* from 00 to 60, to accommodate leap second *);

    fraction = decimal digit, { decimal digit };

&emsp;&emsp;EXAMPLES:

&emsp;&emsp;`2016-02-08T00:00:00Z`

&emsp;&emsp;`2016-02-08T16:08:00Z`

&emsp;&emsp;`2016-02-08T16:08:25Z`

&emsp;&emsp;`2016-02-08T16:08:25.943Z`

The time component of every date/time-valued property **SHALL** be expressed in Coordinated Universal Time (UTC).

> NOTE 1: The name of every date/time-valued property ends in "Utc" to emphasize that requirement.

The time components of date/time-valued properties in property bags ([sec](#property-bags)) **SHOULD** also be expressed in UTC.

> NOTE 2: This might not always be possible if the property comes from a source that does not provide time zone information.

A SARIF producer **SHOULD NOT** provide more digits in `fraction` than warranted by the precision of the clock on the computer on which it runs.

A SARIF producer **SHOULD** express date/time properties, except for those that express product release dates, to a precision of at least whole seconds.

**Comment by sthagen** [comment]
I suggest to add the expanded form at the end of the existing examples listing instead of replacing the existing one:

Examples:
```
2016-02-08
2016-02-08T16:08Z
2016-02-08T16:08:25Z
2016-02-08T16:08:25.943Z
2016-02-08T00:00:00Z
2016-02-08T16:08:00Z
2016-02-08T16:08:25Z
2016-02-08T16:08:25.943Z
```
The time portion is optional (per grammar and should be).
So, the examples should show and not hide that.

**Comment by stacywray** [comment]
@sthagen I have updated the 3.9 example to reflect your suggestion. Thanks!
