### ISSUE TITLE
Requirements to finalize the errata

### ISSUE THREAD

**Issue by dmk42** [oasis-tcs/sarif-spec#509]
We received feedback on our errata with some helpful indications of what we need to do to get it published.  Here is a checklist of what we need.

- [x] Review the sarif-v2.1.0-errata01-csd01.docx file attached at the bottom of this issue to ensure that it correctly reflects what the TC approved.  (We will then need to add some changes to it to correct the URLs discussed below.)
- [x] Use the redlined document attached at the bottom of this issue as the new base, and reapply the changes in the errata with tracked changes.
- [x] Include the following files:  errata (list of changes), redlined text, complete text (optional but desirable), JSON files, and redline changes for the changed JSON file.  There should also be a "cover page" README document as discussed below.
- [x] There are two JSON files:
sarif-external-property-file-schema-2.1.0.json, and
sarif-schema-2.1.0.json .
The new sarif-2.1.0-rtm.6.json is meant to be a replacement for the latter.  The diffs are already included in the errata document; we should add a redlined sarif-schema JSON file as mentioned above, and rename the rtm file to replace the original sarif-schema file.  We should also include the unchanged sarif-external-property file just for completeness.  The README document should explain the purpose of each file in the whole bundle, including the status of the JSON files, and the fact that the unchanged external property file is being included for completeness.
- [x] All the URLs in the document that begin with "raw.githubusercontent...." are now broken.  OASIS has given us the directory [https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/csd01/schemas/](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/csd01/schemas/) to replace the broken links.  These fixes should all be included in the diffs that compose the errata document.

Here are the files that were supplied to us:
[sarif-v2.1.0-errata01-csd01.docx](https://github.com/oasis-tcs/sarif-spec/files/7812437/sarif-v2.1.0-errata01-csd01.docx)
[sarif-v2.1.0-errata01-csd01-redlined.docx](https://github.com/oasis-tcs/sarif-spec/files/7812438/sarif-v2.1.0-errata01-csd01-redlined.docx)

**Comment by VCOLAWTON** [comment]
[sarif-v2.1.0-errata01-csd01-Changes.docx](https://github.com/oasis-tcs/sarif-spec/files/8062707/sarif-v2.1.0-errata01-csd01-Changes.docx)

**Comment by fishoak** [comment]
I'm a bit confused. We were asked to check that the errata had been properly applied to the original document. I can find the errata, but the version of the document that is attached in the previous comment does not appear to have those changes. Should I be looking elsewhere for that document?

**Comment by dmk42** [comment]
My mistake, @fishoak .  Sorry about that.  We'll need one more iteration before it is ready for review.

**Comment by dmk42** [comment]
[sarif-v2.1.0-errata01-csd01-redlined-v2.docx](https://github.com/oasis-tcs/sarif-spec/files/8527005/sarif-v2.1.0-errata01-csd01-redlined-v2.docx)

Here is a new draft of the redlined document, with comprehensive edits by Courtney and light touch-up by me.  Please double-check that the changes match the intent.  Here are the the issues that remain to be addressed.

- 2.8 Issue #476:
In section K.4, update comprehensive SARIF file to make it valid
content.
- 2.9 Issue #477:
[Update the table of contents to include Appendix M.]

SARIF schema issues (outside of this file):
- 2.11 Issue #481
- 2.12 Issue #487
- 2.13 Issue #488

**Comment by katrinaoneil** [comment]
> [sarif-v2.1.0-errata01-csd01-redlined-v2.docx](https://github.com/oasis-tcs/sarif-spec/files/8527005/sarif-v2.1.0-errata01-csd01-redlined-v2.docx)
> 
> Here is a new draft of the redlined document, with comprehensive edits by Courtney and light touch-up by me. Please double-check that the changes match the intent. Here are the the issues that remain to be addressed.
> 
> * 2.8 Issue [Comprehensive SARIF file example is not a valid JSON. #476](https://github.com/oasis-tcs/sarif-spec/issues/476):
>   In section K.4, update comprehensive SARIF file to make it valid
>   content.
> * 2.9 Issue [Add appendices for media type and URI scheme registrations. #477](https://github.com/oasis-tcs/sarif-spec/issues/477):
>   [Update the table of contents to include Appendix M.]
> 
> SARIF schema issues (outside of this file):
> 
> * 2.11 Issue [Schema doesn't allow sarifLog.runs to be null. #481](https://github.com/oasis-tcs/sarif-spec/issues/481)
> * 2.12 Issue [Enums in the JSON Schema should include a type. #487](https://github.com/oasis-tcs/sarif-spec/issues/487)
> * 2.13 Issue [The schema of the `run.language`  and `toolComponent.language` properties is incorrect. #488](https://github.com/oasis-tcs/sarif-spec/issues/488)

Do we need to update Revision History (Appendix L)? Otherwise, looks good to me

**Comment by michaelcfanning** [comment]
I reviewed the redline and have a couple of comments around formatting of 'roles' and refining the 'url' artifact property in 3.4.3. Send those notes offline to @VCOLAWTON and @dmk42.

I don't see the updated schema files here and will go chase that down.

**Comment by dmk42** [comment]
[SARIF_ERRATA.zip](https://github.com/oasis-tcs/sarif-spec/files/8917030/SARIF_ERRATA.zip)

Here is the full package with the latest files I have, including a README to explain what they are.  These use the filenames that OASIS will want us to use.

The remaining steps are:

1.  Check that these files are at least as new as what @michaelcfanning has.
2.  Incorporate @katrinaoneil 's and @michaelcfanning 's comments into the redlined version, and backport the changes to the errata if necessary.
3. Fix the URLs inside the schema, because I still see some references to the github location.
4. Finally, make sure the schema URLs in the errata and redlined version line up with where they will appear on the OASIS web site.

**Comment by dmk42** [comment]
All the requirements were completed and the Errata document was published.
