### ISSUE TITLE
2.1.0 os standard references cos02

### ISSUE THREAD

**Issue by rillig** [oasis-tcs/sarif-spec#548]
https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html says:
> This prose specification is one component of a Work Product that also includes:
> * JSON schemas: https://docs.oasis-open.org/sarif/sarif/v2.1.0/cos02/schemas/

Is it intended that the `os` document references the schemas from `cos02`?
I'd expect that OASIS, as a publisher of many such standard, has quality controls that prevent obvious mistakes like this from happening.

**Comment by sthagen** [comment]
From my experience OASIS does have quality controls in place.
I still have to encounter a producer where quality controls result in a completely error free result.

**Comment by rillig** [comment]
I don't expect OASIS published documents to be completely error free. That's what the errata processes are for.

What I do expect though is that _common typical mistakes_ are detected automatically. When publishing several versions of a document, I assume that it happens from time to time that one version accidentally references a previous version.

When such a mistake has happened several times, I expect that there is a brief discussion on how mistakes like these can be prevented in the future. In the case of accidentally mixing document versions, I am assuming that checking the documents automatically is feasible and easy to implement.

I would be surprised if this were the first time that an accidental link from one version of the document to an outdated version is discovered, as OASIS has already published several large standards, with lots of opportunities for mistakes like these.

**Comment by sthagen** [comment]
The core of the issue has been labeled as erratum and the members of the committee may consider this feedback - I (who is the one suggesting to accept the issue as erratum) am only one of them.

The point of [my comment](https://github.com/oasis-tcs/sarif-spec/issues/548#issuecomment-1264444104) was: 
> Many people expect many things. 

I think, it is not good to discuss assumed OASIS processes here on Github.
Instead, provide that information to OASIS open directly.

**Comment by dmk42** [comment]
Fortunately, this was fixed with the publication of the Errata document.
