### ISSUE TITLE
Which goes first - "version" or "$schema"?

### ISSUE THREAD

**Issue by davidmalcolm** [oasis-tcs/sarif-spec#571]
[In v2.1.0, ](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html)

"3.13.2 version property" says: "Although the order in which properties appear in a JSON object value is not semantically significant, the version property SHOULD appear first."

However, in two of the three examples that have a "$schema", the $schema appears before the "version".

Am I right in thinking that these examples should be changed so that the "version" appears before the "$schema"?

**Comment by dmk42** [comment]
Thanks.  This has been addressed with the 2023-06-12 errata bundle.
