### ISSUE TITLE
Errata01 section 3.13.3, 4.3.2  (note 2 both) and title page - verify Schema URL is well chosen

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/sarif-spec#577]
Upfront: 
> This issue is **not** intended to delay or stop the progressing of ERRATA01,
but rather as input to any follow-up version of SARIF v2.1.0.

# Artifacts and URLs

Reading the errata01 prose diff as compared to the OASIS Standard v2.1.0 the change of host is fine, but not so sure we should confine the resource into the given path.

Rationale: That `csd01` part is guaranteed to not be included in the final stage path.

## Minimal Change Proposal

Instead of:

>NOTE 2: The SARIF schema is available at <https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/csd01/schemas/>

suggest to write:

>NOTE 2: The SARIF schema is available at <https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/schemas/>

or similarly (avoiding an intermediate stage identifier in the path).

**Note**: The same applies to the "Additional Artifacts" entry on the title page as well as to example JSON snippets.

## Follow-up question

Why do we not name the specific artifacts?

I would have expected the OS to name [sarif-schema-2.1.0.json](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/schemas/sarif-schema-2.1.0.json) and if referenced also
[sarif-external-property-file-schema-2.1.0.json](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/schemas/sarif-external-property-file-schema-2.1.0.json) as separate entries on the title page within that "Additional Artifacts" section.

Following the practice of other OASIS specifications we would list the following two artifacts in the ERRATA01 (assuming both are referenced) in alphabetical order:

- `sarif-external-property-file-schema-2.1.0.json` at <https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/schemas/sarif-external-property-file-schema-2.1.0.json>
- `sarif-schema-2.1.0.json` at <https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/schemas/sarif-schema-2.1.0.json>

Esp. in JSON example snippets, naming the specific URL to deference the schema file for consumers (or match against a catalog) is actionable while stating some folder reference with multiple files in it is not:

👎🏽 Ambiguous (in our case):
```json
"$schema": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/schemas/", 
```

👍🏽 Unambiguous:
```json
"$schema": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/schemas/sarif-schema-2.1.0.json", 
```

In section 4.3.2 "$schema property" we then would simply point to the corresponding schema file directly, instead to the `schemas` folder.

**Comment by dmk42** [comment]
Thanks, Stefan.  When we submitted a proposed errata document earlier (which we had to withdraw and work on -- this is the result), OASIS told us to use the `csd01` in the URL because that is where it would initially appear.  As the document progresses to later stages of adoption, `csd01` will change to whatever is next (`os` I think, but I'm not sure for errata).

**Comment by dmk42** [comment]
Thanks again.  This has been addressed with the 2023-06-12 errata bundle.
