### ISSUE TITLE
Consider adding 'rank' or 'probability' property

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#58]
Some tools produce an issue rank. It is difficult to normalize rank across tools. One idea is to normalize all these to a value from 0 to 1 (0 to 100% certainty of value). Some tools provide a numeric rank with no known upper bound , however.

**Comment by katrinaoneil** [comment]
Fortify uses what we call Fortify Priority Order (FPO), a custom system of ranking the issues based on:

- Impact (a static value from 0 to 5)
- Probability (a static value from 0 to 5)
- Accuracy (a static value from 0 to 5)
- Confidence (a dynamic value from 0 to 5)

Likelihood gets calculated dynamically based on Probability,  Accuracy, and Confidence, and depending on the value of Likelihood and Impact, the issues are placed in either Critical, High, Medium, or Low buckets

**Comment by michaelcfanning** [comment]
Closing as duplicate of #280
