### ISSUE TITLE
Errata01  20230619 Appendix M links to section 3 and 4 broken

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/sarif-spec#591]
When accepting all changes the links in the rightmost column of the table in appendix M appera to be broken.

When I replace them with links they look identical (field values on/off toggling) but then they work (jumping to section start of 3 and 4 respectively).

Could be an application specific problem.

Proposal: If possible make them work.

Also, there is no link to the reference entry of the RFC in:
> The following is a list of MIME types and file extensions for files that conform to this specification, registered according to [RFC2048]. 

Reference bundle <https://www.oasis-open.org/committees/document.php?document_id=71131&wg_abbrev=sarif> and file `sarif-v2.1.0-errata01-csd01-redlined.docx` (at the very end)

**Comment by dmk42** [comment]
Thanks!  I've fixed this directly in the redlined document without needing to add it to the errata document, because Appendix M is all new.  Any fixes to Annex M are just part of adding it to the standard.

**Comment by dmk42** [comment]
Completed

**Comment by dmk42** [comment]
Completed
