### ISSUE TITLE
Errata01 20230619 Section 1.2 Terminology - Entry result management system - artifacts link broken

### ISSUE THREAD

**Issue by sthagen** [oasis-tcs/sarif-spec#593]
When accepting all changes the link with the text artifacts in the first para of the result management system entry is broken

> software system that consumes the [log files] produced by [analysis tools], produces reports that enable engineering teams to assess the quality of their software >>>[artifacts]<<< at a point in time and to observe trends in the quality over time, and performs functions such as filing bugs and displaying information about individual [results]

Could be an application specific problem.

Proposal: If possible make them work.

Reference bundle <https://www.oasis-open.org/committees/document.php?document_id=71131&wg_abbrev=sarif> and file `sarif-v2.1.0-errata01-csd01-redlined.docx` (section 1.2 page 20 (on my machine) first para of entry result management system)

**Comment by dmk42** [comment]
Thanks!  I've fixed this in the redlined document and am updating #568 to incorporate it.

**Comment by dmk42** [comment]
Completed
