### ISSUE TITLE
Rationalize GitHub/CodeQL-proposed `precision` and `security-severity` properties

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#598]
GitHub Advanced Security accepts property bag-delivered values in its system to specify results precision and security level.

It would be good to rationalize these property values with current SARIF and to incorporate them, if appropriate, into the 2.2 update.

@adityasharad @lcartey

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#runautomationdetails-object
https://github.blog/changelog/2021-07-19-codeql-code-scanning-new-severity-levels-for-security-alerts/

**Comment by adityasharad** [comment]
@michaelcfanning I've created separate component issues for precision and security-severity.

**Comment by adityasharad** [comment]
Closing in favour of #611 and #612.
