### ISSUE TITLE
Can we cite ECMA-404 as normative?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#6]
Copied from https://github.com/sarif-standard/sarif-spec/issues/10, created by @lgolding:

**Comment by michaelcfanning** [comment]
ECMA-404 certainly needs to be cited as a normative reference. The SARIF JSON implementation requires that contents are valid JSON, and ECMA-404 is the normative reference for the format.

**Comment by lgolding** [comment]
This is done. We do cite ECMA 404 as normative. Whether ISO (which has much stricter requirements on what you can cite as normative) will accept this is a problem for another day. OASIS has no problem with it.
