### ISSUE TITLE
3.24.6 roles property has two "NOTE 3"s

### ISSUE THREAD

**Issue by davidmalcolm** [oasis-tcs/sarif-spec#634]
The 3.24.6 roles property (https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790867) has:

- NOTE 1
- NOTE 2
- NOTE 3
- NOTE 3

Presumably the last one should be NOTE 4.  Visible in both the HTML and PDF.

**Comment by sthagen** [comment]
## Proposal

Rewrite (line https://github.com/oasis-tcs/sarif-spec/blob/main/sarif-2.2/prose/edit/src/file-format-24-artifact-object.md?plain=1#L142):

```
    NOTE 3: The information conveyed by these values could be extracted from a VCS. These properties exist so SARIF consumers can have this information without needing access to the VCS.
```

as:

```
    NOTE 4: The information conveyed by these values could be extracted from a VCS. These properties exist so SARIF consumers can have this information without needing access to the VCS.
```
