### ISSUE TITLE
Enable traceability from converted SARIF file to original analysis tool log file

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#66]
On converting an issue from a native tool format to SARIF, it would be helpful to decorate a result with a location that points to the original problem in the native log and/or to embed the original content that was used to construct the SARIF equivalent.

This is helpful mostly for debugging converted content, as the information wouldn't be generally parseable. Converters shouldn't use this facility, therefore, expecting consumers to parse it. The properties member should contain all relevant information brought forward (that doesn't slot into a SARIF equivalent member)

**Comment by lgolding** [comment]
Proposal:

Consider this Android Studio output file:
```
<?xml version="1.0" encoding="UTF-8"?>
<problems>
  <problem>
    <file></file>
    <line>242</line>
    <module>northwindtraders-droid-2</module>
    <package>com.northwindtraders.droid.model</package>
    <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/northwindtraders-droid-2/src/main/java/com/northwindtraders/droid/model/Model.java" />
    <problem_class severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Assertions</problem_class>
    <hints />
    <description>Assertions are unreliable. Use BuildConfig.DEBUG conditional checks instead.</description>
  </problem>
</problems>
```

Today, the SARIF conversion tool in the SARIF SDK converts this to the following SARIF file:
```
{
  "$schema": "http://json.schemastore.org/sarif-1.0.0",
  "version": "1.0.0",
  "runs": [
    {
      "tool": {
        "name": "AndroidStudio"
      },
      # Some lines omitted for brevity ...
      "results": [
        {
          "ruleId": "Assertions",
          "message": "Assertions are unreliable. Use BuildConfig.DEBUG conditional checks instead.",
          "locations": [
            {
              "analysisTarget": {
                "uri": "northwindtraders-droid-2/src/main/java/com/northwindtraders/droid/model/Model.java",
                "uriBaseId": "$PROJECT_DIR$"
              },
              "fullyQualifiedLogicalName": "northwindtraders-droid-2\\com.northwindtraders.droid.model"
            }
          ],
          "properties": {
            "severity": "WARNING",
            "attributeKey": "WARNING_ATTRIBUTES"
          }
        }
      ]
    }
  ]
}
```
We propose to add a new property `originalLogContents` to the `result` object, as follows:
```
      "results": [
        {
          "ruleId": "Assertions",
          "message": "Assertions are unreliable. Use BuildConfig.DEBUG conditional checks instead.",
          "locations": [
            {
              "analysisTarget": {
                "uri": "northwindtraders-droid-2/src/main/java/com/northwindtraders/droid/model/Model.java",
                "uriBaseId": "$PROJECT_DIR$"
              },
              "fullyQualifiedLogicalName": "northwindtraders-droid-2\\com.northwindtraders.droid.model"
            }
          ],
          "originalLogContents": { # A new property whose type is a new type "originalLogContents"
            "physicalLocation": {
              "uri: "file:///C:/logs/northwind.log",
              "region": {
                "startLine": 3,
                "startColumn": 3,
                "endLine": 12,
                "endColumn": 13
            },
            "snippet": "<problem>\n  <file></file>\n  <line>242</line>\n … \n  </problem>"
          },
          "properties": {
            "severity": "WARNING",
            "attributeKey": "WARNING_ATTRIBUTES"
          }
```
**NAME** Among any other comments you have, please feel free to suggest an alternative to the name "`originalLogContents`".

**Comment by lgolding** [comment]
My proposal above omitted something that @michaelcfanning and I had discussed. For purposes of debugging the converter, it's useful for the SARIF file to include information about the name and version of the converter. So the full proposal would be as follows:

* The addition of the `conversionTool` property to the `run` object. The value of this property is a `tool` object, the same type as the `run.tool` property.
* The addition of the `originalLogContents` property to the `result` object. The value of this property is an object of the newly introduced type `originalLogContents`.
```
{
  "$schema": "http://json.schemastore.org/sarif-1.0.0",
  "version": "1.0.0",
  "runs": [
    {
      "tool": {
        "name": "AndroidStudio"
      },
      "conversionTool": {
        "name": "SARIF SDK Multitool",
        "version": "2.0.1"
      },
      # Some lines omitted for brevity ...
      "results": [
        {
          "ruleId": "Assertions",
          "message": "Assertions are unreliable. Use BuildConfig.DEBUG conditional checks instead.",
          "locations": [
            {
              "analysisTarget": {
                "uri": "northwindtraders-droid-2/src/main/java/com/northwindtraders/droid/model/Model.java",
                "uriBaseId": "$PROJECT_DIR$"
              },
              "fullyQualifiedLogicalName": "northwindtraders-droid-2\\com.northwindtraders.droid.model"
            }
          ],
          "originalLogContents": { # A new property whose type is a new type "originalLogContents"
            "physicalLocation": {
              "uri: "file:///C:/logs/northwind.log",
              "region": {
                "startLine": 3,
                "startColumn": 3,
                "endLine": 12,
                "endColumn": 13
            },
            "snippet": "<problem>\n  <file></file>\n  <line>242</line>\n … \n  </problem>"
          },          "properties": {
            "severity": "WARNING",
            "attributeKey": "WARNING_ATTRIBUTES"
          }
        }
      ]
    }
  ]
}
```

**Comment by lgolding** [comment]
```
{
  "$schema": "http://json.schemastore.org/sarif-1.0.0",
  "version": "1.0.0",
  "runs": [
    {
      "tool": {
        "name": "AndroidStudio"
      },
      "originalLogFile": {
        "uri": "file:///C:/logs/northwind.log"
      },
      "conversionTool": {
        "name": "SARIF SDK Multitool",
        "version": "2.0.1"
      },
      # Some lines omitted for brevity ...
      "results": [
        {
          "ruleId": "Assertions",
          "message": "Assertions are unreliable. Use BuildConfig.DEBUG conditional checks instead.",
          "locations": [
            {
              "analysisTarget": {
                "uri": "northwindtraders-droid-2/src/main/java/com/northwindtraders/droid/model/Model.java",
                "uriBaseId": "$PROJECT_DIR$"
              },
              "fullyQualifiedLogicalName": "northwindtraders-droid-2\\com.northwindtraders.droid.model"
            }
          ],
          "originalLogContents": { # A new property whose type is a new type "originalLogContents"
            "physicalLocation": {
              "uri: "file:///C:/logs/northwind.log",
              "region": {
                "startLine": 3,
                "startColumn": 3,
                "endLine": 12,
                "endColumn": 13
            },
            "snippet": "<problem>\n  <file></file>\n  <line>242</line>\n … \n  </problem>"
          },
          "properties": {
            "severity": "WARNING",
            "attributeKey": "WARNING_ATTRIBUTES"
          }
        }
      ]
    }
  ]
}
```

**Comment by michaelcfanning** [comment]
Agree with the change. Can't we now eliminate the originalLogContents type at this point? 

In preference of a originalFileContentsRegion property of type 'region'. 

i.e., hoist the region, make it a property on result.

**Comment by lgolding** [comment]
@michaelcfanning  We can do that, but we would then need to hoist the snippet as well:
```
      "results": [
        {
          "ruleId": "Assertions",
          "message": "Assertions are unreliable. Use BuildConfig.DEBUG conditional checks instead.",
          "locations": [
            {
              "analysisTarget": {
                "uri": "northwindtraders-droid-2/src/main/java/com/northwindtraders/droid/model/Model.java",
                "uriBaseId": "$PROJECT_DIR$"
              },
              "fullyQualifiedLogicalName": "northwindtraders-droid-2\\com.northwindtraders.droid.model"
            }
          ],
          "originalLogFileRegion": {
            "startLine": 3,
            "startColumn": 3,
            "endLine": 12,
            "endColumn": 13
          },
          "originalLogFileSnippet": "<problem>\n  <file></file>\n  <line>242</line>\n … \n  </problem>"
          "properties": {
            "severity": "WARNING",
            "attributeKey": "WARNING_ATTRIBUTES"
          }
        }
      ]
```
It's more or less a matter of taste whether we want to wrap the two `originalLogFileXxx` properties into an `originalLogFileContents` object. IMO if there were a _third_ such original-log-file-related property, we would definitely want to wrap it. Thoughts?

**Comment by michaelcfanning** [comment]
honestly, had forgotten the snippet. :) i agree, with three, you want a new object. with only two, it's debatable, particularly if we don't foresee it being common for both properties to be present. 

it's a close call.

**Comment by lgolding** [comment]
@michaelcfanning In that case I suggest leaving the wrapper. It's a good future-proofing, and it DRYs out the names (there is only one name of the form `originalLogFileXxxx`.

**Comment by sdrees** [comment]
What somehow makes it hard for me to value the add-on is the region info mostly coming out of thin air I guess 😄 In the original snippet on top there is no place I spot the start(end)Line(Column) quadruple. W.r.t. the naming of originalLog... I hope we come up with something more descriptive, but myself currently am blank - reason for the hope: "original log file" et al. carries an unclear "original" and "log" and "file" as semantic for what? ... and nothing real.

**Comment by michaelcfanning** [comment]
I agree that separating the source file uri from each result region isn't ideal. But repeating the URI for each region when it never changes for a run seems worse. And this is why the embedded snippet exists, so that people scanning the file can just take a look.

I also agree the name's not great and am also having trouble generating a new one. unconvertedLogFile? nonSarifLogFile? 'source' is not a great term to consider given its overloading.

**Comment by sdrees** [comment]
... and if we focus on it's contribution, not it's provenience - I mean what it brings to the table, not what it's random "form" / source format is?

**Comment by lgolding** [comment]
@sdrees Stefan, when you say that the region info comes "out of thin air", do you mean that the region info does not occur in the original log file (the Android Studio log file)? That is not surprising. The `result.originalLogContents.region` property specifies the location of the snippet within the original log file, just as a compiler diagnostic specifies the location of an error within a source file. If you look in a source file, you won't find that location information! The compiler keeps track of that location itself, as it parses the file.

It's the same thing here. The SARIF converter keeps track of its location as it parses the original file, and mentions that location when it creates the `originalLogContents` property. (But it doesn't have to: `region` will be optional.)

On the other hand, if you mean that the region information comes "out of thin air" because you don't see the URI of the file that the region refers to, then yes, as Michael said, we thought it best not to repeat the same "original log file URI" in every `result` object. Instead, we place it in a separate `run.originalLogFile` property.

Now as far as naming goes, you wrote:

> "original log file" et al. carries an unclear "original" and "log" and "file" as semantic for what? ... and nothing real.

But actually, the Terminology section of the spec does define "log file":

> **log file**
>     output file produced by a static analysis tool, which enumerates the results produced by the tool

... so it really does have semantics. Here it refers to the log file produced by the static analysis tool (Android Studio in my example).

I do agree that "original" is a bit unclear. Michael's "unconverted" comes closer. Or, since I've now explained that this is the log file produced by the static analysis tool, what about `analysisToolLogFile`?
