### ISSUE TITLE
Provide a physicalLocation on a stack frame

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#69]
We currently break out uri, uriBaseId, etc. on a stack frame instead of putting a physicalLocation on it. I think the reason is that we didn't see value in providing all the information in a physicalLocation (a region doesn't exactly make sense for a stack frame).

I think it might be preferable to simply have the physicalLocation object, though, with the caveat that its region data is not likely to cover a multi-line span.

**Comment by lgolding** [comment]
Closed in c443e9a.
