### ISSUE TITLE
Can we cite FIPS PUB 180-4, Secure Hash Standard, as normative?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#7]
Copied from https://github.com/sarif-standard/sarif-spec/issues/11, created by @lgolding:

**Comment by michaelcfanning** [comment]
I believe we can cite this reference as normative. The SARIF spec mandates that producers who populate file object with hash details provide hash values that comply with this normative spec.

**Comment by lgolding** [comment]
@michaelcfanning I opened this issue when we thought we were going to ISO, and ISO has really strict rules on what you can cite as normative. We're going to OASIS so this is moot. If we send this to ISO later on and they call us on this, that's plenty of time to address it then.
