### ISSUE TITLE
Ensure spec properly accounts for tools that emit line #'s only for code locations

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#75]
In some contexts, a compiler may emit line numbers only (with no column details). A line may be or arbitrary length (particularly if code authors use continuation tokens). As a result, some emitted data may produce multiple physical locations that aren't differentiated.

This may be a problem with relatedLocations. The JSON schema currently requires this property to be 'unique' meaning that it is a set of non-duplicated items. In order for a SARIF producer to meet our spec currently, the producer would need to track whether each annotatedCodeLocation in a relatedLocations instance is unique.

**Comment by lukecartey** [comment]
This is also a problem if multiple program elements occur at the same line and column location. For example, C/C++ programs with macro invocations can result in multiple program elements occurring at the same line and column location in the program.

**Comment by lgolding** [comment]
@michaelcfanning As we've discussed, the solution here will be to no longer require the elements of the `run.results` array to be unique. But I'll add a note to explain why.
