### ISSUE TITLE
Can we cite RFC 3986 as normative?

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#8]
Copied from https://github.com/sarif-standard/sarif-spec/issues/12, created by @lgolding:

... and figure out if we can cite it as normative.

**Comment by lgolding** [comment]
Comment from @lgolding:

We now cite RFC 3986 as normative. Change the title of this issue to "Can we cite as normative".

**Comment by michaelcfanning** [comment]
Yes, we specify that some SARIF properties MUST be populated with values that conform to RFC 3986, which makes these references in our spec normative: users must comply as required with RFC 3986 to produce valid SARIF.

**Comment by lgolding** [comment]
This is done. OASIS has no trouble with our citing this as normative. Whether ISO will accept it is a problem for another day.
