### ISSUE TITLE
Code flow enhancements

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#80]
This is a bucket issue to capture code flow discussions.

**Comment by michaelcfanning** [comment]
The approved change here is to make code flows represent information/state that drives UX only. We will remove all notion of 'kind' etc. that attempts to codify program semantics in the code flow.

**Comment by lgolding** [comment]
We are actually making two changes:

1. Remove the `kind`-related properties from `annotatedCodeLocation` (but keep `annotatedCodeLocation.state`, which is useful for presenting a "watch window" experience as the user steps through the code flow).
2. Enable the representation of multiple simultaneous threads of execution in a single code flow.
