### ISSUE TITLE
Consider adding attachments property 

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#83]

**Comment by lgolding** [comment]
Mechanism to associate arbitrary files with a set of results. So it's a property of the `run` object. Possibly also a property of the `result` object, _e.g._, a screen shot, or a file containing a checker's internal representation.

```
runs:
[
  {
    "attachments": [                    # An array of uriReference objects.
       { "uri": ..., "uriBaseId": ... },
       { "uri": ..., "uriBaseId": ... }
    ]
  }
]
```
