### ISSUE TITLE
Add path normalization guidance for URLs

### ISSUE THREAD

**Issue by michaelcfanning** [oasis-tcs/sarif-spec#86]

**Comment by michaelcfanning** [comment]
Absolute URLs that are deterministic run-over-run (i.e., not subject to alteration due to differences in tool execution environment such a root drive letters), require no action, otherwise:

1. Break URL into base absolute URI that is non-deterministic (for example, an enlistment root). Store this information in the run.uriBaseIds property, if necessary, and create a name (eg., $SRCROOT) to identify the non-deterministic root. This name s/be consistent run-over run.
2. In the uri Reference, populate the uri value with the relative, deterministic url. 
3. Populate uriBase with the appropriate named variable, e.g., $SRCROOT$

**Comment by lgolding** [comment]
@michaelcfanning I will do this one once we've merged in the other URL-related changes (#63, #64) after tomorrow's TC meeting. That change draft is already big and complicated. Once it's merged, this one will be a small change and easy to review.
