### ISSUE TITLE
Cite  source for list of hash algorithms

### ISSUE THREAD

**Issue by lgolding** [oasis-tcs/sarif-spec#9]
Copied from https://github.com/sarif-standard/sarif-spec/issues/13, created by @lgolding:

The list comes from https://en.wikipedia.org/wiki/List_of_hash_functions. Is this ok?

**Comment by lgolding** [comment]
Comment from @lgolding:

(We've since added a few to the list we got from wikipedia)

**Comment by michaelcfanning** [comment]
Consider pruning the hash type list

**Comment by lgolding** [comment]
@michaelcfanning I am closing this issue. I opened it because I had copied a long list from wikipedia. We have now decided (#107) to settle on a small list of hash algorithms, so this issue is now moot.

**Comment by lgolding** [comment]
@michaelcfanning Now that we've hashed out (!) our approach to #107, I'm closing this again. I'm going with `resolved-duplicate` because #107 takes care of it by citing the IANA registry (while still allowing non-IANA values, but not citing a definitive list).

**Comment by michaelcfanning** [comment]
@lgolding at long last I am receiving email notifications of these updates. FYI. :) thanks for the info.
