### ISSUE TITLE
invocation.fileName -> invocation.executableLocation

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#95]
Changing fileName to executablePath (or execPath) in the invocation object would be more specific.

**Comment by michaelcfanning** [comment]
This property was originally named exePath, I believe. someone pointed out that invocations can originate with non-executables, a script file for example, so the name was changed. I see that the spec change still explicitly refers to executables, if we don't change the property name, we should update the spec text.

**Comment by michaelcfanning** [comment]
Approved in SARIF project editor's review
