### ISSUE TITLE
Add redactionToken property to run object

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#96]
The Invocation Object's commandLine says to replace sensitive data with **[REMOVED]**.  There is no mechanism to escape this value if the string is naturally occurring.

I propose that a new property call **redactedValue** be added to the invocation object and other objects that need such a concept.  If the property is not defined there is no redacted data.  If the property is defined the value SHOULD be '[REMOVED]' or another value that does not naturally occur in the text this is applied to. The value '[REDACTED]' seems like a better value to me, but I do not have a strong opinion.

**Comment by michaelcfanning** [comment]
Yes. redactionToken is the name. Add it to the run object. It SHALL be present if any information has, in fact, been redacted from the log file.
