### ISSUE TITLE
file object's contents property

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#97]
The File Object's **content** property description says that, if the file is binary, then its bytes should be base64 encoded, and if it is a text file, then it should be converted to UTF-8 and then be base64 encoded.  Recoding a text file may change the way that the tool processed the file, so maybe this should not be done.

It might be better to have a textContents property for the case of text files. In this case the text could converted to UTF-8, and stored directly as the value (not base64 encoded).

**Comment by lgolding** [comment]
@kupsch @michaelcfanning
Yes, I've never liked that we base64-encode text files. So is this what you are you suggesting?

1. For _all_ files, `contents` contains a base64-encoding of the original file (that way, a consumer can always recover the original file contents, even if it's a text file in some random encoding).
AND
2. For text files only, `textContents` contains a UTF-8 transcoding of the original file (that way, a viewer can always display the contents).
AND
3. Both `contents` and `textContents` are optional (for example, for a text file, a producer _could_ choose to populate `textContents` but not `contents`).

**Comment by michaelcfanning** [comment]
Sounds good to me.

**Comment by lgolding** [comment]
@kupsch @michaelcfanning:

I will introduce a `fileContent` object as follows, and use it for _all_ properties that contain text from an external file (not just `file.contents`):
```
{    # A fileContent object
  "text": "Text file contents, encoded as UTF-8",
  "binary": "Base64 encoded raw file bytes"
}
```

**Comment by lgolding** [comment]
With that design, this is now a breaking change.
