### ISSUE TITLE
Result Object's snippet property

### ISSUE THREAD

**Issue by kupsch** [oasis-tcs/sarif-spec#99]
The result object's snippet property, would be better placed in a location, since it might be useful to have a snippet from each location. Being part of location gives the snippet an associated file.  There should also be a **snippetRegion** that specifies where the snippet came from within the file.  If the snippetRegion property is absent, then the region should be the same as the location.  The snippetRegion SHOULD cover the locations region, but MAY be larger.

**Comment by michaelcfanning** [comment]
Project editor's conclusion: we should move the snippet property from the result object to the physicalLocation. We should add a region to the snippet object. We should remove use of region properties in the spec where they are parallel to a snippet (and the snippet.region replaces them, for example, on the analysisToolLogFileContents object).

**Comment by lgolding** [comment]
@michaelcfanning There isn't a "`snippet`" object. The thing that will be getting a new `region` property is the `fileContent` object.

**Comment by michaelcfanning** [comment]
We need to talk further about this.

**Comment by lgolding** [comment]
@michaelcfanning I agree. I tried to write this section yesterday and got all tangled up.

**Comment by lgolding** [comment]
Closed by 640b568.
